"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,BookOpen,Calculator,Check,ChevronDown,ImagePlus,Package,Plus,RefreshCw,Save,Search,Sprout,Upload} from "lucide-react";
import {CATEGORIES,LIBRARY_CATEGORIES} from "@/lib/constants";
import {fromCatalogRow,fromGalleryRow,fromVariantRow,fromVendorRow,toCatalogRow,toVariantRow,toVendorRow} from "@/lib/mappers";
import {uploadImage} from "@/lib/supabase/storage";
import styles from "./HouseControl.module.css";

const blankProduct=()=>({id:"",line:"everyday",available:true,limited:false,name:{vi:"",en:""},notes:{vi:"",en:""},brew:{vi:"",en:""},packSize:"",photoUrl:"",photoPosition:"50% 50%",price:undefined,stockHaGiang:undefined,stockSocSon:undefined,batch:"",soldCount:0,flavors:{},kind:"tea",vendorId:"",variants:[]});
const blankVendor=()=>({id:"",name:"",region:"",photo:"",crops:"",story:{vi:"",en:""},phone:"",note:"",active:true,sortOrder:0});
const blankArticle=source=>({source,id:"",category:source==="wiki"?"legacy":"types",title:{vi:"",en:""},body:{vi:"",en:""}});
const slug=value=>`${value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,36)}-${Date.now().toString(36)}`;
const statsToText=stats=>(stats||[]).map(item=>`${item.value} | ${item.label?.en||""} | ${item.label?.vi||""}`).join("\n");
const textToStats=text=>text.split("\n").map(line=>{const [value,en,vi]=line.split("|").map(part=>(part||"").trim());return value?{value,label:{en,vi:vi||en}}:null}).filter(Boolean);
const numberValue=value=>Number.isFinite(Number(value))?Number(value):0;

export default function HouseControl({supabase,email,onLogout}){
 const [tab,setTab]=useState("catalog"),[products,setProducts]=useState([]),[variants,setVariants]=useState([]),[vendors,setVendors]=useState([]),[home,setHome]=useState(null),[stories,setStories]=useState([]),[reading,setReading]=useState([]),[gallery,setGallery]=useState([]),[product,setProduct]=useState(null),[vendor,setVendor]=useState(null),[article,setArticle]=useState(null),[galleryItem,setGalleryItem]=useState(null),[house,setHouse]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[saved,setSaved]=useState(""),[error,setError]=useState(""),[catalogQuery,setCatalogQuery]=useState(""),[catalogLine,setCatalogLine]=useState("all"),[catalogStatus,setCatalogStatus]=useState("all"),[catalogSort,setCatalogSort]=useState("name"),[expandedProductId,setExpandedProductId]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const [p,pv,v,h,w,l,g]=await Promise.all([supabase.from("catalog_products").select("*"),supabase.from("catalog_variants").select("*"),supabase.from("vendors").select("*").order("sort_order"),supabase.from("settings_home").select("*").eq("id",1).maybeSingle(),supabase.from("wiki_articles").select("*"),supabase.from("library_articles").select("*"),supabase.from("gallery_images").select("*").order("created_at",{ascending:false})]);if([p,pv,v,h,w,l,g].some(result=>result.error))setError("Không tải được toàn bộ dữ liệu của Nhà.");if(!p.error)setProducts((p.data||[]).map(fromCatalogRow));if(!pv.error)setVariants((pv.data||[]).map(row=>({...fromVariantRow(row),productId:row.product_id,originalWeight:row.weight})));if(!v.error)setVendors((v.data||[]).map(fromVendorRow));if(!w.error)setStories(w.data||[]);if(!l.error)setReading(l.data||[]);if(!g.error)setGallery((g.data||[]).map(fromGalleryRow));if(!h.error){setHome(h.data);setHouse({producerName:h.data?.producer_name||"",producerPhoto:h.data?.producer_photo||"",roleVi:h.data?.producer_role?.vi||"",roleEn:h.data?.producer_role?.en||"",quoteVi:h.data?.producer_quote?.vi||"",quoteEn:h.data?.producer_quote?.en||"",stats:statsToText(h.data?.origin_stats)})}setLoading(false)},[supabase]);
 useEffect(()=>{load()},[load]);
 const flash=message=>{setSaved(message);setTimeout(()=>setSaved(""),1800)};
 const saveProduct=async event=>{event.preventDefault();if(!product?.name?.vi?.trim()&&!product?.name?.en?.trim())return;setSaving(true);setError("");const number=value=>value===""||value==null?undefined:Number(value),next={...product,id:product.id||slug(product.name.en||product.name.vi),price:number(product.price),stockHaGiang:number(product.stockHaGiang),stockSocSon:number(product.stockSocSon)};const {error:productError}=await supabase.from("catalog_products").upsert(toCatalogRow(next));let variantError=null;const rows=(next.variants||[]).filter(item=>item.weight?.trim()).map(item=>toVariantRow(next.id,{...item,price:number(item.price),stockHaGiang:number(item.stockHaGiang),stockSocSon:number(item.stockSocSon)}));if(!productError&&rows.length)({error:variantError}=await supabase.from("catalog_variants").upsert(rows));setSaving(false);if(productError||variantError){setError("Chưa lưu được toàn bộ sản phẩm và quy cách.");return}setProduct(null);flash("Đã lưu sản phẩm");load()};
 const toggleAvailable=async item=>{const available=!item.available;const {error:updateError}=await supabase.from("catalog_products").update({available}).eq("id",item.id);if(updateError){setError("Chưa cập nhật được tình trạng bán.");return}setProducts(current=>current.map(row=>row.id===item.id?{...row,available}:row))};
 const saveVendor=async event=>{event.preventDefault();if(!vendor?.name?.trim())return;setSaving(true);const next={...vendor,id:vendor.id||slug(vendor.name),sortOrder:vendor.sortOrder??vendors.length};const {error:saveError}=await supabase.from("vendors").upsert(toVendorRow(next));setSaving(false);if(saveError){setError("Chưa lưu được nhà cung cấp.");return}setVendor(null);flash("Đã lưu hồ sơ vùng");load()};
 const saveHouse=async event=>{event.preventDefault();setSaving(true);const row={producer_name:house.producerName.trim(),producer_photo:house.producerPhoto.trim(),producer_role:{vi:house.roleVi.trim(),en:house.roleEn.trim()},producer_quote:{vi:house.quoteVi.trim(),en:house.quoteEn.trim()},origin_stats:textToStats(house.stats)};const {error:saveError}=await supabase.from("settings_home").update(row).eq("id",1);setSaving(false);if(saveError){setError("Chưa lưu được hồ sơ Nhà.");return}flash("Đã lưu hồ sơ Nhà");load()};
 const saveArticle=async event=>{event.preventDefault();if(!article?.title?.vi?.trim()&&!article?.title?.en?.trim())return;setSaving(true);const table=article.source==="wiki"?"wiki_articles":"library_articles",row={id:article.id||slug(article.title.en||article.title.vi),category:article.category,title:article.title,body:article.body};const {error:saveError}=await supabase.from(table).upsert(row);setSaving(false);if(saveError){setError("Chưa lưu được bài viết.");return}setArticle(null);flash("Đã lưu bài viết");load()};
 const saveGallery=async event=>{event.preventDefault();setSaving(true);const {error:saveError}=await supabase.from("gallery_images").update({caption:galleryItem.caption}).eq("id",galleryItem.id);setSaving(false);if(saveError){setError("Chưa lưu được chú thích ảnh.");return}setGalleryItem(null);flash("Đã lưu chú thích");load()};
 const upload=async(file,folder,apply)=>{if(!file)return;setSaving(true);setError("");try{apply(await uploadImage(supabase,file,folder))}catch{setError("Tải ảnh thất bại.")}finally{setSaving(false)}};
 const replaceHomePhoto=async(index,file)=>{if(!file)return;setSaving(true);setError("");try{const url=await uploadImage(supabase,file,"home"),photos=[...(home?.featured_photos||[])];photos[index]=url;const {error:updateError}=await supabase.from("settings_home").update({featured_photos:photos,featured_photo:photos[0]}).eq("id",1);if(updateError)throw updateError;flash(`Đã thay ảnh trang chủ ${index+1}`);load()}catch{setError("Thay ảnh trang chủ thất bại.")}finally{setSaving(false)}};
 const addHomePhoto=async file=>{if(!file)return;setSaving(true);try{const url=await uploadImage(supabase,file,"home");const photos=[...(home?.featured_photos||[]),url];const {error:updateError}=await supabase.from("settings_home").update({featured_photos:photos,featured_photo:photos[0]}).eq("id",1);if(updateError)throw updateError;flash("Đã thêm ảnh trang chủ");load()}catch{setError("Tải ảnh trang chủ thất bại.")}finally{setSaving(false)}};
 const addGalleryPhoto=async file=>{if(!file)return;setSaving(true);try{const url=await uploadImage(supabase,file,"gallery"),item={id:slug("gallery"),url,caption:{vi:"",en:""}};const {error:insertError}=await supabase.from("gallery_images").insert(item);if(insertError)throw insertError;flash("Đã thêm ảnh thư viện");load()}catch{setError("Tải ảnh thư viện thất bại.")}finally{setSaving(false)}};
 const field=(label,value,onChange,props={})=>{const {textarea,...fieldProps}=props;return <label>{label}{textarea?<textarea value={value||""} onChange={event=>onChange(event.target.value)} {...fieldProps}/>:<input value={value??""} onChange={event=>onChange(event.target.value)} {...fieldProps}/>}</label>};
 const variantMap=useMemo(()=>variants.reduce((map,item)=>{(map[item.productId]??=[]).push(item);return map},{}),[variants]);
 const money=value=>value==null||value===""?"Chưa có giá":`${Number(value).toLocaleString("vi-VN")} ₫`;
 const lineLabel=line=>({everyday:"Dùng hằng ngày",reserve:"Dòng tuyển chọn",sample:"Mẫu thử"}[line]||line||"Chưa phân dòng");
 const kindLabel=kind=>kind==="goods"?"Nông sản":"Trà";
 const editProduct=item=>setProduct({...item,variants:(variantMap[item.id]||[]).map(row=>({...row}))});
 const catalogRows=useMemo(()=>products.map(item=>{
  const productVariants=variantMap[item.id]||[],source=productVariants.length?productVariants:[item],prices=source.map(row=>row.price).filter(value=>value!==undefined&&value!==null&&value!=="").map(Number).filter(Number.isFinite),stockHaGiang=source.reduce((sum,row)=>sum+numberValue(row.stockHaGiang),0),stockSocSon=source.reduce((sum,row)=>sum+numberValue(row.stockSocSon),0);
  return {...item,productVariants,priceMin:prices.length?Math.min(...prices):undefined,priceMax:prices.length?Math.max(...prices):undefined,stockHaGiangTotal:stockHaGiang,stockSocSonTotal:stockSocSon,totalStock:stockHaGiang+stockSocSon};
 }).filter(item=>{
  const query=catalogQuery.trim().toLocaleLowerCase("vi");
  const matchesQuery=!query||[item.name?.vi,item.name?.en,item.id,item.packSize,item.batch].some(value=>String(value||"").toLocaleLowerCase("vi").includes(query));
  const matchesLine=catalogLine==="all"||item.line===catalogLine;
  const matchesStatus=catalogStatus==="all"||(catalogStatus==="available"?item.available:!item.available);
  return matchesQuery&&matchesLine&&matchesStatus;
 }).sort((a,b)=>catalogSort==="stock-desc"?b.totalStock-a.totalStock:catalogSort==="price-asc"?(a.priceMin??Number.MAX_SAFE_INTEGER)-(b.priceMin??Number.MAX_SAFE_INTEGER):(a.name?.vi||a.name?.en||"").localeCompare(b.name?.vi||b.name?.en||"","vi")),[products,variantMap,catalogQuery,catalogLine,catalogStatus,catalogSort]);
 const priceRange=item=>item.priceMin==null?"Chưa có giá":item.priceMin===item.priceMax?money(item.priceMin):`${Number(item.priceMin).toLocaleString("vi-VN")}–${Number(item.priceMax).toLocaleString("vi-VN")} ₫`;
 const clearCatalogFilters=()=>{setCatalogQuery("");setCatalogLine("all");setCatalogStatus("all");setCatalogSort("name")};
 return <main className={styles.page}>
  <header className={styles.top}><div><Link href="/admin"><ArrowLeft/>Điều phối</Link><span>House control</span></div><div><span><b>{email}</b><small>Không gian quản trị</small></span><button onClick={load} disabled={loading} aria-label="Làm mới"><RefreshCw/></button><button onClick={onLogout}>Đăng xuất</button></div></header>
  <section className={styles.heading}><div><p>Những gì khách nhìn thấy</p><h1>Nhà, danh mục và vùng trà.</h1></div><span>Mọi thay đổi ở đây đi thẳng vào website đang vận hành.</span></section>
  <nav className={styles.tabs}>{[["catalog","Danh mục",Package],["vendors","Vùng & người",Sprout],["content","Nội dung",BookOpen],["house","Hồ sơ Nhà",ImagePlus]].map(([id,label,Icon])=><button key={id} className={tab===id?styles.active:""} onClick={()=>setTab(id)}><Icon/>{label}</button>)}</nav>
  {error&&<p className={styles.error} role="alert">{error}</p>}{saved&&<p className={styles.saved}><Check/>{saved}</p>}
  {tab==="catalog"&&<section className={`${styles.panel} ${styles.catalogPanel}`}>
   <header><div><p>Danh mục đang vận hành</p><h2>Sản phẩm, giá và tồn kho</h2></div><button type="button" onClick={()=>setProduct(blankProduct())}><Plus/>Thêm sản phẩm</button></header>
   <div className={styles.catalogSummary} aria-label="Tóm tắt danh mục">
    <div><span>Tất cả</span><strong>{products.length}</strong></div><div><span>Đang bán</span><strong>{products.filter(item=>item.available).length}</strong></div><div><span>Đang ẩn</span><strong>{products.filter(item=>!item.available).length}</strong></div><div><span>Quy cách</span><strong>{variants.length}</strong></div>
   </div>
   <div className={styles.catalogTools}>
    <label className={styles.catalogSearch}><span>Tìm sản phẩm</span><div><Search/><input type="search" value={catalogQuery} onChange={event=>setCatalogQuery(event.target.value)} placeholder="Tên, mã, mẻ trà…"/></div></label>
    <label><span>Dòng</span><select value={catalogLine} onChange={event=>setCatalogLine(event.target.value)}><option value="all">Tất cả dòng</option><option value="everyday">Dùng hằng ngày</option><option value="reserve">Dòng tuyển chọn</option><option value="sample">Mẫu thử</option></select></label>
    <label><span>Trạng thái</span><select value={catalogStatus} onChange={event=>setCatalogStatus(event.target.value)}><option value="all">Tất cả trạng thái</option><option value="available">Đang bán</option><option value="hidden">Đang ẩn</option></select></label>
    <label><span>Sắp xếp</span><select value={catalogSort} onChange={event=>setCatalogSort(event.target.value)}><option value="name">Tên A–Z</option><option value="stock-desc">Tồn nhiều trước</option><option value="price-asc">Giá thấp trước</option></select></label>
   </div>
   <div className={styles.catalogResultBar}><span aria-live="polite">{loading?"Đang tải danh mục…":`${catalogRows.length} sản phẩm`}</span>{(catalogQuery||catalogLine!=="all"||catalogStatus!=="all"||catalogSort!=="name")&&<button type="button" onClick={clearCatalogFilters}>Xóa bộ lọc</button>}</div>
   <div className={styles.catalogLedger}>
    <div className={styles.catalogHead} aria-hidden="true"><span>Sản phẩm</span><span>Trạng thái</span><span>Giá bán</span><span>Hà Giang</span><span>Sóc Sơn</span><span>Quy cách</span></div>
    {catalogRows.map(item=>{const expanded=expandedProductId===item.id;return <article className={styles.catalogRow} data-expanded={expanded} key={item.id}>
     <button type="button" className={styles.productIdentity} onClick={()=>editProduct(item)} aria-label={`Mở sản phẩm ${item.name.vi||item.name.en}`}>
      <figure>{item.photoUrl?<img src={item.photoUrl} alt="" loading="lazy"/>:<Package/>}</figure><span><small>{kindLabel(item.kind)} · {lineLabel(item.line)}</small><strong>{item.name.vi||item.name.en}</strong><em>{item.packSize||item.id}</em></span>
     </button>
     <button type="button" className={styles.saleStatus} data-on={item.available} onClick={()=>toggleAvailable(item)}><span aria-hidden="true"/>{item.available?"Đang bán":"Đang ẩn"}</button>
     <div className={styles.ledgerNumber} data-label="Giá bán"><strong>{priceRange(item)}</strong></div>
     <div className={styles.ledgerNumber} data-label="Hà Giang"><strong>{item.stockHaGiangTotal.toLocaleString("vi-VN")}</strong><small>trong kho</small></div>
     <div className={styles.ledgerNumber} data-label="Sóc Sơn"><strong>{item.stockSocSonTotal.toLocaleString("vi-VN")}</strong><small>trong kho</small></div>
     <button type="button" className={styles.variantToggle} aria-expanded={expanded} aria-controls={`variants-${item.id}`} onClick={()=>setExpandedProductId(expanded?"":item.id)}><span>{item.productVariants.length?`${item.productVariants.length} quy cách`:"Giá chung"}</span><ChevronDown/></button>
     {expanded&&<div className={styles.variantDisclosure} id={`variants-${item.id}`}>
      <div className={styles.variantDisclosureHead}><div><span>Chi tiết quy cách</span><strong>{item.name.vi||item.name.en}</strong></div><div><Link href={`/admin/operations/pricing?product=${encodeURIComponent(item.id)}`}><Calculator/>Tính giá</Link><button type="button" onClick={()=>editProduct(item)}>Mở hồ sơ</button></div></div>
      {item.productVariants.length?<div className={styles.variantLedger}>{item.productVariants.map((variant,index)=><div key={`${variant.weight}-${index}`}><strong>{variant.weight||"Chưa đặt tên"}</strong><span>{money(variant.price)}</span><span><small>Hà Giang</small>{numberValue(variant.stockHaGiang).toLocaleString("vi-VN")}</span><span><small>Sóc Sơn</small>{numberValue(variant.stockSocSon).toLocaleString("vi-VN")}</span></div>)}</div>:<p>Chưa có quy cách riêng. Giá và tồn kho đang được quản lý ở cấp sản phẩm.</p>}
     </div>}
    </article>})}
    {!loading&&!catalogRows.length&&<div className={styles.catalogEmpty}><Package/><strong>Không có sản phẩm phù hợp</strong><p>Thử xóa bộ lọc hoặc tìm bằng tên khác.</p><button type="button" onClick={clearCatalogFilters}>Xóa bộ lọc</button></div>}
   </div>
  </section>}
  {tab==="vendors"&&<section className={styles.panel}><header><div><p>Origin network</p><h2>Người và vùng cung ứng</h2></div><button onClick={()=>setVendor(blankVendor())}><Plus/>Thêm hồ sơ</button></header><div className={styles.vendorGrid}>{vendors.map(item=><article key={item.id}>{item.photo?<img src={item.photo} alt=""/>:<Sprout/>}<span>{item.region}</span><h3>{item.name}</h3><p>{item.crops}</p><button onClick={()=>setVendor({...item})}>Mở hồ sơ</button></article>)}</div></section>}
  {tab==="content"&&<section className={`${styles.panel} ${styles.contentPanel}`}><header><div><p>Editorial room</p><h2>Câu chuyện, phòng đọc và thư viện ảnh</h2></div></header><div className={styles.contentColumns}><section><header><div><span>Our story</span><h3>Bài viết về Nhà</h3></div><button onClick={()=>setArticle(blankArticle("wiki"))}><Plus/>Viết bài</button></header><div className={styles.recordList}>{stories.map(item=><button key={item.id} onClick={()=>setArticle({...item,source:"wiki"})}><span>{CATEGORIES.find(cat=>cat.id===item.category)?.label?.vi||item.category}</span><b>{item.title?.vi||item.title?.en}</b><small>{item.title?.en}</small></button>)}</div></section><section><header><div><span>Reading room</span><h3>Kiến thức về trà</h3></div><button onClick={()=>setArticle(blankArticle("library"))}><Plus/>Viết bài</button></header><div className={styles.recordList}>{reading.map(item=><button key={item.id} onClick={()=>setArticle({...item,source:"library"})}><span>{LIBRARY_CATEGORIES.find(cat=>cat.id===item.category)?.label?.vi||item.category}</span><b>{item.title?.vi||item.title?.en}</b><small>{item.title?.en}</small></button>)}</div></section></div><section className={styles.gallerySection}><header><div><span>Image library</span><h3>Khoảnh khắc của Nhà</h3></div><label className={styles.upload}><Upload/>Thêm ảnh<input type="file" accept="image/*" onChange={event=>addGalleryPhoto(event.target.files?.[0])}/></label></header><div className={styles.galleryGrid}>{gallery.map(item=><button key={item.id} onClick={()=>setGalleryItem({...item,caption:{vi:item.caption?.vi||"",en:item.caption?.en||""}})}><img src={item.url} alt=""/><span>{item.caption?.vi||item.caption?.en||"Thêm chú thích"}</span></button>)}</div></section></section>}
  {tab==="house"&&house&&<section className={`${styles.panel} ${styles.housePanel}`}><header><div><p>House record</p><h2>Người đại diện và bằng chứng nguồn gốc</h2></div><label className={styles.upload}><Upload/>Thêm ảnh trang chủ<input type="file" accept="image/*" onChange={event=>addHomePhoto(event.target.files?.[0])}/></label></header><div className={styles.photoRail}>{(home?.featured_photos||[]).map((url,index)=><figure key={url}><img src={url} alt={index===0?"Ảnh bìa trang chủ":`Ảnh trang chủ ${index+1}`}/><figcaption><span>{index===0?"Ảnh bìa":"Khối câu chuyện"}</span><label className={styles.photoReplace}><Upload/>Thay ảnh<input type="file" accept="image/*" onChange={event=>replaceHomePhoto(index,event.target.files?.[0])}/></label></figcaption></figure>)}</div><form onSubmit={saveHouse}>{field("Tên người đại diện",house.producerName,value=>setHouse({...house,producerName:value}))}{field("Vai trò · VI",house.roleVi,value=>setHouse({...house,roleVi:value}))}{field("Role · EN",house.roleEn,value=>setHouse({...house,roleEn:value}))}{field("Lời dẫn · VI",house.quoteVi,value=>setHouse({...house,quoteVi:value}),{textarea:true})}{field("Quote · EN",house.quoteEn,value=>setHouse({...house,quoteEn:value}),{textarea:true})}<label className={styles.upload}><Upload/>Tải ảnh người đại diện<input type="file" accept="image/*" onChange={event=>upload(event.target.files?.[0],"producer",url=>setHouse({...house,producerPhoto:url}))}/></label>{house.producerPhoto&&<img className={styles.producerPreview} src={house.producerPhoto} alt=""/>}{field("Số liệu · mỗi dòng: giá trị | EN | VI",house.stats,value=>setHouse({...house,stats:value}),{textarea:true})}<button className={styles.save} disabled={saving}><Save/>{saving?"Đang lưu…":"Lưu hồ sơ Nhà"}</button></form></section>}
  {product&&<div className={styles.overlay}><form className={`${styles.drawer} ${styles.productDrawer}`} onSubmit={saveProduct}>
   <header><div><p>Hồ sơ danh mục</p><h2>{product.id?product.name.vi||product.name.en||"Sửa sản phẩm":"Sản phẩm mới"}</h2></div><button type="button" onClick={()=>setProduct(null)} aria-label="Đóng hồ sơ sản phẩm">×</button></header>
   <section className={styles.editorSection}><header><div><span>Nhận diện</span><h3>Tên và phân loại</h3></div><label className={styles.availabilityField}><input type="checkbox" checked={product.available} onChange={event=>setProduct({...product,available:event.target.checked})}/><span>{product.available?"Đang bán":"Đang ẩn"}</span></label></header><div className={styles.formGrid}>{field("Tên tiếng Việt",product.name.vi,value=>setProduct({...product,name:{...product.name,vi:value}}))}{field("Tên tiếng Anh",product.name.en,value=>setProduct({...product,name:{...product.name,en:value}}))}<label>Loại<select value={product.kind} onChange={event=>setProduct({...product,kind:event.target.value})}><option value="tea">Trà</option><option value="goods">Nông sản</option></select></label><label>Dòng<select value={product.line} onChange={event=>setProduct({...product,line:event.target.value})}><option value="everyday">Dùng hằng ngày</option><option value="reserve">Dòng tuyển chọn</option><option value="sample">Mẫu thử</option></select></label><label>Nhà cung cấp<select value={product.vendorId||""} onChange={event=>setProduct({...product,vendorId:event.target.value})}><option value="">Nhà Hoàng Long</option>{vendors.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{field("Mẻ trà",product.batch,value=>setProduct({...product,batch:value}))}</div></section>
   <section className={styles.editorSection}><header><div><span>Thương mại</span><h3>Giá và tồn kho chung</h3></div>{product.id&&<Link className={styles.editorPriceLink} href={`/admin/operations/pricing?product=${encodeURIComponent(product.id)}`}><Calculator/>Tính giá</Link>}</header><div className={styles.formGrid}>{field("Giá bán",product.price,value=>setProduct({...product,price:value}),{type:"number",min:"0"})}{field("Quy cách chung",product.packSize,value=>setProduct({...product,packSize:value}))}{field("Tồn Hà Giang",product.stockHaGiang,value=>setProduct({...product,stockHaGiang:value}),{type:"number",min:"0"})}{field("Tồn Sóc Sơn",product.stockSocSon,value=>setProduct({...product,stockSocSon:value}),{type:"number",min:"0"})}</div></section>
   <section className={styles.editorSection}><header><div><span>Website</span><h3>Ảnh và mô tả</h3></div></header><div className={styles.formGrid}>{field("Ghi chú tiếng Việt",product.notes.vi,value=>setProduct({...product,notes:{...product.notes,vi:value}}),{textarea:true})}{field("Ghi chú tiếng Anh",product.notes.en,value=>setProduct({...product,notes:{...product.notes,en:value}}),{textarea:true})}<label className={styles.upload}><Upload/>Tải ảnh sản phẩm<input type="file" accept="image/*" onChange={event=>upload(event.target.files?.[0],"products",url=>setProduct({...product,photoUrl:url}))}/></label>{product.photoUrl&&<img className={styles.productPreview} src={product.photoUrl} alt=""/>}</div></section>
   <section className={`${styles.variants} ${styles.editorSection}`}><header><div><span>Quy cách riêng</span><h3>Giá và tồn theo khối lượng</h3></div><button type="button" onClick={()=>setProduct({...product,variants:[...(product.variants||[]),{weight:"",price:"",stockHaGiang:"",stockSocSon:""}]})}><Plus/>Thêm quy cách</button></header>{(product.variants||[]).length?(product.variants||[]).map((item,index)=><div className={styles.variantRow} key={`${item.originalWeight||"new"}-${index}`}>{field("Khối lượng",item.weight,value=>setProduct({...product,variants:product.variants.map((row,i)=>i===index?{...row,weight:value}:row)}),{disabled:!!item.originalWeight})}{field("Giá",item.price,value=>setProduct({...product,variants:product.variants.map((row,i)=>i===index?{...row,price:value}:row)}),{type:"number",min:"0"})}{field("Tồn HG",item.stockHaGiang,value=>setProduct({...product,variants:product.variants.map((row,i)=>i===index?{...row,stockHaGiang:value}:row)}),{type:"number",min:"0"})}{field("Tồn SS",item.stockSocSon,value=>setProduct({...product,variants:product.variants.map((row,i)=>i===index?{...row,stockSocSon:value}:row)}),{type:"number",min:"0"})}</div>):<p className={styles.variantEmpty}>Chưa có quy cách riêng. Sản phẩm đang dùng giá và tồn kho chung ở trên.</p>}</section>
   <div className={styles.editorFooter}><p>Quy cách cũ chỉ được cập nhật; hệ thống không tự xóa dữ liệu.</p><button className={styles.save} disabled={saving}><Save/>{saving?"Đang lưu…":"Lưu sản phẩm"}</button></div>
  </form></div>}
  {vendor&&<div className={styles.overlay}><form className={styles.drawer} onSubmit={saveVendor}><header><div><p>Origin record</p><h2>{vendor.id?"Sửa hồ sơ":"Hồ sơ mới"}</h2></div><button type="button" onClick={()=>setVendor(null)}>×</button></header><div className={styles.formGrid}>{field("Tên",vendor.name,value=>setVendor({...vendor,name:value}))}{field("Vùng",vendor.region,value=>setVendor({...vendor,region:value}))}{field("Nông sản",vendor.crops,value=>setVendor({...vendor,crops:value}))}{field("Điện thoại · nội bộ",vendor.phone,value=>setVendor({...vendor,phone:value}))}{field("Câu chuyện · VI",vendor.story.vi,value=>setVendor({...vendor,story:{...vendor.story,vi:value}}),{textarea:true})}{field("Story · EN",vendor.story.en,value=>setVendor({...vendor,story:{...vendor.story,en:value}}),{textarea:true})}{field("Ghi chú nội bộ",vendor.note,value=>setVendor({...vendor,note:value}),{textarea:true})}<label className={styles.upload}><Upload/>Tải ảnh hồ sơ<input type="file" accept="image/*" onChange={event=>upload(event.target.files?.[0],"vendors",url=>setVendor({...vendor,photo:url}))}/></label>{vendor.photo&&<img className={styles.productPreview} src={vendor.photo} alt=""/>}</div><button className={styles.save} disabled={saving}><Save/>{saving?"Đang lưu…":"Lưu hồ sơ"}</button></form></div>}
  {article&&<div className={styles.overlay}><form className={styles.drawer} onSubmit={saveArticle}><header><div><p>{article.source==="wiki"?"Our story":"Reading room"}</p><h2>{article.id?"Sửa bài viết":"Bài viết mới"}</h2></div><button type="button" onClick={()=>setArticle(null)}>×</button></header><div className={styles.formGrid}><label>Chuyên mục<select value={article.category} onChange={event=>setArticle({...article,category:event.target.value})}>{(article.source==="wiki"?CATEGORIES:LIBRARY_CATEGORIES).map(item=><option value={item.id} key={item.id}>{item.label.vi}</option>)}</select></label>{field("Tiêu đề · VI",article.title?.vi,value=>setArticle({...article,title:{...article.title,vi:value}}))}{field("Title · EN",article.title?.en,value=>setArticle({...article,title:{...article.title,en:value}}))}{field("Nội dung · VI",article.body?.vi,value=>setArticle({...article,body:{...article.body,vi:value}}),{textarea:true})}{field("Body · EN",article.body?.en,value=>setArticle({...article,body:{...article.body,en:value}}),{textarea:true})}</div><button className={styles.save} disabled={saving}><Save/>{saving?"Đang lưu…":"Lưu bài viết"}</button><p>Nội dung được lưu song ngữ; các bản ghi cũ không bị xóa khi chuyển sang phòng biên tập mới.</p></form></div>}
  {galleryItem&&<div className={styles.overlay}><form className={`${styles.drawer} ${styles.galleryDrawer}`} onSubmit={saveGallery}><header><div><p>Image record</p><h2>Chú thích ảnh</h2></div><button type="button" onClick={()=>setGalleryItem(null)}>×</button></header><img src={galleryItem.url} alt=""/><div className={styles.formGrid}>{field("Chú thích · VI",galleryItem.caption.vi,value=>setGalleryItem({...galleryItem,caption:{...galleryItem.caption,vi:value}}),{textarea:true})}{field("Caption · EN",galleryItem.caption.en,value=>setGalleryItem({...galleryItem,caption:{...galleryItem.caption,en:value}}),{textarea:true})}</div><button className={styles.save} disabled={saving}><Save/>{saving?"Đang lưu…":"Lưu chú thích"}</button><p>Ảnh được giữ nguyên; phòng biên tập mới chỉ cập nhật chú thích.</p></form></div>}
 </main>
}
