"use client";

import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Check,ImagePlus,Package,Plus,RefreshCw,Save,Sprout,Upload} from "lucide-react";
import {fromCatalogRow,fromVendorRow,toCatalogRow,toVendorRow} from "@/lib/mappers";
import {uploadImage} from "@/lib/supabase/storage";
import styles from "./HouseControl.module.css";

const blankProduct=()=>({id:"",line:"everyday",available:true,limited:false,name:{vi:"",en:""},notes:{vi:"",en:""},brew:{vi:"",en:""},packSize:"",photoUrl:"",photoPosition:"50% 50%",price:undefined,stockHaGiang:undefined,stockSocSon:undefined,batch:"",soldCount:0,flavors:{},kind:"tea",vendorId:""});
const blankVendor=()=>({id:"",name:"",region:"",photo:"",crops:"",story:{vi:"",en:""},phone:"",note:"",active:true,sortOrder:0});
const slug=value=>`${value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,36)}-${Date.now().toString(36)}`;
const statsToText=stats=>(stats||[]).map(item=>`${item.value} | ${item.label?.en||""} | ${item.label?.vi||""}`).join("\n");
const textToStats=text=>text.split("\n").map(line=>{const [value,en,vi]=line.split("|").map(part=>(part||"").trim());return value?{value,label:{en,vi:vi||en}}:null}).filter(Boolean);

export default function HouseControl({supabase,email,onLogout}){
 const [tab,setTab]=useState("catalog"),[products,setProducts]=useState([]),[vendors,setVendors]=useState([]),[home,setHome]=useState(null),[product,setProduct]=useState(null),[vendor,setVendor]=useState(null),[house,setHouse]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[saved,setSaved]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const [p,v,h]=await Promise.all([supabase.from("catalog_products").select("*"),supabase.from("vendors").select("*").order("sort_order"),supabase.from("settings_home").select("*").eq("id",1).maybeSingle()]);if(p.error||v.error||h.error)setError("Không tải được toàn bộ dữ liệu của Nhà.");if(!p.error)setProducts((p.data||[]).map(fromCatalogRow));if(!v.error)setVendors((v.data||[]).map(fromVendorRow));if(!h.error){setHome(h.data);setHouse({producerName:h.data?.producer_name||"",producerPhoto:h.data?.producer_photo||"",roleVi:h.data?.producer_role?.vi||"",roleEn:h.data?.producer_role?.en||"",quoteVi:h.data?.producer_quote?.vi||"",quoteEn:h.data?.producer_quote?.en||"",stats:statsToText(h.data?.origin_stats)})}setLoading(false)},[supabase]);
 useEffect(()=>{load()},[load]);
 const flash=message=>{setSaved(message);setTimeout(()=>setSaved(""),1800)};
 const saveProduct=async event=>{event.preventDefault();if(!product?.name?.vi?.trim()&&!product?.name?.en?.trim())return;setSaving(true);setError("");const next={...product,id:product.id||slug(product.name.en||product.name.vi),price:product.price===""?undefined:Number(product.price),stockHaGiang:product.stockHaGiang===""?undefined:Number(product.stockHaGiang),stockSocSon:product.stockSocSon===""?undefined:Number(product.stockSocSon)};const {error:saveError}=await supabase.from("catalog_products").upsert(toCatalogRow(next));setSaving(false);if(saveError){setError("Chưa lưu được sản phẩm.");return}setProduct(null);flash("Đã lưu sản phẩm");load()};
 const toggleAvailable=async item=>{const available=!item.available;const {error:updateError}=await supabase.from("catalog_products").update({available}).eq("id",item.id);if(updateError){setError("Chưa cập nhật được tình trạng bán.");return}setProducts(current=>current.map(row=>row.id===item.id?{...row,available}:row))};
 const saveVendor=async event=>{event.preventDefault();if(!vendor?.name?.trim())return;setSaving(true);const next={...vendor,id:vendor.id||slug(vendor.name),sortOrder:vendor.sortOrder??vendors.length};const {error:saveError}=await supabase.from("vendors").upsert(toVendorRow(next));setSaving(false);if(saveError){setError("Chưa lưu được nhà cung cấp.");return}setVendor(null);flash("Đã lưu hồ sơ vùng");load()};
 const saveHouse=async event=>{event.preventDefault();setSaving(true);const row={producer_name:house.producerName.trim(),producer_photo:house.producerPhoto.trim(),producer_role:{vi:house.roleVi.trim(),en:house.roleEn.trim()},producer_quote:{vi:house.quoteVi.trim(),en:house.quoteEn.trim()},origin_stats:textToStats(house.stats)};const {error:saveError}=await supabase.from("settings_home").update(row).eq("id",1);setSaving(false);if(saveError){setError("Chưa lưu được hồ sơ Nhà.");return}flash("Đã lưu hồ sơ Nhà");load()};
 const upload=async(file,folder,apply)=>{if(!file)return;setSaving(true);setError("");try{apply(await uploadImage(supabase,file,folder))}catch{setError("Tải ảnh thất bại.")}finally{setSaving(false)}};
 const addHomePhoto=async file=>{if(!file)return;setSaving(true);try{const url=await uploadImage(supabase,file,"home");const photos=[...(home?.featured_photos||[]),url];const {error:updateError}=await supabase.from("settings_home").update({featured_photos:photos,featured_photo:photos[0]}).eq("id",1);if(updateError)throw updateError;flash("Đã thêm ảnh trang chủ");load()}catch{setError("Tải ảnh trang chủ thất bại.")}finally{setSaving(false)}};
 const field=(label,value,onChange,props={})=>{const {textarea,...fieldProps}=props;return <label>{label}{textarea?<textarea value={value||""} onChange={event=>onChange(event.target.value)} {...fieldProps}/>:<input value={value??""} onChange={event=>onChange(event.target.value)} {...fieldProps}/>}</label>};
 return <main className={styles.page}>
  <header className={styles.top}><div><Link href="/admin"><ArrowLeft/>Điều phối</Link><span>House control</span></div><div><span><b>{email}</b><small>Không gian quản trị</small></span><button onClick={load} disabled={loading}><RefreshCw/></button><button onClick={onLogout}>Đăng xuất</button></div></header>
  <section className={styles.heading}><p>Những gì khách nhìn thấy</p><h1>Nhà, danh mục và vùng trà.</h1><span>Mọi thay đổi ở đây đi thẳng vào website đang vận hành.</span></section>
  <nav className={styles.tabs}>{[["catalog","Danh mục",Package],["vendors","Vùng & người",Sprout],["house","Hồ sơ Nhà",ImagePlus]].map(([id,label,Icon])=><button key={id} className={tab===id?styles.active:""} onClick={()=>setTab(id)}><Icon/>{label}</button>)}</nav>
  {error&&<p className={styles.error} role="alert">{error}</p>}{saved&&<p className={styles.saved}><Check/>{saved}</p>}
  {tab==="catalog"&&<section className={styles.panel}><header><div><p>Live catalogue</p><h2>Sản phẩm đang quản lý</h2></div><button onClick={()=>setProduct(blankProduct())}><Plus/>Thêm sản phẩm</button></header><div className={styles.productList}>{products.map(item=><article key={item.id}><figure>{item.photoUrl?<img src={item.photoUrl} alt=""/>:<Package/>}</figure><div><span>{item.kind} · {item.line}</span><h3>{item.name.vi||item.name.en}</h3><p>{item.packSize||"Chưa có quy cách"} · {item.price?Number(item.price).toLocaleString("vi-VN")+"đ":"Chưa có giá"}</p></div><button data-on={item.available} onClick={()=>toggleAvailable(item)}>{item.available?"Đang bán":"Đang ẩn"}</button><button onClick={()=>setProduct({...item})}>Sửa</button></article>)}</div></section>}
  {tab==="vendors"&&<section className={styles.panel}><header><div><p>Origin network</p><h2>Người và vùng cung ứng</h2></div><button onClick={()=>setVendor(blankVendor())}><Plus/>Thêm hồ sơ</button></header><div className={styles.vendorGrid}>{vendors.map(item=><article key={item.id}>{item.photo?<img src={item.photo} alt=""/>:<Sprout/>}<span>{item.region}</span><h3>{item.name}</h3><p>{item.crops}</p><button onClick={()=>setVendor({...item})}>Mở hồ sơ</button></article>)}</div></section>}
  {tab==="house"&&house&&<section className={`${styles.panel} ${styles.housePanel}`}><header><div><p>House record</p><h2>Người đại diện và bằng chứng nguồn gốc</h2></div><label className={styles.upload}><Upload/>Thêm ảnh trang chủ<input type="file" accept="image/*" onChange={event=>addHomePhoto(event.target.files?.[0])}/></label></header><div className={styles.photoRail}>{(home?.featured_photos||[]).map((url,index)=><img key={url} src={url} alt={`Ảnh trang chủ ${index+1}`}/>)}</div><form onSubmit={saveHouse}>{field("Tên người đại diện",house.producerName,value=>setHouse({...house,producerName:value}))}{field("Vai trò · VI",house.roleVi,value=>setHouse({...house,roleVi:value}))}{field("Role · EN",house.roleEn,value=>setHouse({...house,roleEn:value}))}{field("Lời dẫn · VI",house.quoteVi,value=>setHouse({...house,quoteVi:value}),{textarea:true})}{field("Quote · EN",house.quoteEn,value=>setHouse({...house,quoteEn:value}),{textarea:true})}<label className={styles.upload}><Upload/>Tải ảnh người đại diện<input type="file" accept="image/*" onChange={event=>upload(event.target.files?.[0],"producer",url=>setHouse({...house,producerPhoto:url}))}/></label>{house.producerPhoto&&<img className={styles.producerPreview} src={house.producerPhoto} alt=""/>}{field("Số liệu · mỗi dòng: giá trị | EN | VI",house.stats,value=>setHouse({...house,stats:value}),{textarea:true})}<button className={styles.save} disabled={saving}><Save/>{saving?"Đang lưu…":"Lưu hồ sơ Nhà"}</button></form></section>}
  {product&&<div className={styles.overlay}><form className={styles.drawer} onSubmit={saveProduct}><header><div><p>Catalogue record</p><h2>{product.id?"Sửa sản phẩm":"Sản phẩm mới"}</h2></div><button type="button" onClick={()=>setProduct(null)}>×</button></header><div className={styles.formGrid}>{field("Tên · VI",product.name.vi,value=>setProduct({...product,name:{...product.name,vi:value}}))}{field("Name · EN",product.name.en,value=>setProduct({...product,name:{...product.name,en:value}}))}<label>Loại<select value={product.kind} onChange={event=>setProduct({...product,kind:event.target.value})}><option value="tea">Trà</option><option value="goods">Nông sản</option></select></label><label>Dòng<select value={product.line} onChange={event=>setProduct({...product,line:event.target.value})}><option value="everyday">Everyday</option><option value="reserve">Reserve</option><option value="sample">Sample</option></select></label>{field("Giá",product.price,value=>setProduct({...product,price:value}),{type:"number"})}{field("Quy cách",product.packSize,value=>setProduct({...product,packSize:value}))}{field("Tồn Hà Giang",product.stockHaGiang,value=>setProduct({...product,stockHaGiang:value}),{type:"number"})}{field("Tồn Sóc Sơn",product.stockSocSon,value=>setProduct({...product,stockSocSon:value}),{type:"number"})}{field("Mẻ trà",product.batch,value=>setProduct({...product,batch:value}))}<label>Nhà cung cấp<select value={product.vendorId||""} onChange={event=>setProduct({...product,vendorId:event.target.value})}><option value="">Nhà Hoàng Long</option>{vendors.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{field("Ghi chú · VI",product.notes.vi,value=>setProduct({...product,notes:{...product.notes,vi:value}}),{textarea:true})}{field("Notes · EN",product.notes.en,value=>setProduct({...product,notes:{...product.notes,en:value}}),{textarea:true})}<label className={styles.upload}><Upload/>Tải ảnh sản phẩm<input type="file" accept="image/*" onChange={event=>upload(event.target.files?.[0],"products",url=>setProduct({...product,photoUrl:url}))}/></label>{product.photoUrl&&<img className={styles.productPreview} src={product.photoUrl} alt=""/>}</div><button className={styles.save} disabled={saving}><Save/>{saving?"Đang lưu…":"Lưu sản phẩm"}</button><p>Biến thể quy cách cũ vẫn được giữ nguyên. Chỉnh biến thể chi tiết tại hệ thống cũ trong thời gian chuyển đổi.</p></form></div>}
  {vendor&&<div className={styles.overlay}><form className={styles.drawer} onSubmit={saveVendor}><header><div><p>Origin record</p><h2>{vendor.id?"Sửa hồ sơ":"Hồ sơ mới"}</h2></div><button type="button" onClick={()=>setVendor(null)}>×</button></header><div className={styles.formGrid}>{field("Tên",vendor.name,value=>setVendor({...vendor,name:value}))}{field("Vùng",vendor.region,value=>setVendor({...vendor,region:value}))}{field("Nông sản",vendor.crops,value=>setVendor({...vendor,crops:value}))}{field("Điện thoại · nội bộ",vendor.phone,value=>setVendor({...vendor,phone:value}))}{field("Câu chuyện · VI",vendor.story.vi,value=>setVendor({...vendor,story:{...vendor.story,vi:value}}),{textarea:true})}{field("Story · EN",vendor.story.en,value=>setVendor({...vendor,story:{...vendor.story,en:value}}),{textarea:true})}{field("Ghi chú nội bộ",vendor.note,value=>setVendor({...vendor,note:value}),{textarea:true})}<label className={styles.upload}><Upload/>Tải ảnh hồ sơ<input type="file" accept="image/*" onChange={event=>upload(event.target.files?.[0],"vendors",url=>setVendor({...vendor,photo:url}))}/></label>{vendor.photo&&<img className={styles.productPreview} src={vendor.photo} alt=""/>}</div><button className={styles.save} disabled={saving}><Save/>{saving?"Đang lưu…":"Lưu hồ sơ"}</button></form></div>}
 </main>
}
