"use client";

import {useCallback,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {AlertTriangle,ArrowLeft,CheckCircle2,ChevronRight,FileUp,HelpCircle,PackageCheck,ShieldCheck} from 'lucide-react';
import {createClient} from '@/lib/supabase/client';
import {PROCEDURE_STAGES,procedureProgress,isFinished,preDispatchProblems} from '@/lib/procedure-templates';
import styles from './ProcedureDesk.module.css';

const label={not_started:'Chưa làm',in_progress:'Đang làm',blocked:'Đang vướng',done:'Đã làm · chờ kiểm',verified:'Đã kiểm',not_required:'Không cần',missing:'Thiếu',draft:'Bản nháp',ready:'Sẵn sàng',checked:'Đã đối chiếu',issue_found:'Có vấn đề',open:'Đang mở',resolved:'Chờ xác minh',overridden:'Đã cho phép ngoại lệ'};
const date=value=>value?new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—';
const person=(profiles,id)=>profiles.find(row=>row.user_id===id)?.display_name||'Chưa giao';
const money=value=>value===null||value===undefined?'—':`${new Intl.NumberFormat('vi-VN').format(value)} ₫`;

export default function ProcedureDesk({runId}) {
  const router=useRouter();
  const supabase=useMemo(()=>createClient(),[]);
  const [auth,setAuth]=useState(null),[data,setData]=useState(null),[list,setList]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[query,setQuery]=useState('');
  const [activeItem,setActiveItem]=useState(''),[note,setNote]=useState(''),[blockForm,setBlockForm]=useState(false),[problem,setProblem]=useState(''),[correction,setCorrection]=useState(''),[stopWork,setStopWork]=useState(false),[budget,setBudget]=useState(''),[blockDue,setBlockDue]=useState(''),[resolution,setResolution]=useState(''),[actualSpend,setActualSpend]=useState(''),[approveAmount,setApproveAmount]=useState(''),[resolver,setResolver]=useState(''),[helpContact,setHelpContact]=useState(''),[backupContact,setBackupContact]=useState('');
  const [waiverReason,setWaiverReason]=useState('');
  const request=useCallback(async(path,options={})=>{
    const {data:{session}}=await supabase.auth.getSession();
    if (!session?.access_token) throw new Error('Phiên đăng nhập đã hết hạn.');
    const response=await fetch(path,{...options,headers:{Authorization:`Bearer ${session.access_token}`,...options.headers}});
    const body=await response.json().catch(()=>({}));
    if (!response.ok) throw new Error(({second_person_required:'Cần người khác kiểm xác nhận.',evidence_required:'Cần tải bằng chứng trước khi kiểm.',resolution_evidence_required:'Cần ảnh / tệp chứng minh đã khắc phục.',document_file_required:'Tải chứng từ trước khi đánh dấu đã kiểm.',pre_dispatch_incomplete:'Chưa đủ bước kiểm trước khi xe rời kho.',blocker_open:'Vẫn còn vấn đề chưa được xác minh.',budget_approval_required:'Khoản chi cần quản lý phê duyệt trước.',waiver_reason_required:'Ghi rõ lý do bỏ qua (ít nhất 10 ký tự).',stop_blocker_open:'Đơn còn STOP chưa xử lý; không thể bỏ qua quy trình.',run_waived:'Quy trình đã được bỏ qua; bật lại trước khi tiếp tục.'})[body.error]||body.error||'Chưa lưu được.');
    return body;
  },[supabase]);
  const reload=useCallback(async()=>{
    try {const result=await request(runId?`/api/staff/procedures/${encodeURIComponent(runId)}`:`/api/staff/procedures?q=${encodeURIComponent(query)}`);setData(runId?result:null);setList(result.runs||[]);setError('');}
    catch(e){setError(e.message)}finally{setLoading(false)}
  },[request,runId,query]);
  useEffect(()=>{let live=true;(async()=>{
    const {data:{user}}=await supabase.auth.getUser();
    if (!user){router.replace('/admin/login');return}
    const {data:staff}=await supabase.from('staff_roles').select('role').eq('user_id',user.id).maybeSingle();
    if (!live)return;
    if (!staff){setError('Tài khoản chưa có quyền nhân viên.');setLoading(false);return}
    setAuth({id:user.id,role:staff.role});
  })();return()=>{live=false}},[router,supabase]);
  useEffect(()=>{if(auth)reload()},[auth,reload]);
  const manager=auth&&['admin','manager'].includes(auth.role);
  const save=async(body)=>{setSaving(true);setError('');setNotice('');try{await request(`/api/staff/procedures/${encodeURIComponent(runId)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await reload();setNotice('Đã lưu vào lịch sử quy trình.');setBlockForm(false);setProblem('');setCorrection('');setResolution('');}catch(e){setError(e.message)}finally{setSaving(false)}};
  const upload=async(itemId,file,blockerId=null)=>{if(!file)return;setSaving(true);setError('');try{
    const url=`/api/staff/procedures/${encodeURIComponent(runId)}/evidence`;
    const details={itemId,blockerId,fileName:file.name,contentType:file.type,size:file.size};
    const prepared=await request(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...details,phase:'prepare'})});
    const {error:uploadError}=await supabase.storage.from('procedure-evidence').uploadToSignedUrl(prepared.path,prepared.token,file,{contentType:file.type});
    if(uploadError)throw new Error('Chưa tải được tệp lên kho bằng chứng.');
    await request(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...details,phase:'finalize',path:prepared.path,evidenceId:prepared.evidenceId})});
    await reload();setNotice('Đã lưu bằng chứng trong hồ sơ đơn.');
  }catch(e){setError(e.message)}finally{setSaving(false)}};
  const viewFile=async(id)=>{const viewer=window.open('about:blank','_blank');if(viewer)viewer.opener=null;try{const result=await request(`/api/staff/procedures/${encodeURIComponent(runId)}/evidence?evidenceId=${id}`);if(viewer)viewer.location.href=result.url;else window.location.href=result.url}catch(e){viewer?.close();setError(e.message)}};
  if (loading) return <main className={styles.page}><p>Đang mở quy trình…</p></main>;
  if (!runId) return <main className={styles.page}><header className={styles.pageHead}><div><small>HOÀNG LONG · B2B OPERATIONS</small><h1>Quy trình đơn B2B</h1><p>Mỗi đơn một hồ sơ: việc đang chờ, vấn đề, bằng chứng và người chịu trách nhiệm.</p></div><Link href="/admin/orders">Mở Order book <ChevronRight size={16}/></Link></header><form className={styles.search} onSubmit={event=>{event.preventDefault();setQuery(search.trim())}}><input aria-label="Tìm khách, mã đơn, mã vận đơn hoặc Run" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Tìm khách, mã đơn, mã vận đơn hoặc năm…"/><button>Tìm</button></form>{error&&<p className={styles.error} role="alert">{error}</p>}{list.length?<div className={styles.runList}>{list.map(run=><Link key={run.id} href={`/admin/procedures/${run.id}`} className={styles.runCard}><span><small>{run.order_id} · {run.template_key==='export_b2b'?'Xuất khẩu':'Trong nước'} · {new Date(run.created_at).getFullYear()}</small><b>{run.order?.customer_name||'Khách hàng'}</b><em>{run.next_action||'Xem việc kế tiếp'}</em></span><span className={styles.runProgress}><strong>{run.progress?.percent||0}%</strong><small>{run.stop?'STOP':run.status==='waived'?'Đã bỏ qua':run.blockers?`${run.blockers} vướng`:run.status==='completed'?'Đã khép':'Đang làm'}</small></span><ChevronRight/></Link>)}</div>:<div className={styles.empty}><PackageCheck/><h2>Không có Procedure Run phù hợp.</h2><p>Mở một đơn sỉ đã xác nhận trong Order book để bắt đầu.</p></div>}</main>;
  if (!data) return <main className={styles.page}><Link href="/admin/procedures">← Danh sách</Link><p role="alert">{error||'Không mở được quy trình.'}</p></main>;

  const {run,order,items,blockers,evidence,events,profiles}=data;
  const progress=procedureProgress(items),preflight=preDispatchProblems(items,blockers);
  const current=items.find(item=>item.required&&!isFinished(item));
  const openBlockers=blockers.filter(row=>['open','resolved'].includes(row.status));
  const canWork=item=>run.status==='active'&&(manager||item.assigned_to===auth.id||(!item.assigned_to&&run.assigned_to===auth.id));
  return <main className={styles.page}>
    <Link className={styles.back} href="/admin/procedures"><ArrowLeft size={17}/> Tất cả quy trình</Link>
    <header className={styles.pageHead}><div><small>{run.template_key==='export_b2b'?'EXPORT B2B':'DOMESTIC B2B'} · {order?.id}</small><h1>{order?.customer_name}</h1><p>{order?.contact} · {order?.address||'Chưa có địa chỉ giao'} · {order?.lines?.map(line=>`${line.name?.vi||line.name?.en||'Trà'} ${line.qty} ${line.unit}`).join(', ')}</p></div><div className={styles.heroProgress}><strong>{progress.percent}%</strong><span>{progress.done}/{progress.total} việc</span></div></header>
    <div className={styles.track} role="progressbar" aria-valuenow={progress.percent} aria-valuemin="0" aria-valuemax="100" aria-label="Tiến độ quy trình"><span style={{width:`${progress.percent}%`}}/></div>
    {preflight.stop.length>0&&<div className={styles.stopBanner} role="alert"><AlertTriangle/><div><strong>{run.status==='waived'?'STOP đã được quản lý cho phép ngoại lệ — cần theo dõi xử lý':'STOP — KHÔNG XẾP / XUẤT HÀNG'}</strong><p>{preflight.stop[0].problem}</p></div></div>}
    {run.status==='waived'&&<div className={styles.waiverBanner} role="status"><strong>Đã bỏ qua Procedure Run cho riêng đơn này</strong><p>Lý do: {run.waiver_reason}</p><small>{date(run.waived_at)} · {person(profiles,run.waived_by)}</small>{manager&&<button disabled={saving} onClick={()=>save({action:'resume'})}>Bật lại quy trình</button>}</div>}
    {manager&&run.status==='active'&&<details className={styles.waiverControl}><summary>Bỏ qua quy trình cho riêng đơn này</summary><p>Dùng cho đơn nhỏ không cần checklist B2B. Quyết định và lý do được lưu trong lịch sử. Nếu đang có STOP, dùng thao tác “Force off · Chuyển Đang giao” tại Order book.</p><label>Lý do bỏ qua<textarea value={waiverReason} maxLength={1000} onChange={event=>setWaiverReason(event.target.value)} placeholder="Ví dụ: đơn 5 kg gửi bưu điện, đã kiểm hàng và mã vận đơn trong Order book"/></label><button disabled={saving||waiverReason.trim().length<10||preflight.stop.length>0} onClick={()=>save({action:'waive',reason:waiverReason})}>Xác nhận bỏ qua cho đơn này</button></details>}
    <section className={styles.nextCard}><div><small>VIỆC CẦN LÀM TIẾP</small><h2>{run.status==='waived'?'Theo dõi đơn trong Order book':openBlockers[0]?`Gỡ vướng: ${openBlockers[0].problem}`:run.next_action||current?.title||'Kiểm tra và khép đơn'}</h2><p>Phụ trách: {person(profiles,run.assigned_to)} · Hạn: {date(run.due_at)}{run.next_contact_at?` · Liên hệ lại: ${date(run.next_contact_at)}`:''}</p></div><HelpCircle/></section>
    {error&&<p className={styles.error} role="alert">{error}</p>}{notice&&<p className={styles.notice} role="status">{notice}</p>}
    {manager&&run.status==='active'&&<details className={styles.settings}><summary>Người phụ trách & mốc thời gian</summary><div className={styles.formGrid}><label>Phụ trách chung<select value={run.assigned_to||''} onChange={event=>save({action:'run',assignedTo:event.target.value||null})}><option value="">Chưa giao</option>{profiles.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name}</option>)}</select></label>{[['due_at','dueAt','Hạn quy trình'],['loading_at','loadingAt','Ngày xếp hàng'],['delivery_due_at','deliveryDueAt','Hạn giao hàng'],['next_contact_at','nextContactAt','Liên hệ đặt lại']].map(([column,input,title])=><label key={column}>{title}<input type="datetime-local" defaultValue={run[column]?.slice(0,16)||''} onBlur={event=>{const value=event.target.value?new Date(event.target.value).toISOString():null;if(value!==run[column])save({action:'run',[input]:value})}}/></label>)}<label>Việc bán hàng tiếp theo<input defaultValue={run.reorder_action||''} placeholder="Ví dụ: hỏi lịch đặt lại 30 kg trà" onBlur={event=>{if(event.target.value!==run.reorder_action)save({action:'run',reorderAction:event.target.value})}}/></label></div></details>}
    <div className={styles.stages}>{PROCEDURE_STAGES.map(([key,title],index)=>{
      const stageItems=items.filter(item=>item.stage_key===key),done=stageItems.filter(isFinished).length;
      return <details key={key} className={styles.stage} defaultOpen={stageItems.some(item=>item.id===current?.id)}>
        <summary><span className={styles.stageNumber}>{String(index+1).padStart(2,'0')}</span><span><b>{title}</b><small>{done}/{stageItems.length} xong</small></span>{stageItems.some(item=>item.status==='blocked')?<AlertTriangle className={styles.warn}/>:done===stageItems.length?<CheckCircle2 className={styles.good}/>:<ChevronRight/>}</summary>
        <div className={styles.itemList}>{stageItems.map(item=>{
          const files=evidence.filter(row=>row.item_id===item.id),issues=blockers.filter(row=>row.item_id===item.id),editable=canWork(item)&&run.status==='active';
          const open=activeItem===item.id;
          return <article key={item.id} className={styles.item} data-status={item.status}>
            <button className={styles.itemToggle} onClick={()=>{setActiveItem(open?'':item.id);setNote(item.worker_notes||'');setBlockForm(false);setProblem('');setResolution('');setResolver(item.assigned_to||run.assigned_to||'');setHelpContact(item.escalation_contact||'');setBackupContact(item.secondary_contact||'')}}><span className={styles.itemMark}>{isFinished(item)?'✓':item.status==='blocked'?'!':'○'}</span><span><b>{item.title}</b><small>{label[item.status]}{item.document_state?` · Chứng từ: ${label[item.document_state]}`:''} · {person(profiles,item.assigned_to||run.assigned_to)}</small></span><ChevronRight/></button>
            {open&&<div className={styles.itemBody}>
              <p className={styles.guidance}>Làm đúng: {item.guidance}</p>
              <p className={styles.proof}>Bằng chứng: {item.evidence_required?'Cần tệp/ảnh trước khi người khác xác minh.':'Ghi chú đủ rõ; đính kèm ảnh nếu hữu ích.'}</p>
              <p className={styles.contact}>Khi vướng: {item.escalation_contact||'Báo quản lý'}{item.secondary_contact?` · ${item.secondary_contact}`:''}</p>
              {manager&&run.status==='active'&&<div className={styles.assign}><label>Giao cho<select value={item.assigned_to||''} onChange={event=>save({action:'assign_item',itemId:item.id,assignedTo:event.target.value||null})}><option value="">Người phụ trách Run</option>{profiles.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name}</option>)}</select></label><label>Liên hệ khi cần giúp<input defaultValue={item.escalation_contact} onBlur={event=>{if(event.target.value!==item.escalation_contact)save({action:'assign_item',itemId:item.id,assignedTo:item.assigned_to,escalationContact:event.target.value})}}/></label><label>Liên hệ dự phòng<input defaultValue={item.secondary_contact} onBlur={event=>{if(event.target.value!==item.secondary_contact)save({action:'assign_item',itemId:item.id,assignedTo:item.assigned_to,secondaryContact:event.target.value})}}/></label></div>}
              <label className={styles.fullLabel}>Ghi chú người làm<textarea value={note} onChange={event=>setNote(event.target.value)} disabled={!editable} placeholder="Số lượng thực tế, lô trà, giờ xếp, người nhận…"/></label>
              {editable&&item.document_state&&<label>Trạng thái chứng từ<select value={item.document_state} onChange={event=>{const choice=event.target.value;if(['missing','draft','ready'].includes(choice))save({action:'item',itemId:item.id,status:choice==='missing'?'not_started':'in_progress',documentState:choice,notes:note})}}><option value="missing">Thiếu</option><option value="draft">Bản nháp</option><option value="ready">Sẵn sàng</option><option value="checked" disabled>Đã đối chiếu</option><option value="verified" disabled>Đã xác minh</option><option value="issue_found" disabled>Có vấn đề</option><option value="not_required" disabled>Không cần</option></select></label>}
              {editable&&<div className={styles.actions}><button disabled={saving} onClick={()=>save({action:'item',itemId:item.id,status:'in_progress',notes:note})}>Đang làm / lưu ghi chú</button><button disabled={saving} className={styles.primary} onClick={()=>save({action:'item',itemId:item.id,status:'done',notes:note})}>Tôi đã làm xong</button>{manager&&item.status==='done'&&<button disabled={saving} onClick={()=>save({action:'item',itemId:item.id,status:'verified',notes:note})}><ShieldCheck size={16}/> Xác minh</button>}{manager&&<button disabled={saving} onClick={()=>{const reason=window.prompt('Vì sao bước này không cần cho đơn này?');if(reason?.trim())save({action:'item',itemId:item.id,status:'not_required',notes:reason})}}>Không cần</button>}</div>}
              {item.completed_at&&<p className={styles.audit}>Hoàn thành {date(item.completed_at)} · {person(profiles,item.completed_by)}{item.verified_at?` · Kiểm ${date(item.verified_at)} bởi ${person(profiles,item.verified_by)}`:''}</p>}
              <div className={styles.files}><b>Ảnh & tài liệu ({files.length})</b>{files.map(file=>file.status==='ready'?<button key={file.id} onClick={()=>viewFile(file.id)}>{file.file_name} · {date(file.created_at)} ↗</button>:<span key={file.id} className={styles.pending}>{file.file_name} · đang chờ tải xong</span>)}{editable&&<label className={styles.upload}><FileUp size={17}/> Tải bằng chứng<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,application/pdf" disabled={saving} onChange={event=>{upload(item.id,event.target.files?.[0]);event.target.value=''}}/></label>}</div>
              <div className={styles.issueArea}>{issues.map(issue=><div key={issue.id} className={styles.issue}><strong>{issue.stop_work?'STOP · ':''}{issue.problem}</strong><small>{label[issue.status]} · Phụ trách: {person(profiles,issue.responsible_to)} · Hạn {date(issue.due_at)}</small><p>Khắc phục: {issue.corrective_action||'Cần xác định cách xử lý'}</p><p>Ngân sách: dự kiến {money(issue.estimated_budget)} · duyệt {money(issue.approved_budget)}{issue.approved_by?` bởi ${person(profiles,issue.approved_by)}`:''} · thực chi {money(issue.actual_spend)}</p><p>Liên hệ: {issue.escalation_contact||'Quản lý'}</p>{issue.resolution_notes&&<p>Đã xử lý: {issue.resolution_notes} · {person(profiles,issue.resolved_by)} lúc {date(issue.resolved_at)}{issue.verified_by?` · xác minh bởi ${person(profiles,issue.verified_by)} lúc ${date(issue.verified_at)}`:''}</p>}{issue.status==='open'&&run.status==='active'&&(editable||issue.responsible_to===auth.id)&&<><label>Cách đã xử lý<textarea value={resolution} onChange={event=>setResolution(event.target.value)}/></label><div className={styles.formGrid}><label>Thực chi (VND)<input inputMode="numeric" value={actualSpend} onChange={event=>setActualSpend(event.target.value)}/></label><button disabled={saving||!resolution.trim()} onClick={()=>save({action:'blocker',blockerId:issue.id,operation:'resolve',resolutionNotes:resolution,actualSpend})}>Đã xử lý · chờ kiểm</button></div></>}{issue.status==='resolved'&&manager&&run.status==='active'&&<div className={styles.actions}><button disabled={saving} onClick={()=>save({action:'blocker',blockerId:issue.id,operation:'verify'})}>Xác minh đã hết vướng</button><button disabled={saving} onClick={()=>{const reason=window.prompt('Lý do cho phép ngoại lệ?');if(reason?.trim())save({action:'blocker',blockerId:issue.id,operation:'override',reason})}}>Cho phép ngoại lệ</button></div>}{manager&&run.status==='active'&&<div className={styles.formGrid}><label>Duyệt tối đa (VND)<input inputMode="numeric" value={approveAmount} onChange={event=>setApproveAmount(event.target.value)}/></label><button disabled={saving||!approveAmount} onClick={()=>save({action:'blocker',blockerId:issue.id,operation:'budget',approvedBudget:approveAmount})}>Duyệt ngân sách</button><label>Thực chi sau xử lý (VND)<input inputMode="numeric" value={actualSpend} onChange={event=>setActualSpend(event.target.value)}/></label><button disabled={saving||!actualSpend} onClick={()=>save({action:'blocker',blockerId:issue.id,operation:'spend',actualSpend})}>Cập nhật thực chi</button></div>}{issue.status!=='verified'&&issue.status!=='overridden'&&run.status==='active'&&(editable||issue.responsible_to===auth.id)&&<label className={styles.upload}><FileUp size={17}/> Tải bằng chứng xử lý<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,application/pdf" disabled={saving} onChange={event=>{upload(item.id,event.target.files?.[0],issue.id);event.target.value=''}}/></label>}</div>)}
              {editable&&!blockForm&&<button className={styles.help} onClick={()=>setBlockForm(true)}><HelpCircle size={17}/> Tôi cần giúp / Báo vướng</button>}
              {editable&&blockForm&&<div className={styles.blockForm}><h4>Báo vướng cho {item.escalation_contact||'quản lý'}</h4><label>Chuyện gì xảy ra?<textarea value={problem} onChange={event=>setProblem(event.target.value)} required/></label><label>Cần giải quyết thế nào?<textarea value={correction} onChange={event=>setCorrection(event.target.value)}/></label><div className={styles.formGrid}><label>Ai xử lý?<select value={resolver} onChange={event=>setResolver(event.target.value)}><option value="">Người phụ trách Run</option>{profiles.filter(p=>p.active).map(p=><option key={p.user_id} value={p.user_id}>{p.display_name}</option>)}</select></label><label>Liên hệ hỗ trợ (tên / số / cách liên lạc)<input value={helpContact} onChange={event=>setHelpContact(event.target.value)}/></label><label>Liên hệ dự phòng<input value={backupContact} onChange={event=>setBackupContact(event.target.value)}/></label></div><div className={styles.formGrid}><label>Ngân sách dự kiến (VND)<input inputMode="numeric" value={budget} onChange={event=>setBudget(event.target.value)} placeholder="Không cần chi thì để trống"/></label><label>Hạn xử lý<input type="datetime-local" value={blockDue} onChange={event=>setBlockDue(event.target.value)}/></label></div><label className={styles.check}><input type="checkbox" checked={stopWork||item.critical} disabled={item.critical} onChange={event=>setStopWork(event.target.checked)}/> STOP — chưa được xếp / xuất hàng</label><div className={styles.actions}><button className={styles.danger} disabled={saving||!problem.trim()} onClick={()=>save({action:'block',itemId:item.id,problem,correctiveAction:correction,estimatedBudget:budget||null,responsibleTo:resolver||null,escalationContact:helpContact,secondaryContact:backupContact,dueAt:blockDue?new Date(blockDue).toISOString():null,stopWork:stopWork||item.critical})}>Gửi báo vướng</button><button onClick={()=>setBlockForm(false)}>Hủy</button></div></div>}
              </div>
            </div>}
          </article>})}</div>
      </details>})}</div>
    {manager&&run.status==='active'&&<button className={styles.close} disabled={saving||progress.done<progress.total||openBlockers.length>0||(order?.stage!=='completed'&&order?.status!=='completed')} onClick={()=>save({action:'close'})}>Khép hồ sơ vận hành</button>}
    <details className={styles.history}><summary>Lịch sử thực hiện ({events.length})</summary><ol>{events.map(event=><li key={event.id}><b>{event.action}</b> · {date(event.created_at)} · {person(profiles,event.actor_id)}<p>{event.detail}</p></li>)}</ol></details>
  </main>;
}
