"use client";
import {useEffect,useState} from 'react';
import styles from './ProspectDiscovery.module.css';
export default function ProspectPromotion({prospect,supabase,preview,onUpdated}){
 const [contacts,setContacts]=useState([]),[opportunity,setOpportunity]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){if(preview)return;const [c,o]=await Promise.all([supabase.from('discovery_contacts').select('id,kind,value').eq('prospect_id',prospect.id).in('kind',['email','phone']),supabase.from('trade_opportunities').select('id').eq('discovery_prospect_id',prospect.id).maybeSingle()]);if(c.error||o.error){setMessage('Chưa tải được liên kết Pipeline. Thử tải lại bên dưới.');return;}setContacts(c.data||[]);setOpportunity(o.data?.id||null);setMessage('');}
 useEffect(()=>{load();},[prospect.id,prospect.version,supabase,preview]);
 async function promote(event){event.preventDefault();setBusy(true);setMessage('');try{const contact=new FormData(event.currentTarget).get('contact');const {data,error}=await supabase.rpc('promote_discovery_prospect',{p_id:prospect.id,p_version:prospect.version,p_contact_id:contact});if(error)throw new Error(error.message.includes('shared_contact_conflict')?'Liên hệ này dùng chung với hồ sơ khác. Đối chiếu doanh nghiệp trước khi liên kết; chưa tạo cơ hội trùng.':error.message.includes('stale_prospect')?'Hồ sơ đã thay đổi. Tải lại danh sách trước khi đưa vào Pipeline.':'Chưa đưa vào Pipeline. Cần hồ sơ phù hợp, nguồn đã đọc và email hoặc số điện thoại công khai.');setOpportunity(data);const refreshed=await supabase.from('discovery_prospects').select('*').eq('id',prospect.id).single();if(refreshed.data)onUpdated?.(refreshed.data);}catch(error){setMessage(error.message);}finally{setBusy(false);}}
 return <section><h3>Tiến tới giao dịch</h3>{opportunity?<a className={styles.primary} href={`/admin/pipeline?opportunity=${encodeURIComponent(opportunity)}`}>Mở Pipeline → mẫu → báo giá → đơn hàng</a>:<form className={styles.review} onSubmit={promote}><p>Chọn liên hệ công khai đã đối chiếu. Thao tác chỉ tạo hoặc liên kết cơ hội, không gửi tin.</p><label>Liên hệ dùng trong Pipeline<select name="contact" required><option value="">Chọn email / điện thoại</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.value}</option>)}</select></label><button className={styles.primary} disabled={busy||preview||prospect.status!=='qualified'||prospect.evidence_kind!=='page_review'||!contacts.length}>Đưa vào Pipeline</button>{prospect.status!=='qualified'&&<small>Đánh dấu phù hợp sau khi đọc nguồn trước khi chuyển.</small>}</form>}{!preview&&<button type="button" onClick={load} disabled={busy}>Tải lại liên hệ & liên kết</button>}<p role="status">{message}</p></section>;
}
