"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { Activity,Archive,ArrowLeft,ArrowRight,BarChart3,Calendar,CheckCircle2,ChevronRight,CircleDollarSign,ClipboardCheck,ClipboardList,Clock3,Copy,ExternalLink,FlaskConical,Handshake,LogOut,MessageCircle,MessageSquare,PackageCheck,Plus,RefreshCw,RotateCcw,Save,Search,Send,SlidersHorizontal,Smartphone,Sprout,Trash2,Truck,Users,WalletCards } from "lucide-react";
import { fromOrderRow,fromThreadRow } from "@/lib/mappers";
import { ORDER_HEALTH,ORDER_STAGES,ORDER_WAITING_ON,orderStageIndex,orderStageMeta } from "@/lib/order-flow";
import { SHIPPING_CARRIERS,carrierLabel } from "@/lib/carrier-tracking";
import { ORDER_COST_CATEGORIES,ORDER_COST_STATUSES,orderCostAmount,orderEconomics } from "@/lib/order-costs";
import { MANUAL_MESSAGE_KINDS,buildManualOrderMessage,makeSmsHref,normalizeSmsPhone } from "@/lib/manual-order-message";
import NewOrderPanel from "./NewOrderPanel";
import FormattedNumberInput from "@/components/FormattedNumberInput";
import styles from "./StaffWorkbench.module.css";

const dateTime=(value)=>{const date=new Date(value);return !value||Number.isNaN(date.getTime())?"—":new Intl.DateTimeFormat("vi-VN",{dateStyle:"short",timeStyle:"short"}).format(date)};
const money=(value)=>value===null||value===undefined?"Chưa báo giá":new Intl.NumberFormat("vi-VN",{style:"currency",currency:"VND",maximumFractionDigits:0}).format(value);
const quantity=(order)=>{const totals=(order.lines||[]).reduce((result,line)=>{result[line.unit]=(result[line.unit]||0)+(Number(line.qty)||0);return result},{});return [totals.kg?`${totals.kg} kg`:"",totals.pcs?`${totals.pcs} gói`:""].filter(Boolean).join(" · ")||"Chưa có sản phẩm"};

export default function StaffWorkbench({supabase,email,role,onLogout}){
 const [orders,setOrders]=useState([]),[leads,setLeads]=useState([]),[samples,setSamples]=useState([]),[sessions,setSessions]=useState([]),[threads,setThreads]=useState([]),[customers,setCustomers]=useState([]),[selected,setSelected]=useState(null),[task,setTask]=useState(null),[activeThread,setActiveThread]=useState(null),[reply,setReply]=useState(""),[customer,setCustomer]=useState(null),[customerNote,setCustomerNote]=useState(""),[query,setQuery]=useState(""),[creatingOrder,setCreatingOrder]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [orderEvents,setOrderEvents]=useState([]),[orderCosts,setOrderCosts]=useState([]),[orderReceivable,setOrderReceivable]=useState(null),[detailLoading,setDetailLoading]=useState(false),[flowSaving,setFlowSaving]=useState(false),[healthDraft,setHealthDraft]=useState("on_track"),[waitingDraft,setWaitingDraft]=useState("us"),[healthNoteDraft,setHealthNoteDraft]=useState(""),[trackingDraft,setTrackingDraft]=useState(""),[carrierDraft,setCarrierDraft]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const [o,l,s,t,h,c]=await Promise.all([supabase.from("orders").select("*").order("ts",{ascending:false}),supabase.from("leads").select("*").order("ts",{ascending:false}),supabase.from("sample_requests").select("*").order("ts",{ascending:false}),supabase.from("tea_sessions").select("*").order("date",{ascending:true}),supabase.from("support_threads").select("*").order("created_at",{ascending:false}),supabase.rpc("customer_profiles_summary")]);const failed=[o,l,s,t,h,c].find(r=>r.error);if(failed)setError("Không tải được toàn bộ dữ liệu vận hành.");if(!o.error)setOrders((o.data||[]).map(fromOrderRow));if(!l.error)setLeads(l.data||[]);if(!s.error)setSamples(s.data||[]);if(!t.error)setSessions(t.data||[]);if(!h.error)setThreads((h.data||[]).map(fromThreadRow));if(!c.error)setCustomers(Array.isArray(c.data)?c.data:[]);setLoading(false)},[supabase]);
 useEffect(()=>{load()},[load]);
 const openOrders=orders.filter(o=>o.stage!=="completed"),unreadOrders=openOrders.filter(o=>o.unread),newLeads=leads.filter(l=>l.unread),newSamples=samples.filter(s=>s.unread||s.status==="new"),pendingSessions=sessions.filter(s=>s.status==="pending"),unreadThreads=threads.filter(thread=>thread.unreadForAdmin&&thread.messages.length>0);
 const queue=useMemo(()=>[
  ...unreadThreads.map(thread=>({kind:"message",id:thread.id,ts:thread.messages.at(-1)?.ts,title:thread.customerName,detail:thread.messages.at(-1)?.text||"Tin nhắn mới",record:thread,priority:1})),
  ...unreadOrders.map(o=>({kind:"order",id:o.id,ts:o.ts,title:o.customerName,detail:`${orderStageMeta(o.stage).label} · ${quantity(o)}`,record:o,priority:2})),
  ...newSamples.map(s=>({kind:"sample",id:s.id,ts:s.ts,title:s.store_name,detail:`Mẫu ${s.pack} · ${s.phone}`,record:s,priority:3})),
  ...newLeads.map(l=>({kind:"lead",id:l.id,ts:l.ts,title:l.business_name||l.name,detail:l.interest,record:l,priority:4})),
  ...pendingSessions.map(s=>({kind:"session",id:s.id,ts:`${s.date}T${s.session_time||"00:00"}`,title:s.customer_name,detail:`${s.date} · ${(s.session_time||"").slice(0,5)}`,record:s,priority:5})),
 ].sort((a,b)=>a.priority-b.priority||new Date(a.ts)-new Date(b.ts)),[unreadThreads,unreadOrders,newSamples,newLeads,pendingSessions]);
 const filtered=orders.filter(o=>`${o.id} ${o.customerName} ${o.contact}`.toLowerCase().includes(query.toLowerCase()));
 const staffRequest=useCallback(async(orderId,{method="GET",body}={})=>{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("not_authenticated");const response=await fetch(`/api/staff/orders/${encodeURIComponent(orderId)}`,{method,headers:{Authorization:`Bearer ${session.access_token}`,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});if(!response.ok)throw new Error(`order_request_${response.status}`);return response.json()},[supabase]);
 const costRequest=useCallback(async(orderId,{method="POST",body}={})=>{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("not_authenticated");const response=await fetch(`/api/staff/orders/${encodeURIComponent(orderId)}/costs`,{method,headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify(body||{})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||`cost_request_${response.status}`);return result},[supabase]);
 const loadEvents=useCallback(async(orderId)=>{setDetailLoading(true);try{const result=await staffRequest(orderId);setOrderEvents(result.events||[]);setOrderCosts(result.costs||[]);setOrderReceivable(result.receivable||null)}catch{setOrderEvents([]);setOrderCosts([]);setOrderReceivable(null)}finally{setDetailLoading(false)}},[staffRequest]);
 const selectOrder=async(order)=>{setTask(null);setActiveThread(null);setCustomer(null);const next=order.unread?{...order,unread:false}:order;setSelected(next);setHealthDraft(next.health||"on_track");setWaitingDraft(next.waitingOn||"us");setHealthNoteDraft(next.healthNote||"");setTrackingDraft(next.trackingCode||"");setCarrierDraft(next.shippingCarrier||"");setOrderEvents([]);loadEvents(next.id);if(order.unread){await supabase.from("orders").update({unread:false}).eq("id",order.id);setOrders(current=>current.map(o=>o.id===order.id?next:o))}};
 const openThread=async(thread)=>{setSelected(null);setTask(null);setCustomer(null);setActiveThread(thread);if(thread.unreadForAdmin){await supabase.from("support_threads").update({unread_for_admin:false}).eq("id",thread.id);const next={...thread,unreadForAdmin:false};setThreads(current=>current.map(item=>item.id===thread.id?next:item));setActiveThread(next)}};
 const openTask=(item)=>{if(item.kind==="order"){selectOrder(item.record);return}if(item.kind==="message"){openThread(item.record);return}setActiveThread(null);setCustomer(null);setSelected(null);setTask(item)};
 const updateOrderFlow=async(patch)=>{if(!selected||flowSaving)return false;setFlowSaving(true);setError("");try{const result=await staffRequest(selected.id,{method:"PATCH",body:patch});const next=fromOrderRow(result.order);setOrders(current=>current.map(order=>order.id===next.id?next:order));setSelected(next);setOrderEvents(result.events||[]);setHealthDraft(next.health);setWaitingDraft(next.waitingOn||"us");setHealthNoteDraft(next.healthNote||"");setTrackingDraft(next.trackingCode||"");setCarrierDraft(next.shippingCarrier||"");return true}catch{setError("Chưa cập nhật được luồng đơn. Hãy thử lại.");return false}finally{setFlowSaving(false)}};
 const issueOrderReceivable=async()=>{if(!selected||flowSaving||Number(selected.estimatedTotal)<=0)return false;setFlowSaving(true);setError("");const today=new Date().toISOString().slice(0,10);const {error:issueError}=await supabase.rpc("issue_receivable",{p_order_id:selected.id,p_invoice_number:`TT-${selected.id}`,p_issued_at:today,p_due_at:null,p_payment_terms:"Chuyển khoản theo mã QR hoặc thông tin tài khoản trên trang đơn hàng.",p_note:"Yêu cầu thanh toán tạo từ trang điều phối đơn."});setFlowSaving(false);if(issueError){await loadEvents(selected.id);setError("Chưa mở được theo dõi thanh toán. Kiểm tra tổng đơn hoặc yêu cầu thanh toán đã có trước đó.");return false}await loadEvents(selected.id);return true};
 const recordOrderPayment=async(amount)=>{if(!selected||!orderReceivable||flowSaving)return false;setFlowSaving(true);setError("");const {error:paymentError}=await supabase.rpc("record_receivable_payment",{p_receivable_id:orderReceivable.id,p_amount:Number(amount),p_method:selected.paymentMethod==="cash"?"cash":"bank_transfer",p_reference:"",p_note:"Ghi nhận tại trang điều phối đơn.",p_actor:email});setFlowSaving(false);if(paymentError){setError("Chưa ghi nhận được khoản thanh toán. Số tiền không được vượt phần còn lại.");return false}await loadEvents(selected.id);return true};
 const addOrderCost=async(payload)=>{if(!selected)return false;setError("");try{const result=await costRequest(selected.id,{body:payload});setOrderCosts(current=>[result.cost,...current]);loadEvents(selected.id);return true}catch{setError("Chưa lưu được chi phí của đơn. Kiểm tra nội dung và số tiền.");return false}};
 const syncOrderCosts=async()=>{if(!selected)return false;setError("");try{const result=await costRequest(selected.id,{method:"PUT"});setOrderCosts(result.costs||[]);loadEvents(selected.id);return true}catch(error){setError(error.message==="material_migration_required"?"Chưa có sổ định mức vật tư. Cần áp dụng migration 0052.":"Chưa đồng bộ được chi phí từ định mức.");return false}};
 const deleteOrderCost=async(costId)=>{if(!selected)return false;setError("");try{await costRequest(selected.id,{method:"DELETE",body:{costId}});setOrderCosts(current=>current.filter(item=>item.id!==costId));loadEvents(selected.id);return true}catch(error){setError(error.message==="classified_expense"?"Khoản này đã được phân loại vào ngân sách nên không thể xóa tại đơn.":"Chưa xóa được chi phí của đơn.");return false}};
 const acknowledgeLead=async(lead)=>{const {error:updateError}=await supabase.from("leads").update({unread:false}).eq("id",lead.id);if(updateError){setError("Chưa cập nhật được lead.");return}setLeads(current=>current.map(item=>item.id===lead.id?{...item,unread:false}:item))};
 const sendSample=async(sample)=>{const {error:updateError}=await supabase.from("sample_requests").update({status:"sent",unread:false}).eq("id",sample.id);if(updateError){setError("Chưa cập nhật được mẫu thử.");return}setSamples(current=>current.map(item=>item.id===sample.id?{...item,status:"sent",unread:false}:item))};
 const confirmSession=async(session)=>{const {error:updateError}=await supabase.from("tea_sessions").update({status:"confirmed"}).eq("id",session.id);if(updateError){setError("Chưa xác nhận được lịch trà.");return}setSessions(current=>current.map(item=>item.id===session.id?{...item,status:"confirmed"}:item))};
 const sendReply=async(event)=>{event.preventDefault();if(!activeThread||!reply.trim())return;const nextMessages=[...activeThread.messages,{from:"admin",text:reply.trim(),ts:new Date().toISOString()}];const {error:updateError}=await supabase.from("support_threads").update({messages:nextMessages,unread_for_admin:false}).eq("id",activeThread.id);if(updateError){setError("Chưa gửi được phản hồi.");return}const next={...activeThread,messages:nextMessages,unreadForAdmin:false};setThreads(current=>current.map(item=>item.id===next.id?next:item));setActiveThread(next);setReply("")};
 const openCustomer=async(profile)=>{setSelected(null);setTask(null);setActiveThread(null);const {data,error:detailError}=await supabase.rpc("customer_detail",{p_contact:profile.contact});if(detailError){setError("Chưa tải được hồ sơ khách hàng.");return}setCustomer({...profile,detail:data});setCustomerNote(data?.note||"")};
 const saveCustomerNote=async()=>{if(!customer)return;const {error:noteError}=await supabase.rpc("save_customer_note",{p_contact:customer.contact,p_note:customerNote,p_by:email});if(noteError){setError("Chưa lưu được ghi chú khách hàng.");return}setCustomer(current=>({...current,detail:{...current.detail,note:customerNote}}))};
 const orderCreated=async(order)=>{setOrders(current=>[order,...current.filter(item=>item.id!==order.id)]);setCreatingOrder(false);try{await staffRequest(order.id,{method:"POST"})}catch{}await selectOrder(order);requestAnimationFrame(()=>document.querySelector("#orders")?.scrollIntoView({behavior:"smooth",block:"start"}))};
 const cards=[{label:"Cần xử lý",value:queue.length,icon:ClipboardList},{label:"Đơn đang mở",value:openOrders.length,icon:PackageCheck},{label:"Tin chưa đọc",value:unreadThreads.length,icon:MessageSquare},{label:"Lịch trà chờ",value:pendingSessions.length,icon:Calendar}];
 return <main className={styles.shell}>
  <aside className={styles.rail}><div className={styles.brand}><span>皇龍</span><b>HL</b></div><nav aria-label="Staff workspace"><Link href="/admin"><Calendar/><span>Bảng điều khiển</span></Link><Link href="/admin/work"><ClipboardCheck/><span>Công việc</span></Link><Link href="/admin/orders" className={styles.active}><ClipboardList/><span>Điều phối đơn</span>{queue.length>0&&<b>{queue.length}</b>}</Link><Link href="/admin/pipeline"><Handshake/><span>Khách hàng CRM</span></Link><Link href="/admin/operations"><BarChart3/><span>Vận hành & tài chính</span></Link><Link href="/admin/house"><Sprout/><span>Nhà & danh mục</span></Link><Link href="/admin/control"><SlidersHorizontal/><span>Thương mại</span></Link><Link href="/admin/legacy"><Archive/><span>Hệ thống cũ</span></Link><Link href="/admin/growth"><FlaskConical/><span>Công cụ</span></Link></nav><button onClick={onLogout} aria-label="Đăng xuất"><LogOut/><span>Đăng xuất</span></button></aside>
  <section className={styles.workspace}>
   <header className={styles.top}><div><p>Staff workbench</p><h1>Điều phối hôm nay</h1></div><div className={styles.identity}><span><b>{email}</b><small>{role}</small></span><button onClick={load} disabled={loading} aria-label="Làm mới"><RefreshCw className={loading?styles.spin:""}/></button></div></header>
   {error&&<p className={styles.error} role="alert">{error}</p>}
   <section className={styles.metrics}>{cards.map(({label,value,icon:Icon})=><article key={label}><Icon/><span>{label}</span><b>{loading?"—":value}</b></article>)}</section>
   <section className={styles.board} id="queue"><header><div><p>Hàng đợi chung</p><h2>Việc cần chạm vào</h2></div><span>{queue.length} mục</span></header>{loading?<div className={styles.skeleton}><i/><i/><i/></div>:queue.length?<div className={styles.queue}>{queue.slice(0,12).map(item=><button key={`${item.kind}-${item.id}`} onClick={()=>openTask(item)}><span className={styles.kind}>{item.kind}</span><span><b>{item.title}</b><small>{item.detail}</small></span><time>{dateTime(item.ts)}</time><ChevronRight/></button>)}</div>:<div className={styles.clear}><PackageCheck/><h3>Hàng đợi đã sạch.</h3><p>Không có đơn, mẫu, lead hoặc lịch trà mới đang chờ.</p></div>}</section>
   <section className={styles.orders} id="orders"><header><div><p>Order book</p><h2>Tất cả đơn hàng</h2></div><div className={styles.orderTools}><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm tên, liên hệ, mã đơn"/></label><button className={styles.createOrder} onClick={()=>setCreatingOrder(true)} title="Mở phiếu tạo đơn; bạn sẽ kiểm tra lại trước khi đơn được lưu."><Plus/>Tạo đơn</button></div></header><div className={styles.orderList}>{filtered.map(order=><button key={order.id} onClick={()=>selectOrder(order)} className={selected?.id===order.id?styles.selected:""}><span><b>{order.customerName}</b><small>{order.id} · {quantity(order)}</small></span><span>{money(order.estimatedTotal)}</span><span className={styles.orderState} data-status={order.status}><b>{orderStageMeta(order.stage).shortLabel}</b><small data-health={order.health}>{ORDER_HEALTH.find(item=>item.id===order.health)?.shortLabel||"Đúng tiến độ"}</small></span><ChevronRight/></button>)}</div></section>
   <section className={styles.inbox} id="messages"><header><div><p>House inbox</p><h2>Đối thoại với khách</h2></div><span>{unreadThreads.length} chưa đọc</span></header><div className={styles.inboxGrid}><div className={styles.threadList}>{threads.length?threads.map(thread=><button key={thread.id} onClick={()=>openThread(thread)} className={activeThread?.id===thread.id?styles.selected:""}><span><b>{thread.customerName}</b><small>{thread.messages.at(-1)?.text||"Chưa có tin nhắn"}</small></span>{thread.unreadForAdmin&&<i>Mới</i>}</button>):<p>Chưa có cuộc trò chuyện.</p>}</div>{activeThread?<div className={styles.chat}><header><b>{activeThread.customerName}</b><small>{activeThread.role}</small></header><div>{activeThread.messages.map((message,index)=><article key={`${message.ts}-${index}`} data-from={message.from}><span>{message.text}</span><time>{dateTime(message.ts)}</time></article>)}</div><form onSubmit={sendReply}><textarea value={reply} onChange={event=>setReply(event.target.value)} placeholder="Viết phản hồi…"/><button disabled={!reply.trim()} aria-label="Gửi phản hồi"><Send/></button></form></div>:<div className={styles.noThread}><MessageSquare/><p>Chọn một cuộc trò chuyện để đọc và trả lời.</p></div>}</div></section>
   <section className={styles.relationships} id="contacts"><header><div><p>Relationship desk</p><h2>Lead, mẫu thử và lịch trà</h2></div><span>Hành động nhanh, không rời hàng đợi</span></header><div className={styles.relationshipGrid}>
    <article><header><Users/><span><b>Lead mới</b><small>{newLeads.length} cần liên hệ</small></span></header><div>{leads.slice(0,8).map(lead=><section key={lead.id}><span><b>{lead.business_name||lead.name}</b><small>{lead.contact} · {lead.interest}</small></span>{lead.unread?<button onClick={()=>acknowledgeLead(lead)}>Đã liên hệ</button>:<i>Đã nhận</i>}</section>)}</div></article>
    <article><header><PackageCheck/><span><b>Mẫu thử</b><small>{newSamples.length} đang chờ</small></span></header><div>{samples.slice(0,8).map(sample=><section key={sample.id}><span><b>{sample.store_name}</b><small>{sample.pack} · {sample.phone}</small></span>{sample.status==="new"?<button onClick={()=>sendSample(sample)}>Đã gửi</button>:<i>{sample.status}</i>}</section>)}</div></article>
    <article><header><Calendar/><span><b>Lịch trà</b><small>{pendingSessions.length} chờ xác nhận</small></span></header><div>{sessions.slice(0,8).map(session=><section key={session.id}><span><b>{session.customer_name}</b><small>{session.date} · {(session.session_time||"").slice(0,5)}</small></span>{session.status==="pending"?<button onClick={()=>confirmSession(session)}>Xác nhận</button>:<i>{session.status}</i>}</section>)}</div></article>
   </div></section>
   <section className={styles.customers} id="customers"><header><div><p>Customer memory</p><h2>Lịch sử khách hàng</h2></div><span>{customers.length} hồ sơ</span></header><div>{customers.slice(0,20).map(profile=><button key={profile.contact_key} onClick={()=>openCustomer(profile)}><span><b>{profile.customer_name}</b><small>{profile.contact}</small></span><span>{profile.order_count} đơn</span><span>{money(profile.total_spent)}</span><ChevronRight/></button>)}</div></section>
  </section>
  {selected&&<OrderDetail
   order={selected} events={orderEvents} costs={orderCosts} receivable={orderReceivable} loadingEvents={detailLoading} saving={flowSaving}
   healthDraft={healthDraft} setHealthDraft={setHealthDraft} waitingDraft={waitingDraft} setWaitingDraft={setWaitingDraft}
   healthNoteDraft={healthNoteDraft} setHealthNoteDraft={setHealthNoteDraft} trackingDraft={trackingDraft} setTrackingDraft={setTrackingDraft}
   carrierDraft={carrierDraft} setCarrierDraft={setCarrierDraft} onUpdate={updateOrderFlow} onIssueReceivable={issueOrderReceivable} onRecordPayment={recordOrderPayment} onAddCost={addOrderCost} onSyncCosts={syncOrderCosts} onDeleteCost={deleteOrderCost} onClose={()=>setSelected(null)}
  />}
  {task&&<aside className={styles.detail} aria-label="Chi tiết việc cần xử lý"><header><div><p>{task.kind}</p><h2>{task.title}</h2></div><button onClick={()=>setTask(null)} aria-label="Đóng">×</button></header><dl><div><dt>Mã</dt><dd>{task.id}</dd></div><div><dt>Nhận lúc</dt><dd>{dateTime(task.ts)}</dd></div><div><dt>Chi tiết</dt><dd>{task.detail}</dd></div>{task.record.contact&&<div><dt>Liên hệ</dt><dd>{task.record.contact}</dd></div>}{task.record.phone&&<div><dt>Điện thoại</dt><dd>{task.record.phone}</dd></div>}{task.record.address&&<div><dt>Địa chỉ</dt><dd>{task.record.address}</dd></div>}{task.record.note&&<div><dt>Ghi chú</dt><dd>{task.record.note}</dd></div>}</dl><Link href="/admin/legacy">Xử lý trong hệ thống đầy đủ <ArrowRight/></Link></aside>}
  {customer&&<aside className={styles.detail} aria-label="Hồ sơ khách hàng"><header><div><p>Customer memory</p><h2>{customer.customer_name}</h2></div><button onClick={()=>setCustomer(null)} aria-label="Đóng">×</button></header><dl><div><dt>Liên hệ</dt><dd>{customer.contact}</dd></div><div><dt>Số đơn</dt><dd>{customer.order_count}</dd></div><div><dt>Tổng chi</dt><dd>{money(customer.total_spent)}</dd></div><div><dt>Đơn gần nhất</dt><dd>{dateTime(customer.last_order)}</dd></div></dl><div className={styles.history}><h3>Lịch sử đơn</h3>{(customer.detail?.history||[]).map(item=><div key={item.id}><span><b>{item.id}</b><small>{dateTime(item.ts)}</small></span><span>{money(item.total)}</span></div>)}</div><label className={styles.houseNote}>Ghi nhớ của Nhà<textarea value={customerNote} onChange={event=>setCustomerNote(event.target.value)} placeholder="Cách uống, nơi nhận, điều cần nhớ…"/></label><button className={styles.advance} onClick={saveCustomerNote}>Lưu ghi nhớ</button></aside>}
  {creatingOrder&&<NewOrderPanel supabase={supabase} onClose={()=>setCreatingOrder(false)} onCreated={orderCreated}/>}
 </main>
}

function OrderDetail({order,events,costs,receivable,loadingEvents,saving,healthDraft,setHealthDraft,waitingDraft,setWaitingDraft,healthNoteDraft,setHealthNoteDraft,trackingDraft,setTrackingDraft,carrierDraft,setCarrierDraft,onUpdate,onIssueReceivable,onRecordPayment,onAddCost,onSyncCosts,onDeleteCost,onClose}){
 const stageIndex=orderStageIndex(order.stage),stage=ORDER_STAGES[stageIndex],nextStage=ORDER_STAGES[stageIndex+1],previousStage=ORDER_STAGES[stageIndex-1];
 const amountDue=receivable&&["open","partial"].includes(receivable.status)?Math.max(0,Number(receivable.total||0)-Number(receivable.paid||0)):0;
 const defaultMessageKind=()=>(stage.id==="completed"||order.status==="completed")?(amountDue>0?"delivered_due":"delivered"):"shipping";
 const freshCost=()=>({category:"tea",description:"",quantity:"1",unitCost:"",paymentStatus:"planned",incurredOn:new Date().toISOString().slice(0,10),note:"",recordExpense:false});
 const [editingPrices,setEditingPrices]=useState(false),[priceDrafts,setPriceDrafts]=useState(()=>(order.lines||[]).map(line=>line.price??""));
 const [addingCost,setAddingCost]=useState(false),[costSaving,setCostSaving]=useState(false),[costDraft,setCostDraft]=useState(freshCost);
 const [paymentAmount,setPaymentAmount]=useState(amountDue||"");
 const [messageKind,setMessageKind]=useState(defaultMessageKind),[messageDraft,setMessageDraft]=useState(()=>buildManualOrderMessage({order,kind:defaultMessageKind(),amountDue})),[smsPlatform,setSmsPlatform]=useState("android"),[messageCopied,setMessageCopied]=useState(false);
 useEffect(()=>{setPriceDrafts((order.lines||[]).map(line=>line.price??""));setEditingPrices(false);setAddingCost(false);setCostDraft(freshCost());setMessageCopied(false)},[order.id,order.lines]);
 useEffect(()=>{const nextKind=defaultMessageKind();setMessageKind(nextKind);setMessageDraft(buildManualOrderMessage({order,kind:nextKind,amountDue}))},[order.id,amountDue,stage.id]);
 useEffect(()=>{setPaymentAmount(amountDue||"")},[order.id,receivable?.id,amountDue]);
 useEffect(()=>{const agent=navigator.userAgent||"";setSmsPlatform(/iPhone|iPad|iPod/i.test(agent)||(/Macintosh/i.test(agent)&&navigator.maxTouchPoints>1)?"ios":"android")},[]);
 const pricesComplete=priceDrafts.length>0&&priceDrafts.every(value=>value!==""&&Number.isFinite(Number(value))&&Number(value)>=0);
 const pricePreview=pricesComplete?order.lines.reduce((total,line,index)=>total+(Number(line.qty)||0)*Number(priceDrafts[index]),0):null;
 const economics=useMemo(()=>orderEconomics(order.estimatedTotal,costs),[order.estimatedTotal,costs]);
 const savePrices=async()=>{const saved=await onUpdate({linePrices:priceDrafts.map((value,index)=>({index,price:value===""?null:Number(value)}))});if(saved)setEditingPrices(false)};
 const saveHealth=()=>onUpdate({health:healthDraft,waitingOn:healthDraft==="on_track"?null:waitingDraft,healthNote:healthDraft==="on_track"?"":healthNoteDraft});
 const savePayment=async(event)=>{event.preventDefault();const saved=await onRecordPayment(Number(paymentAmount));if(saved)setPaymentAmount("")};
 const saveCost=async(event)=>{event.preventDefault();setCostSaving(true);const saved=await onAddCost({...costDraft,quantity:Number(costDraft.quantity),unitCost:Number(costDraft.unitCost)});setCostSaving(false);if(saved){setCostDraft(freshCost());setAddingCost(false)}};
 const syncCosts=async()=>{setCostSaving(true);await onSyncCosts();setCostSaving(false)};
 const removeCost=async(cost)=>{if(!window.confirm(`Xóa chi phí “${cost.description}”?${cost.expense_id?" Khoản liên kết trong Hộp chi phí cũng sẽ được xóa nếu chưa phân loại.":""}`))return;setCostSaving(true);await onDeleteCost(cost.id);setCostSaving(false)};
 const categoryLabel=(id)=>ORDER_COST_CATEGORIES.find(item=>item.id===id)?.label||id;
 const statusLabel=(id)=>ORDER_COST_STATUSES.find(item=>item.id===id)?.label||id;
 const smsPhone=normalizeSmsPhone(order.contact),customerPageUrl=order.publicTrackingToken?`https://www.hoanglongtra.com/don-hang/${encodeURIComponent(order.publicTrackingToken)}`:"";
 const suggestedMessage=buildManualOrderMessage({order,kind:messageKind,amountDue}),customerMessage=messageDraft;
 const smsHref=makeSmsHref(smsPhone,customerMessage,smsPlatform);
 const copyCustomerMessage=async()=>{try{await navigator.clipboard.writeText(customerMessage);setMessageCopied(true);window.setTimeout(()=>setMessageCopied(false),1800)}catch{setMessageCopied(false)}};
 const chooseMessageKind=(kind)=>{setMessageKind(kind);setMessageDraft(buildManualOrderMessage({order,kind,amountDue}));setMessageCopied(false)};

 return <aside className={`${styles.detail} ${styles.orderDetail}`} aria-label="Kiểm tra và điều phối đơn hàng" aria-modal="true" role="dialog">
  <header><div><p>Order inspection</p><h2>{order.customerName}</h2><span className={styles.detailStage}>{stage.number} · {stage.label}</span></div><button onClick={onClose} aria-label="Đóng">×</button></header>
  <section className={styles.flowSection} aria-labelledby="order-flow-title"><div className={styles.detailSectionTitle}><Activity/><span><b id="order-flow-title">Luồng xử lý</b><small>Mỗi lần chỉ tiến hoặc lùi một bước.</small></span></div><ol className={styles.orderSpine}>{ORDER_STAGES.map((item,index)=><li key={item.id} data-state={index<stageIndex?"done":index===stageIndex?"current":"future"}><span>{index<stageIndex?<CheckCircle2/>:item.number}</span><div><b>{item.label}</b>{index===stageIndex&&<small>Đang ở đây</small>}</div></li>)}</ol>
   <div className={styles.nextAction}><span>Việc cần làm ở bước này</span><p>{stage.nextAction}</p></div>
   <div className={styles.flowActions}>{previousStage&&<button className={styles.backStage} disabled={saving} onClick={()=>onUpdate({stage:previousStage.id})} title={`Đưa đơn trở lại bước ${previousStage.label} để sửa hoặc làm lại.`}><ArrowLeft/>Lùi về {previousStage.shortLabel}</button>}{nextStage?<button className={styles.advance} disabled={saving} onClick={()=>onUpdate({stage:nextStage.id})} title={`Hoàn tất bước ${stage.label} và chuyển đơn sang ${nextStage.label}.`}>{saving?"Đang cập nhật…":`Xong bước này · sang ${nextStage.shortLabel}`}<ArrowRight/></button>:<p className={styles.done}><CheckCircle2/> Đơn đã hoàn tất.</p>}</div>
  </section>
  <section className={styles.healthSection}><div className={styles.detailSectionTitle}><Clock3/><span><b>Nhịp của đơn</b><small>Ghi rõ nếu đơn đang chờ hoặc bị vướng.</small></span></div><div className={styles.healthChoices}>{ORDER_HEALTH.map(item=><button type="button" key={item.id} data-active={healthDraft===item.id} data-health={item.id} onClick={()=>setHealthDraft(item.id)} title={item.id==="on_track"?"Đơn vẫn đang di chuyển đúng kế hoạch.":item.id==="waiting"?"Đơn tạm dừng vì đang chờ một bên phản hồi hoặc bàn giao.":"Có vấn đề ngăn đơn tiếp tục; cần người xử lý."}>{item.label}</button>)}</div>{healthDraft!=="on_track"&&<div className={styles.healthFields}><label>Đang chờ ai<select value={waitingDraft} onChange={event=>setWaitingDraft(event.target.value)}>{ORDER_WAITING_ON.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Lý do / việc cần gỡ<textarea value={healthNoteDraft} onChange={event=>setHealthNoteDraft(event.target.value)} placeholder="Ví dụ: khách chưa chốt nhãn; chờ túi 500 g…"/></label></div>}<button className={styles.saveState} disabled={saving} onClick={saveHealth} title="Lưu tình trạng này vào đơn và ghi một dòng trong lịch sử."><Save/>Lưu tình trạng</button></section>
  {stageIndex>=4&&<section className={styles.trackingSection}><div className={styles.detailSectionTitle}><Truck/><span><b>Vận chuyển</b><small>Hãng sẽ cập nhật hành trình; giao thành công sẽ tự khép đơn.</small></span></div><div className={styles.trackingFields}><label>Đơn vị vận chuyển<select value={carrierDraft} onChange={event=>setCarrierDraft(event.target.value)}><option value="">Chọn hãng</option>{SHIPPING_CARRIERS.map(carrier=><option key={carrier.id} value={carrier.id}>{carrier.label}</option>)}</select></label><label>Mã vận đơn<input value={trackingDraft} onChange={event=>setTrackingDraft(event.target.value)} placeholder="Nhập mã vận đơn" autoCapitalize="characters"/></label><button disabled={saving||(Boolean(carrierDraft)!==Boolean(trackingDraft))||(carrierDraft===(order.shippingCarrier||"")&&trackingDraft===(order.trackingCode||""))} onClick={()=>onUpdate({shippingCarrier:carrierDraft||null,trackingCode:trackingDraft})} title="Lưu hãng và mã vận đơn. Hệ thống bắt đầu nhận trạng thái do hãng gửi về.">Lưu vận chuyển</button></div>{order.shippingCarrier&&order.trackingCode&&<div className={styles.carrierState} data-delivered={Boolean(order.deliveredAt)}><span><i/><b>{carrierLabel(order.shippingCarrier)}</b><code>{order.trackingCode}</code></span><p>{order.carrierStatusName?`${order.carrierStatusName}${order.carrierStatusCode?` · ${order.carrierStatusCode}`:""}`:"Đã kết nối · đang chờ trạng thái đầu tiên từ hãng"}</p>{order.carrierStatusAt&&<small>Cập nhật {dateTime(order.carrierStatusAt)}</small>}</div>}{order.publicTrackingToken&&<Link href={`/don-hang/${order.publicTrackingToken}`} target="_blank" title="Mở đúng trang mà khách sẽ thấy từ link trong tin nhắn.">Mở trang khách theo dõi <ArrowRight/></Link>}</section>}
  <section className={styles.paymentControlSection}><div className={styles.detailSectionTitle}><WalletCards/><span><b>Thanh toán của đơn</b><small>Số dư ở đây cũng là số tiền khách thấy trên trang theo dõi.</small></span></div>
   {!receivable?<div className={styles.paymentSetup}><span><small>Tổng cần theo dõi</small><b>{money(order.estimatedTotal)}</b></span><p>Mở theo dõi để hiện số tiền còn lại, QR và thông tin chuyển khoản trên link của khách.</p><button disabled={saving||Number(order.estimatedTotal)<=0} onClick={onIssueReceivable}>{saving?"Đang mở…":"Mở theo dõi thanh toán"}</button></div>:<>
    <div className={styles.paymentLedger}><div><span>Tổng đơn</span><b>{money(receivable.total)}</b></div><div><span>Đã ghi nhận</span><b>{money(receivable.paid)}</b></div><div data-due={amountDue>0}><span>Còn lại</span><b>{money(amountDue)}</b></div></div>
    {amountDue>0?<form className={styles.paymentRecord} onSubmit={savePayment}><label><span>Khoản vừa nhận</span><FormattedNumberInput required min="1" max={amountDue} step="1000" value={paymentAmount} onChange={event=>setPaymentAmount(event.target.value)} placeholder="Nhập số tiền"/></label><button disabled={saving||Number(paymentAmount)<=0||Number(paymentAmount)>amountDue}>{saving?"Đang lưu…":"Ghi nhận đã nhận tiền"}</button><small>{order.paymentMethod==="cash"?"Sẽ ghi là tiền mặt.":"Sẽ ghi là chuyển khoản."} Trang khách cập nhật ngay sau khi lưu.</small></form>:<p className={styles.paymentComplete}><CheckCircle2/>Đơn đã được ghi nhận thanh toán đủ.</p>}
   </>}
  </section>
  <section className={styles.messageSection}><div className={styles.detailSectionTitle}><MessageCircle/><span><b>Nhắn khách qua SMS</b><small>Xem trước, rồi mở ứng dụng Tin nhắn trên điện thoại để tự bấm gửi.</small></span></div>
   <div className={styles.messageKinds}>{MANUAL_MESSAGE_KINDS.map(item=><button type="button" key={item.id} data-active={messageKind===item.id} disabled={item.id==="delivered_due"&&amountDue<=0} onClick={()=>chooseMessageKind(item.id)} title={item.id==="delivered_due"&&amountDue<=0?"Đơn chưa có khoản phải thu đang mở.":`Dùng mẫu ${item.label.toLowerCase()}.`}>{item.label}</button>)}</div>
   <div className={styles.recipient}><Smartphone/><span><small>Số sẽ nhận tin</small><b>{smsPhone||order.contact||"Chưa có số điện thoại hợp lệ"}</b></span></div>
   <article className={styles.messagePreview}><header><span>Hoàng Long</span><small>Tin nhắn khách sẽ nhận · có thể sửa</small></header><textarea aria-label="Sửa nội dung SMS" value={messageDraft} onChange={event=>{setMessageDraft(event.target.value);setMessageCopied(false)}}/><footer><span>{customerMessage.length} ký tự</span><div><button type="button" disabled={messageDraft===suggestedMessage} onClick={()=>setMessageDraft(suggestedMessage)} title="Bỏ phần đã sửa và khôi phục đúng mẫu đang chọn."><RotateCcw/>Khôi phục mẫu</button><button type="button" onClick={copyCustomerMessage} title="Sao chép đúng nội dung đang xem để dán thủ công nếu điện thoại không điền sẵn."><Copy/>{messageCopied?"Đã sao chép":"Sao chép"}</button></div></footer></article>
   <a className={styles.smsOpen} href={smsHref||undefined} aria-disabled={!smsHref||!customerMessage.trim()} onClick={event=>{if(!smsHref||!customerMessage.trim())event.preventDefault()}} title="Mở ứng dụng SMS với số khách và nội dung này đã được điền; bạn vẫn là người xác nhận gửi."><MessageCircle/>Mở SMS trên điện thoại</a>
   {!smsPhone&&<p className={styles.smsWarning}>Liên hệ của đơn chưa chứa số điện thoại Việt Nam hợp lệ.</p>}
   {customerPageUrl&&<details className={styles.pagePreview}><summary><span><b>Xem trang khách sẽ mở</b><small>{customerPageUrl}</small></span><ExternalLink/></summary><div className={styles.phoneFrame}><iframe src={customerPageUrl} title={`Trang theo dõi của đơn ${order.id}`} loading="lazy"/></div><a href={customerPageUrl} target="_blank" rel="noreferrer">Mở toàn màn hình <ExternalLink/></a></details>}
  </section>
  <section className={styles.orderFacts}><div className={styles.detailSectionTitle}><ClipboardList/><span><b>Thông tin đã đặt</b><small>{dateTime(order.ts)}</small></span><button className={styles.priceEditToggle} onClick={()=>setEditingPrices(current=>!current)} title="Mở giá bán của từng dòng để điều chỉnh riêng cho đơn này.">{editingPrices?"Hủy chỉnh giá":"Điều chỉnh giá bán"}</button></div><dl><div><dt>Mã đơn</dt><dd>{order.id}</dd></div><div><dt>Liên hệ</dt><dd>{order.contact}</dd></div><div><dt>Địa chỉ</dt><dd>{order.address||"—"}</dd></div><div><dt>Thanh toán</dt><dd>{order.paymentMethod==="cash"?"Tiền mặt":"Chuyển khoản QR"}</dd></div>{order.note&&<div><dt>Ghi chú</dt><dd>{order.note}</dd></div>}</dl><div className={styles.lines}>{(order.lines||[]).map((line,index)=><div key={index}><span><b>{line.name?.vi||line.name?.en}</b><small>{line.qty} {line.unit}{line.price!==null&&line.price!==undefined?` × ${money(line.price)}`:" · chưa báo giá"}</small></span>{editingPrices?<label className={styles.linePriceEditor}><span>Giá / {line.unit}</span><FormattedNumberInput min="0" step="1000" value={priceDrafts[index]} onChange={event=>setPriceDrafts(current=>current.map((value,itemIndex)=>itemIndex===index?event.target.value:value))} placeholder="Chưa báo giá"/></label>:<span>{line.price!==null&&line.price!==undefined?money(line.price*line.qty):"—"}</span>}</div>)}</div>{editingPrices&&<div className={styles.priceSaveBar}><span><small>Tổng sau điều chỉnh</small><b>{money(pricePreview)}</b></span><button disabled={saving} onClick={savePrices} title="Lưu giá riêng vào đơn, tính lại tổng và ghi thay đổi vào lịch sử."><Save/>Lưu giá riêng</button></div>}<div className={styles.detailTotal}><span>Tổng dự kiến</span><b>{money(order.estimatedTotal)}</b></div></section>
  <section className={styles.costSection}><div className={styles.detailSectionTitle}><CircleDollarSign/><span><b>Chi phí của đơn</b><small>Định mức tự tạo giá vốn; chỉ thêm tay các khoản riêng của đơn.</small></span><div className={styles.costTools}><button onClick={syncCosts} disabled={costSaving} title="Tính lại trà, bao bì và nhãn từ định mức đang áp dụng cho từng sản phẩm trong đơn."><RefreshCw/>Tính từ định mức</button><button onClick={()=>setAddingCost(current=>!current)} title="Mở phiếu thêm vận chuyển hoặc chi phí riêng không có trong định mức.">{addingCost?"Đóng phiếu":"Thêm riêng"}</button></div></div>
   {addingCost&&<form className={styles.costForm} onSubmit={saveCost}><label>Loại chi phí<select value={costDraft.category} onChange={event=>setCostDraft(current=>({...current,category:event.target.value}))}>{ORDER_COST_CATEGORIES.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className={styles.costDescription}>Mô tả chi phí<input required maxLength="200" value={costDraft.description} onChange={event=>setCostDraft(current=>({...current,description:event.target.value}))} placeholder="Ví dụ: túi zipper 500 g"/></label><label>Số lượng<FormattedNumberInput required min="0.001" step="0.001" value={costDraft.quantity} onChange={event=>setCostDraft(current=>({...current,quantity:event.target.value}))}/></label><label>Đơn giá<FormattedNumberInput required min="0" step="1000" value={costDraft.unitCost} onChange={event=>setCostDraft(current=>({...current,unitCost:event.target.value}))} placeholder="0 ₫"/></label><label>Trạng thái<select value={costDraft.paymentStatus} onChange={event=>setCostDraft(current=>({...current,paymentStatus:event.target.value}))}>{ORDER_COST_STATUSES.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Ngày<input type="date" required value={costDraft.incurredOn} onChange={event=>setCostDraft(current=>({...current,incurredOn:event.target.value}))}/></label><label className={styles.costNote}>Ghi chú<input value={costDraft.note} onChange={event=>setCostDraft(current=>({...current,note:event.target.value}))} placeholder="Nhà cung cấp hoặc điều cần nhớ"/></label><label className={styles.expenseToggle}><input type="checkbox" checked={costDraft.recordExpense} onChange={event=>setCostDraft(current=>({...current,recordExpense:event.target.checked}))}/><span><b>Đồng thời ghi vào Hộp chi phí</b><small>Bật khi khoản này thực sự cần theo dõi trong ngân sách. Hệ thống liên kết hai nơi để tránh nhập trùng.</small></span></label><div className={styles.costFormTotal}><span><small>Thành tiền</small><b>{money((Number(costDraft.quantity)||0)*(Number(costDraft.unitCost)||0))}</b></span><button disabled={costSaving||!costDraft.description.trim()||Number(costDraft.quantity)<=0||costDraft.unitCost===""}>{costSaving?"Đang lưu…":"Lưu chi phí"}</button></div></form>}
   {costs.length?<div className={styles.costRows}>{costs.map(cost=><article key={cost.id}><span><b>{cost.description}</b><small>{categoryLabel(cost.category)} · {cost.quantity} × {money(cost.unit_cost)} · {cost.source_type==="bom"?"tự động từ định mức":statusLabel(cost.payment_status)}{cost.expense_id?" · đã liên kết Hộp chi phí":""}</small></span><strong>{money(orderCostAmount(cost))}</strong>{cost.source_type==="bom"?<i>Tự động</i>:<button disabled={costSaving} onClick={()=>removeCost(cost)} aria-label={`Xóa chi phí ${cost.description}`} title="Xóa dòng chi phí này; khoản Hộp chi phí liên kết cũng được xóa nếu chưa phân loại."><Trash2/></button>}</article>)}</div>:!addingCost&&<p className={styles.eventEmpty}>Chưa có chi phí nào. Nếu đơn đã có định mức, bấm “Tính từ định mức”.</p>}
   <div className={styles.economics}><div><span>Doanh thu</span><b>{money(economics.revenue)}</b></div><div><span>Tổng chi phí</span><b>{money(economics.costTotal)}</b></div><div data-profit={economics.grossProfit!==null&&economics.grossProfit<0?"negative":"positive"}><span>Lãi gộp ước tính</span><b>{money(economics.grossProfit)}</b></div><div><span>Biên lãi bán hàng</span><b>{economics.marginPercent===null?"—":`${economics.marginPercent.toFixed(1)}%`}</b></div></div>
   {economics.marginPercent!==null&&<div className={styles.marginMeter} aria-label={`Biên lãi ${economics.marginPercent.toFixed(1)} phần trăm`}><i style={{width:`${Math.max(0,Math.min(100,economics.marginPercent))}%`}}/><span>{economics.marginPercent<0?"Đơn đang bán dưới giá vốn":economics.marginPercent<20?"Biên lãi mỏng":economics.marginPercent<40?"Biên lãi cần cân nhắc":"Biên lãi khỏe"}</span></div>}
  </section>
  <section className={styles.eventSection}><div className={styles.detailSectionTitle}><Activity/><span><b>Lịch sử đơn</b><small>Ai đã thay đổi điều gì và khi nào.</small></span></div>{loadingEvents?<p className={styles.eventEmpty}>Đang tải lịch sử…</p>:events.length?<ol>{events.map(event=><li key={event.id}><i/><div><p>{event.message}</p><small>{dateTime(event.created_at)}{event.actor?` · ${event.actor}`:""}</small></div></li>)}</ol>:<p className={styles.eventEmpty}>Chưa có thay đổi nào được ghi lại.</p>}</section>
 </aside>
}
