"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { Archive,ArrowRight,Calendar,ChevronRight,ClipboardList,LogOut,MessageSquare,PackageCheck,RefreshCw,Search,Send,Sprout,Users } from "lucide-react";
import { fromOrderRow,fromThreadRow } from "@/lib/mappers";
import styles from "./StaffWorkbench.module.css";

const STATUS={pending:"Chờ xác nhận",confirmed:"Đã xác nhận",shipped:"Đang giao",completed:"Hoàn tất"};
const NEXT={pending:"confirmed",confirmed:"shipped",shipped:"completed"};
const dateTime=(value)=>{const date=new Date(value);return !value||Number.isNaN(date.getTime())?"—":new Intl.DateTimeFormat("vi-VN",{dateStyle:"short",timeStyle:"short"}).format(date)};
const money=(value)=>value?new Intl.NumberFormat("vi-VN",{style:"currency",currency:"VND",maximumFractionDigits:0}).format(value):"Chưa báo giá";

export default function StaffWorkbench({supabase,email,role,onLogout}){
 const [orders,setOrders]=useState([]),[leads,setLeads]=useState([]),[samples,setSamples]=useState([]),[sessions,setSessions]=useState([]),[threads,setThreads]=useState([]),[customers,setCustomers]=useState([]),[selected,setSelected]=useState(null),[task,setTask]=useState(null),[activeThread,setActiveThread]=useState(null),[reply,setReply]=useState(""),[customer,setCustomer]=useState(null),[customerNote,setCustomerNote]=useState(""),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const [o,l,s,t,h,c]=await Promise.all([supabase.from("orders").select("*").order("ts",{ascending:false}),supabase.from("leads").select("*").order("ts",{ascending:false}),supabase.from("sample_requests").select("*").order("ts",{ascending:false}),supabase.from("tea_sessions").select("*").order("date",{ascending:true}),supabase.from("support_threads").select("*").order("created_at",{ascending:false}),supabase.rpc("customer_profiles_summary")]);const failed=[o,l,s,t,h,c].find(r=>r.error);if(failed)setError("Không tải được toàn bộ dữ liệu vận hành.");if(!o.error)setOrders((o.data||[]).map(fromOrderRow));if(!l.error)setLeads(l.data||[]);if(!s.error)setSamples(s.data||[]);if(!t.error)setSessions(t.data||[]);if(!h.error)setThreads((h.data||[]).map(fromThreadRow));if(!c.error)setCustomers(Array.isArray(c.data)?c.data:[]);setLoading(false)},[supabase]);
 useEffect(()=>{load()},[load]);
 const openOrders=orders.filter(o=>o.status!=="completed"),unreadOrders=openOrders.filter(o=>o.unread),newLeads=leads.filter(l=>l.unread),newSamples=samples.filter(s=>s.unread||s.status==="new"),pendingSessions=sessions.filter(s=>s.status==="pending"),unreadThreads=threads.filter(thread=>thread.unreadForAdmin&&thread.messages.length>0);
 const queue=useMemo(()=>[
  ...unreadThreads.map(thread=>({kind:"message",id:thread.id,ts:thread.messages.at(-1)?.ts,title:thread.customerName,detail:thread.messages.at(-1)?.text||"Tin nhắn mới",record:thread,priority:1})),
  ...unreadOrders.map(o=>({kind:"order",id:o.id,ts:o.ts,title:o.customerName,detail:`${o.type==="retail"?"Đơn lẻ":"Đơn sỉ"} · ${o.totalItems||o.totalKg||0} ${o.type==="retail"?"món":"kg"}`,record:o,priority:2})),
  ...newSamples.map(s=>({kind:"sample",id:s.id,ts:s.ts,title:s.store_name,detail:`Mẫu ${s.pack} · ${s.phone}`,record:s,priority:3})),
  ...newLeads.map(l=>({kind:"lead",id:l.id,ts:l.ts,title:l.business_name||l.name,detail:l.interest,record:l,priority:4})),
  ...pendingSessions.map(s=>({kind:"session",id:s.id,ts:`${s.date}T${s.session_time||"00:00"}`,title:s.customer_name,detail:`${s.date} · ${(s.session_time||"").slice(0,5)}`,record:s,priority:5})),
 ].sort((a,b)=>a.priority-b.priority||new Date(a.ts)-new Date(b.ts)),[unreadThreads,unreadOrders,newSamples,newLeads,pendingSessions]);
 const filtered=orders.filter(o=>`${o.id} ${o.customerName} ${o.contact}`.toLowerCase().includes(query.toLowerCase()));
 const selectOrder=async(order)=>{setTask(null);setSelected(order);if(order.unread){await supabase.from("orders").update({unread:false}).eq("id",order.id);setOrders(current=>current.map(o=>o.id===order.id?{...o,unread:false}:o))}};
 const openThread=async(thread)=>{setSelected(null);setTask(null);setCustomer(null);setActiveThread(thread);if(thread.unreadForAdmin){await supabase.from("support_threads").update({unread_for_admin:false}).eq("id",thread.id);const next={...thread,unreadForAdmin:false};setThreads(current=>current.map(item=>item.id===thread.id?next:item));setActiveThread(next)}};
 const openTask=(item)=>{if(item.kind==="order"){selectOrder(item.record);return}if(item.kind==="message"){openThread(item.record);return}setActiveThread(null);setCustomer(null);setSelected(null);setTask(item)};
 const advance=async(order)=>{const status=NEXT[order.status];if(!status)return;const {error:updateError}=await supabase.from("orders").update({status,unread:false}).eq("id",order.id);if(updateError){setError("Chưa cập nhật được trạng thái đơn.");return}const next={...order,status,unread:false};setOrders(current=>current.map(o=>o.id===order.id?next:o));setSelected(next)};
 const acknowledgeLead=async(lead)=>{const {error:updateError}=await supabase.from("leads").update({unread:false}).eq("id",lead.id);if(updateError){setError("Chưa cập nhật được lead.");return}setLeads(current=>current.map(item=>item.id===lead.id?{...item,unread:false}:item))};
 const sendSample=async(sample)=>{const {error:updateError}=await supabase.from("sample_requests").update({status:"sent",unread:false}).eq("id",sample.id);if(updateError){setError("Chưa cập nhật được mẫu thử.");return}setSamples(current=>current.map(item=>item.id===sample.id?{...item,status:"sent",unread:false}:item))};
 const confirmSession=async(session)=>{const {error:updateError}=await supabase.from("tea_sessions").update({status:"confirmed"}).eq("id",session.id);if(updateError){setError("Chưa xác nhận được lịch trà.");return}setSessions(current=>current.map(item=>item.id===session.id?{...item,status:"confirmed"}:item))};
 const sendReply=async(event)=>{event.preventDefault();if(!activeThread||!reply.trim())return;const nextMessages=[...activeThread.messages,{from:"admin",text:reply.trim(),ts:new Date().toISOString()}];const {error:updateError}=await supabase.from("support_threads").update({messages:nextMessages,unread_for_admin:false}).eq("id",activeThread.id);if(updateError){setError("Chưa gửi được phản hồi.");return}const next={...activeThread,messages:nextMessages,unreadForAdmin:false};setThreads(current=>current.map(item=>item.id===next.id?next:item));setActiveThread(next);setReply("")};
 const openCustomer=async(profile)=>{setSelected(null);setTask(null);setActiveThread(null);const {data,error:detailError}=await supabase.rpc("customer_detail",{p_contact:profile.contact});if(detailError){setError("Chưa tải được hồ sơ khách hàng.");return}setCustomer({...profile,detail:data});setCustomerNote(data?.note||"")};
 const saveCustomerNote=async()=>{if(!customer)return;const {error:noteError}=await supabase.rpc("save_customer_note",{p_contact:customer.contact,p_note:customerNote,p_by:email});if(noteError){setError("Chưa lưu được ghi chú khách hàng.");return}setCustomer(current=>({...current,detail:{...current.detail,note:customerNote}}))};
 const cards=[{label:"Cần xử lý",value:queue.length,icon:ClipboardList},{label:"Đơn đang mở",value:openOrders.length,icon:PackageCheck},{label:"Tin chưa đọc",value:unreadThreads.length,icon:MessageSquare},{label:"Lịch trà chờ",value:pendingSessions.length,icon:Calendar}];
 return <main className={styles.shell}>
  <aside className={styles.rail}><div className={styles.brand}><span>皇龍</span><b>HL</b></div><nav aria-label="Staff workspace"><a href="#queue" className={styles.active}><ClipboardList/><span>Điều phối</span>{queue.length>0&&<b>{queue.length}</b>}</a><a href="#orders"><PackageCheck/><span>Đơn hàng</span></a><a href="#messages"><MessageSquare/><span>Tin nhắn</span>{unreadThreads.length>0&&<b>{unreadThreads.length}</b>}</a><a href="#contacts"><Users/><span>Quan hệ</span></a><Link href="/admin/house"><Sprout/><span>Nhà & danh mục</span></Link><Link href="/admin/legacy"><Archive/><span>Hệ thống cũ</span></Link></nav><button onClick={onLogout} aria-label="Đăng xuất"><LogOut/><span>Đăng xuất</span></button></aside>
  <section className={styles.workspace}>
   <header className={styles.top}><div><p>Staff workbench</p><h1>Điều phối hôm nay</h1></div><div className={styles.identity}><span><b>{email}</b><small>{role}</small></span><button onClick={load} disabled={loading} aria-label="Làm mới"><RefreshCw className={loading?styles.spin:""}/></button></div></header>
   {error&&<p className={styles.error} role="alert">{error}</p>}
   <section className={styles.metrics}>{cards.map(({label,value,icon:Icon})=><article key={label}><Icon/><span>{label}</span><b>{loading?"—":value}</b></article>)}</section>
   <section className={styles.board} id="queue"><header><div><p>Hàng đợi chung</p><h2>Việc cần chạm vào</h2></div><span>{queue.length} mục</span></header>{loading?<div className={styles.skeleton}><i/><i/><i/></div>:queue.length?<div className={styles.queue}>{queue.slice(0,12).map(item=><button key={`${item.kind}-${item.id}`} onClick={()=>openTask(item)}><span className={styles.kind}>{item.kind}</span><span><b>{item.title}</b><small>{item.detail}</small></span><time>{dateTime(item.ts)}</time><ChevronRight/></button>)}</div>:<div className={styles.clear}><PackageCheck/><h3>Hàng đợi đã sạch.</h3><p>Không có đơn, mẫu, lead hoặc lịch trà mới đang chờ.</p></div>}</section>
   <section className={styles.orders} id="orders"><header><div><p>Order book</p><h2>Tất cả đơn hàng</h2></div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm tên, liên hệ, mã đơn"/></label></header><div className={styles.orderList}>{filtered.map(order=><button key={order.id} onClick={()=>selectOrder(order)} className={selected?.id===order.id?styles.selected:""}><span><b>{order.customerName}</b><small>{order.id} · {order.type}</small></span><span>{money(order.estimatedTotal)}</span><span data-status={order.status}>{STATUS[order.status]||order.status}</span><ChevronRight/></button>)}</div></section>
   <section className={styles.inbox} id="messages"><header><div><p>House inbox</p><h2>Đối thoại với khách</h2></div><span>{unreadThreads.length} chưa đọc</span></header><div className={styles.inboxGrid}><div className={styles.threadList}>{threads.length?threads.map(thread=><button key={thread.id} onClick={()=>openThread(thread)} className={activeThread?.id===thread.id?styles.selected:""}><span><b>{thread.customerName}</b><small>{thread.messages.at(-1)?.text||"Chưa có tin nhắn"}</small></span>{thread.unreadForAdmin&&<i>Mới</i>}</button>):<p>Chưa có cuộc trò chuyện.</p>}</div>{activeThread?<div className={styles.chat}><header><b>{activeThread.customerName}</b><small>{activeThread.role}</small></header><div>{activeThread.messages.map((message,index)=><article key={`${message.ts}-${index}`} data-from={message.from}><span>{message.text}</span><time>{dateTime(message.ts)}</time></article>)}</div><form onSubmit={sendReply}><textarea value={reply} onChange={event=>setReply(event.target.value)} placeholder="Viết phản hồi…"/><button disabled={!reply.trim()} aria-label="Gửi phản hồi"><Send/></button></form></div>:<div className={styles.noThread}><MessageSquare/><p>Chọn một cuộc trò chuyện để đọc và trả lời.</p></div>}</div></section>
   <section className={styles.relationships} id="contacts"><header><div><p>Relationship desk</p><h2>Lead, mẫu thử và lịch trà</h2></div><span>Hành động nhanh, không rời hàng đợi</span></header><div className={styles.relationshipGrid}>
    <article><header><Users/><span><b>Lead mới</b><small>{newLeads.length} cần liên hệ</small></span></header><div>{leads.slice(0,8).map(lead=><section key={lead.id}><span><b>{lead.business_name||lead.name}</b><small>{lead.contact} · {lead.interest}</small></span>{lead.unread?<button onClick={()=>acknowledgeLead(lead)}>Đã liên hệ</button>:<i>Đã nhận</i>}</section>)}</div></article>
    <article><header><PackageCheck/><span><b>Mẫu thử</b><small>{newSamples.length} đang chờ</small></span></header><div>{samples.slice(0,8).map(sample=><section key={sample.id}><span><b>{sample.store_name}</b><small>{sample.pack} · {sample.phone}</small></span>{sample.status==="new"?<button onClick={()=>sendSample(sample)}>Đã gửi</button>:<i>{sample.status}</i>}</section>)}</div></article>
    <article><header><Calendar/><span><b>Lịch trà</b><small>{pendingSessions.length} chờ xác nhận</small></span></header><div>{sessions.slice(0,8).map(session=><section key={session.id}><span><b>{session.customer_name}</b><small>{session.date} · {(session.session_time||"").slice(0,5)}</small></span>{session.status==="pending"?<button onClick={()=>confirmSession(session)}>Xác nhận</button>:<i>{session.status}</i>}</section>)}</div></article>
   </div></section>
   <section className={styles.customers}><header><div><p>Customer memory</p><h2>Lịch sử khách hàng</h2></div><span>{customers.length} hồ sơ</span></header><div>{customers.slice(0,20).map(profile=><button key={profile.contact_key} onClick={()=>openCustomer(profile)}><span><b>{profile.customer_name}</b><small>{profile.contact}</small></span><span>{profile.order_count} đơn</span><span>{money(profile.total_spent)}</span><ChevronRight/></button>)}</div></section>
  </section>
  {selected&&<aside className={styles.detail} aria-label="Chi tiết đơn hàng"><header><div><p>Order detail</p><h2>{selected.customerName}</h2></div><button onClick={()=>setSelected(null)} aria-label="Đóng">×</button></header><dl><div><dt>Mã đơn</dt><dd>{selected.id}</dd></div><div><dt>Liên hệ</dt><dd>{selected.contact}</dd></div><div><dt>Địa chỉ</dt><dd>{selected.address||"—"}</dd></div><div><dt>Thanh toán</dt><dd>{selected.paymentMethod==="cash"?"Tiền mặt":"Chuyển khoản QR"}</dd></div></dl><div className={styles.lines}>{selected.lines.map((line,i)=><div key={i}><span><b>{line.name?.vi||line.name?.en}</b><small>{line.qty} {line.unit}</small></span><span>{line.price?money(line.price*line.qty):"—"}</span></div>)}</div><div className={styles.detailTotal}><span>Tổng dự kiến</span><b>{money(selected.estimatedTotal)}</b></div>{NEXT[selected.status]?<button className={styles.advance} onClick={()=>advance(selected)}>{STATUS[NEXT[selected.status]]}<ArrowRight/></button>:<p className={styles.done}>Đơn đã hoàn tất.</p>}<Link href="/admin/legacy">Mở trong hệ thống đầy đủ <ArrowRight/></Link></aside>}
  {task&&<aside className={styles.detail} aria-label="Chi tiết việc cần xử lý"><header><div><p>{task.kind}</p><h2>{task.title}</h2></div><button onClick={()=>setTask(null)} aria-label="Đóng">×</button></header><dl><div><dt>Mã</dt><dd>{task.id}</dd></div><div><dt>Nhận lúc</dt><dd>{dateTime(task.ts)}</dd></div><div><dt>Chi tiết</dt><dd>{task.detail}</dd></div>{task.record.contact&&<div><dt>Liên hệ</dt><dd>{task.record.contact}</dd></div>}{task.record.phone&&<div><dt>Điện thoại</dt><dd>{task.record.phone}</dd></div>}{task.record.address&&<div><dt>Địa chỉ</dt><dd>{task.record.address}</dd></div>}{task.record.note&&<div><dt>Ghi chú</dt><dd>{task.record.note}</dd></div>}</dl><Link href="/admin/legacy">Xử lý trong hệ thống đầy đủ <ArrowRight/></Link></aside>}
  {customer&&<aside className={styles.detail} aria-label="Hồ sơ khách hàng"><header><div><p>Customer memory</p><h2>{customer.customer_name}</h2></div><button onClick={()=>setCustomer(null)} aria-label="Đóng">×</button></header><dl><div><dt>Liên hệ</dt><dd>{customer.contact}</dd></div><div><dt>Số đơn</dt><dd>{customer.order_count}</dd></div><div><dt>Tổng chi</dt><dd>{money(customer.total_spent)}</dd></div><div><dt>Đơn gần nhất</dt><dd>{dateTime(customer.last_order)}</dd></div></dl><div className={styles.history}><h3>Lịch sử đơn</h3>{(customer.detail?.history||[]).map(item=><div key={item.id}><span><b>{item.id}</b><small>{dateTime(item.ts)}</small></span><span>{money(item.total)}</span></div>)}</div><label className={styles.houseNote}>Ghi nhớ của Nhà<textarea value={customerNote} onChange={event=>setCustomerNote(event.target.value)} placeholder="Cách uống, nơi nhận, điều cần nhớ…"/></label><button className={styles.advance} onClick={saveCustomerNote}>Lưu ghi nhớ</button></aside>}
 </main>
}
