"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, BookOpen, Brain, BriefcaseBusiness, CircleCheck, Command, Home, MessageSquare, Network, PackageOpen, Search, Send, ShoppingBag, Users } from "lucide-react";
import { answerCommercialQuestion, deriveAttention, deriveCommercialJourney } from "@/lib/domain/commercial";
import styles from "./BrainConsole.module.css";

const sections = [
  { id: "home", label: "Brain", icon: Home }, { id: "relationships", label: "Relationships", icon: Network },
  { id: "knowledge", label: "Knowledge", icon: BookOpen }, { id: "work", label: "Work", icon: BriefcaseBusiness },
  { id: "ask", label: "Ask Hoàng Long", icon: Brain },
];
const fmtDate = value => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short" }).format(new Date(value)) : "—";

export default function BrainConsole({ initialData, staffEmail, loadWarning }) {
  const [section, setSection] = useState("home"); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(null);
  const journey = useMemo(() => deriveCommercialJourney(initialData), [initialData]);
  const attention = useMemo(() => deriveAttention(initialData), [initialData]);
  const ask = value => { const q = value || question; if (!q.trim()) return; setQuestion(q); setAnswer(answerCommercialQuestion(initialData, q)); setSection("ask"); };

  return <div className={styles.shell}><aside className={styles.sidebar}><button className={styles.brand} onClick={() => setSection("home")}><span>龍</span><div><strong>HOÀNG LONG</strong><small>INSTITUTIONAL BRAIN</small></div></button><nav>{sections.map(item => { const Icon = item.icon; return <button key={item.id} className={section === item.id ? styles.active : ""} onClick={() => setSection(item.id)}><Icon size={17}/>{item.label}</button> })}</nav><div className={styles.sideFoot}><Link href="/admin"><ShoppingBag size={15}/>Open Front Desk</Link><small>{staffEmail}</small></div></aside>
    <main className={styles.main}><header className={styles.mast}><span>House of Hoàng Long</span><span>Live Supabase workspace</span></header>{loadWarning && <div className={styles.warning}>Some records could not be read: {loadWarning}</div>}
      {section === "home" && <div className={styles.page}><section className={styles.brief}><div><span className={styles.eyebrow}>Live house briefing</span><h1>What needs judgment now.</h1><p>The Brain is reading commerce records directly. It does not change them.</p></div><button onClick={() => ask("What should I prioritize today?")}>Ask for a reading <ArrowRight size={15}/></button></section><section className={styles.attention}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>Attention ledger</span><h2>Unresolved signals</h2></div><b>{attention.length}</b></div>{attention.length ? attention.map((item,index) => <article key={`${item.type}-${item.id}`}><span>0{index+1}</span><div><small>{item.type} · {fmtDate(item.date)}</small><h3>{item.title}</h3></div><CircleCheck size={17}/></article>) : <div className={styles.empty}>No unread or pending records.</div>}</section><div className={styles.signalGrid}><article><PackageOpen/><span className={styles.eyebrow}>Orders</span><strong>{initialData.orders.filter(o => o.status === "pending").length}</strong><p>pending confirmation</p></article><article><Send/><span className={styles.eyebrow}>Samples</span><strong>{initialData.samples.filter(s => s.status === "new").length}</strong><p>new requests</p></article><article><MessageSquare/><span className={styles.eyebrow}>Voice</span><strong>{initialData.threads.filter(t => t.unread_for_admin).length}</strong><p>unread conversations</p></article><article><Users/><span className={styles.eyebrow}>Relationships</span><strong>{initialData.notes.length}</strong><p>durable customer notes</p></article></div></div>}
      {section === "relationships" && <div className={styles.page}><div className={styles.pageHead}><span className={styles.eyebrow}>Commercial memory</span><h1>Relationships</h1><p>Leads, samples, and orders shown as one continuous journey.</p></div><div className={styles.journey}>{journey.map(row => <article key={`${row.stage}-${row.id}`}><span>{row.stage}</span><h3>{row.name}</h3><small>{row.source} · {fmtDate(row.at)}</small><p>{row.next}</p></article>)}</div></div>}
      {section === "knowledge" && <div className={styles.page}><div className={styles.pageHead}><span className={styles.eyebrow}>Evidence before certainty</span><h1>Knowledge</h1><p>The first live sources are customer notes, product records, vendors, and conversations.</p></div><div className={styles.knowledgeList}>{initialData.notes.map(note => <article key={note.contact_key}><span>OBSERVATION</span><div><h3>Customer memory · {note.contact_key}</h3><p>{note.note || "Empty note"}</p><small>Updated {fmtDate(note.updated_at)} · {note.updated_by || "House staff"}</small></div></article>)}{initialData.notes.length === 0 && <div className={styles.empty}>Customer notes will appear here as observations.</div>}</div></div>}
      {section === "work" && <div className={styles.page}><div className={styles.pageHead}><span className={styles.eyebrow}>Operational bridge</span><h1>Work</h1><p>Open Front Desk to change records; the Brain keeps the priorities visible.</p></div><div className={styles.workGrid}><section><h2>Orders to confirm</h2>{initialData.orders.filter(o => o.status === "pending").map(o => <article key={o.id}><strong>{o.customer_name}</strong><span>{o.id}</span></article>)}</section><section><h2>Samples to qualify</h2>{initialData.samples.filter(s => s.status === "new").map(s => <article key={s.id}><strong>{s.store_name}</strong><span>{s.pack}</span></article>)}</section><section><h2>Messages to answer</h2>{initialData.threads.filter(t => t.unread_for_admin).map(t => <article key={t.id}><strong>{t.customer_name}</strong><span>{t.messages?.length || 0} messages</span></article>)}</section></div><Link className={styles.frontDeskButton} href="/admin">Continue in Front Desk <ArrowRight size={15}/></Link></div>}
      {section === "ask" && <div className={`${styles.page} ${styles.askPage}`}><div className={styles.askHead}><Brain/><span className={styles.eyebrow}>Decision support</span><h1>Ask Hoàng Long</h1><p>Answers are prioritized from the live records this staff account can access.</p></div><div className={styles.suggestions}>{["What should I prioritize today?","Which samples need action?","Which customer relationships need attention?"].map(q => <button key={q} onClick={() => ask(q)}>{q}<ArrowRight size={13}/></button>)}</div><form className={styles.askBox} onSubmit={e => {e.preventDefault();ask();}}><Command/><input value={question} onChange={e => setQuestion(e.target.value)} placeholder="Ask across orders, samples, leads, and messages…"/><button aria-label="Ask"><Search/></button></form>{answer && <section className={styles.answer}><h2>{answer.summary}</h2>{answer.actions.map((action,index) => <article key={action[0]}><span>0{index+1}</span><div><h3>{action[0]}</h3><p>{action[1]}</p><small>Evidence · {action[2]}</small></div></article>)}</section>}</div>}
    </main></div>;
}
