export const STR = {
  en: {
    welcome: "Welcome to the House of Hoàng Long",
    viewingAs: "Viewing as",
    search: "Search Our Story…",
    librarySearch: "Search the Library…",
    libraryChooseSection: "A general reference on tea — separate from our own story.",
    galleryTab: "Gallery",
    readingTab: "Reading",
    emptyGallery: "No photos yet — check back soon.",
    captionPh: "Caption (optional)",
    addPhoto: "Add photo",
    addArticle: "Add article",
    addToSection: "Add to this section",
    chooseSection: "Choose a section — ordered by what visitors usually want to know first.",
    allSections: "All sections",
    back: "Back",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    save: "Save article",
    titlePh: "Article title",
    bodyPh: "Content…",
    loading: "Loading…",
    noResults: "No results found.",
    noArticles: "No articles in this section yet.",
    results: (n, q) => `${n} results for "${q}"`,
    articleCount: (n) => `${n} sections`,
    comingSoon: "Coming soon",
    tradeIntro: "Volume pricing for our Everyday line, sold by the kilogram.",
    tradeQuoteNote: "This summary is a starting point, not a formal quotation — final pricing is confirmed by our team using our standard quotation template.",
    shopTitle: "Tea Shop",
    shopBody: "A retail ordering flow is next on the roadmap — small-batch purchases for individual tea lovers.",
    orderTitle: "Build an Order",
    orderHint: "Enter quantities in kilograms for the products you need.",
    kg: "kg",
    totalKg: "Total volume",
    tierApplied: "Tier applied",
    summaryTitle: "Order Summary",
    emptyCart: "Add a quantity to at least one product to see your order summary.",
    copySummary: "Copy order summary",
    copied: "Copied",
    priceRef: "Reference pricing tiers",
    yourName: "Your name",
    yourContact: "Phone or email",
    yourAddress: "Delivery address",
    taxNumber: "Tax number (optional)",
    vatNote: "10% VAT applies to retail orders and will be added to the final invoice.",
    orderNote: "Got a question or something to add? Comments, changes, anything…",
    submitOrder: "Submit order",
    orderSent: "Order received — thank you! We'll confirm final pricing shortly.",
    emailFallback: "Email this order",
    nameRequired: "Please enter your name and contact so we can reach you.",
    frontDeskOrders: "Orders",
    frontDeskMessages: "Messages",
    noOrdersYet: "No orders yet.",
    noThreadsYet: "No conversations yet.",
    markRead: "Mark as read",
    newBadge: "New",
    contactLabel: "Contact",
    noteLabel: "Note",
    chatTitle: "Talk to the House",
    chatIntro: "Have a question? Message our team directly.",
    chatNamePh: "Your name",
    chatMsgPh: "Type a message…",
    chatSend: "Send",
    chatStart: "Start conversation",
    chatEmpty: "No messages yet — say hello.",
    replyPh: "Type a reply…",
    you: "You",
    admin: "House of Hoàng Long",
    pcs: "pack(s)",
    shopHint: "Enter the quantity of packs you'd like for each tea.",
    itemsTotal: "Items",
    onboardSkip: "Skip",
    onboardStepOf: (n, total) => `Step ${n} of ${total}`,
    onboardWelcomeTitle: "Welcome to the House",
    onboardWelcomeBody: "A family tea house since 1995, working ancient Hà Giang leaf through Japanese processing craft.",
    onboardOfferTitle: "What we offer",
    onboardOriginTitle: "Origin & Craft",
    onboardOriginBody: "Wild ancient tea trees from Hoàng Su Phì, steamed using Japanese technology.",
    onboardLibraryTitle: "The Tea Library",
    onboardLibraryBody: "Everyday café-grade teas and a small Reserve line for connoisseurs.",
    onboardInfoTitle: "Tell us about you",
    onboardInterestLabel: "I'm interested in",
    onboardWholesale: "Wholesale",
    onboardRetail: "Retail",
    onboardNamePh: "Your name",
    onboardContactPh: "Phone or email",
    onboardCTA: "Get Started",
    leadRequired: "Please enter your name and contact to continue.",
    frontDeskLeads: "Leads",
    noLeadsYet: "No leads yet.",
    interestedIn: "Interested in",
    trackOrder: "Track an order",
    trackOrderHint: "Enter your Order ID to check its status.",
    orderIdPh: "Order ID",
    lookupBtn: "Check status",
    orderNotFound: "No order found with that ID.",
    yourOrderId: "Your Order ID",
    orderIdSaveNote: "Save this ID to check your order status later.",
    paymentTitle: "Payment",
    paymentHint: "Complete payment by bank transfer using the details below.",
    paymentPending: "Bank transfer details will be confirmed by our team shortly.",
    paymentSettingsTitle: "Payment Settings",
    selectBank: "Select your bank",
    accountNumberLabel: "Account number",
    accountNameLabel: "Account holder name",
    saveSettings: "Save",
    savedNote: "Saved",
    transferContent: "Transfer content",
    frontDeskPayment: "Payment",
    orderStatusLabel: "Status",
    exportCsv: "Export CSV",
    catalogTitle: "Catalog",
    productNameEnPh: "Name (English)",
    productNameViPh: "Name (Vietnamese)",
    lineLabel: "Line",
    everydayOption: "Everyday (kg, wholesale-eligible)",
    reserveOption: "Reserve (pack, retail-only)",
    addProduct: "Add tea",
    saveProduct: "Save",
    deleteProduct: "Remove",
    reviewsTitle: "Reviews",
    reviewerNamePh: "Customer name",
    reviewQuotePh: "What they said…",
    addReview: "Add review",
    noReviewsYetAdmin: "No reviews added yet.",
    testimonialsHeading: "What our customers say",
    reorderTitle: "Ordered before?",
    reorderHint: "Enter your phone or email to load your last order.",
    reorderContactPh: "Phone or email",
    reorderBtn: "Load last order",
    reorderNotFound: "No previous order found for that contact.",
    reorderApplied: "Loaded your last order — review and submit again below.",
    printInvoice: "Print invoice",
    promoLabel: "Promo code",
    promoCodePh: "Enter promo code",
    applyPromo: "Apply",
    promoApplied: (code, pct) => `Applied: ${code} (-${pct}%)`,
    promoInvalid: "That code isn't valid or active.",
    promosTitle: "Promo codes",
    promoCodeFieldPh: "Code (e.g. TET10)",
    promoPercentPh: "Discount %",
    addPromo: "Add code",
    activate: "Activate",
    deactivate: "Deactivate",
    noPromosYet: "No promo codes yet.",
    affiliateNamePh: "Employee/affiliate name (optional)",
    usedCount: (n) => `Used ${n} time${n === 1 ? "" : "s"}`,
    tastingNotesEnPh: "Tasting notes, English (optional)",
    tastingNotesViPh: "Tasting notes, Vietnamese (optional)",
    brewEnPh: "Brew guide, English",
    brewViPh: "Brew guide, Vietnamese",
    packSizePh: "Pack size (e.g. 100g, 250g) — optional",
    photoUrlPh: "Photo URL (optional)",
    uploadPhotoLabel: "Or upload a photo",
    centerImageLabel: "Adjust image center (crop position)",
    pricePh: "Price in VND (optional)",
    sampleOption: "Sample Packs",
    estimatedTotal: "Estimated total (priced items)",
    priceNote: "Other items are priced separately by our team.",
    stockHaGiangPh: "Stock in Tuyên Quang (Hà Giang) warehouse",
    stockSocSonPh: "Stock in Sóc Sơn warehouse",
    batchPh: "Batch (optional, e.g. Batch #2025-11)",
    warehouseHaGiang: "Tuyên Quang (Hà Giang)",
    warehouseSocSon: "Sóc Sơn",
    batchLabel: "Batch",
    stockLeft: (n) => `${n} left`,
    lastFew: "Only a few left!",
    fromPrice: (v) => `From ${v}`,
    chooseWeight: "Choose a size",
    limitedBadge: "Limited",
    shareExperienceTitle: "Share your experience",
    yourReviewNamePh: "Your name",
    yourReviewQuotePh: "Tell us what you thought…",
    submitReview: "Submit review",
    reviewSubmittedNote: "Thanks! Your review will appear after our team takes a quick look.",
    pendingApproval: "Pending approval",
    approve: "Approve",
    cartBarItems: (n) => `${n} item${n === 1 ? "" : "s"}`,
    viewOrder: "View order",
    cartTitle: "Your Order",
    proceedToCheckout: "Proceed to checkout",
    yieldGuideTitle: "How Far Does 1kg Go?",
    replaySeal: "Replay",
    yieldGuideHint: "A general guide — actual yield depends on your steeping strength and recipe.",
    yieldLight: "Light (iced tea)",
    yieldStandard: "Standard",
    yieldConcentrate: "Concentrated (milk tea / cold brew base)",
    litersLabel: "liters",
    cupsApprox: (min, max) => `≈ ${min}–${max} cups (200–350ml)`,
    costPerLiterFrom: (v) => `from ${v} / liter`,
    paymentMethodLabel: "Payment method",
    payByQR: "Bank transfer (QR)",
    payByCash: "Cash",
    cashLockedNote: "First-time orders are paid by bank transfer. Cash becomes available after your first completed order.",
    cashConfirmedNote: "You've chosen to pay by cash. Please have the exact amount ready, or confirm payment details with our team.",
    missingDetailsHint: "No tasting notes or photo yet",
    addToOrder: "Add to order",
    addedToOrder: "Added",
    viewDetails: "Tap for details",
    quantityLabel: "Quantity",
    wholesaleGateTitle: "Registered Partners Only",
    wholesaleGateHint: "Enter your registered partner ID to view wholesale pricing and place an order.",
    partnerIdPh: "Partner ID",
    verifyBtn: "Verify",
    notRegisteredYet: "Not registered yet?",
    requestAccess: "Request wholesale access",
    invalidPartnerId: "That ID isn't registered. Please check and try again, or request access below.",
    wholesaleAccountsTitle: "Wholesale Partners",
    businessNamePh: "Business / shop name",
    partnerCodePh: "Partner ID (e.g. WS-001)",
    addPartner: "Add partner",
    noPartnersYet: "No registered partners yet.",
    trackingCodeLabel: "Tracking code",
    trackingCodePh: "Enter tracking code",
    saveTracking: "Save",
    noTrackingYet: "No tracking code yet",
    testPackName: { en: "New Batch Test Pack (Free)", vi: "Gói Thử Mẻ Mới (Miễn phí)" },
    testPackOfferTitle: "New Batch Test Pack",
    testPackOfferHint: "As a returning partner, add a free sample of our newest batch to this order.",
    testPackCheckbox: "Add free test pack to this order",
    consentLabel: "I agree that House of Hoàng Long may store this information to process my request.",
    consentRequired: "Please confirm consent to continue.",
    statsWeekTitle: "This week",
    statsOrders: "Orders",
    statsWholesaleVolume: "Wholesale volume",
    statsLeads: "New leads",
    statsMessages: "Customer messages",
    outOfStock: "Out of stock",
    markAvailable: "Mark available",
    markOutOfStock: "Mark out of stock",
    loginTitle: "Internal Sign In",
    loginEmailPh: "Email",
    loginPasswordPh: "Password",
    loginBtn: "Sign in",
    loginError: "Incorrect email or password.",
    loginNotStaff: "This account doesn't have internal access yet. Contact an administrator.",
    logout: "Sign out",
    signedInAs: "Signed in as",
    orderFailed: "Something changed (likely stock) — please review your order and try again.",
  },
  vi: {
    welcome: "Chào mừng đến Nhà Hoàng Long",
    viewingAs: "Đang xem với vai trò",
    search: "Tìm trong Câu chuyện…",
    librarySearch: "Tìm trong Thư Viện…",
    libraryChooseSection: "Kiến thức trà nói chung — tách biệt với câu chuyện thương hiệu của nhà.",
    galleryTab: "Ảnh",
    readingTab: "Đọc thêm",
    emptyGallery: "Chưa có ảnh nào — quay lại sau nhé.",
    captionPh: "Chú thích (không bắt buộc)",
    addPhoto: "Thêm ảnh",
    addArticle: "Thêm bài",
    addToSection: "Thêm bài vào mục này",
    chooseSection: "Chọn một chuyên mục — sắp xếp theo thứ tự thường được khách quan tâm trước.",
    allSections: "Tất cả chuyên mục",
    back: "Quay lại",
    cancel: "Huỷ",
    edit: "Sửa",
    delete: "Xoá",
    save: "Lưu bài viết",
    titlePh: "Tiêu đề bài viết",
    bodyPh: "Nội dung…",
    loading: "Đang tải…",
    noResults: "Không tìm thấy kết quả nào.",
    noArticles: "Chưa có bài viết trong mục này.",
    results: (n, q) => `${n} kết quả cho "${q}"`,
    articleCount: (n) => `${n} chuyên mục`,
    comingSoon: "Sắp ra mắt",
    tradeIntro: "Bậc giá theo sản lượng cho dòng Pha Chế, bán theo kg.",
    tradeQuoteNote: "Đây là bản tóm tắt sơ bộ, chưa phải báo giá chính thức — giá cuối cùng sẽ được đội ngũ xác nhận theo mẫu quotation chuẩn.",
    shopTitle: "Cửa hàng lẻ",
    shopBody: "Luồng đặt hàng lẻ đang trong kế hoạch tiếp theo — mua số lượng nhỏ cho khách yêu trà cá nhân.",
    orderTitle: "Tạo đơn hàng",
    orderHint: "Nhập số lượng (kg) cho các sản phẩm cần đặt.",
    kg: "kg",
    totalKg: "Tổng sản lượng",
    tierApplied: "Bậc giá áp dụng",
    summaryTitle: "Tóm tắt đơn hàng",
    emptyCart: "Nhập số lượng ít nhất một sản phẩm để xem tóm tắt đơn hàng.",
    copySummary: "Sao chép đơn hàng",
    copied: "Đã sao chép",
    priceRef: "Bảng giá tham khảo",
    yourName: "Tên của bạn",
    yourContact: "Số điện thoại hoặc email",
    yourAddress: "Địa chỉ giao hàng",
    taxNumber: "Mã số thuế (không bắt buộc)",
    vatNote: "Đơn lẻ áp dụng VAT 10%, sẽ được cộng vào hoá đơn cuối cùng.",
    orderNote: "Bạn có thắc mắc gì không? Bình luận, thay đổi, hay câu hỏi...?",
    submitOrder: "Gửi đơn hàng",
    orderSent: "Đã nhận đơn — cảm ơn a/chị! Bên em sẽ xác nhận giá cuối cùng sớm.",
    emailFallback: "Gửi đơn qua email",
    nameRequired: "Vui lòng nhập tên và số liên hệ để bên em liên lạc lại.",
    frontDeskOrders: "Đơn hàng",
    frontDeskMessages: "Tin nhắn",
    noOrdersYet: "Chưa có đơn hàng nào.",
    noThreadsYet: "Chưa có cuộc trò chuyện nào.",
    markRead: "Đánh dấu đã đọc",
    newBadge: "Mới",
    contactLabel: "Liên hệ",
    noteLabel: "Ghi chú",
    chatTitle: "Trò chuyện với Nhà Hoàng Long",
    chatIntro: "Có câu hỏi? Nhắn trực tiếp cho đội ngũ hỗ trợ.",
    chatNamePh: "Tên của bạn",
    chatMsgPh: "Nhập tin nhắn…",
    chatSend: "Gửi",
    chatStart: "Bắt đầu trò chuyện",
    chatEmpty: "Chưa có tin nhắn nào — chào một câu nhé.",
    replyPh: "Nhập phản hồi…",
    you: "Bạn",
    admin: "Nhà Hoàng Long",
    pcs: "gói",
    shopHint: "Nhập số lượng gói muốn mua cho mỗi loại trà.",
    itemsTotal: "Số món",
    onboardSkip: "Bỏ qua",
    onboardStepOf: (n, total) => `Bước ${n}/${total}`,
    onboardWelcomeTitle: "Chào mừng đến Nhà Hoàng Long",
    onboardWelcomeBody: "Thương hiệu trà gia đình từ 1995, làm trà cổ thụ Hà Giang bằng công nghệ Nhật Bản.",
    onboardOfferTitle: "Chúng tôi có gì",
    onboardOriginTitle: "Nguồn gốc & Công nghệ",
    onboardOriginBody: "Trà cổ thụ mọc tự nhiên tại Hoàng Su Phì, chế biến bằng công nghệ hấp Nhật Bản.",
    onboardLibraryTitle: "Trà & Sản phẩm",
    onboardLibraryBody: "Dòng Pha Chế dùng hàng ngày và dòng Thưởng cao cấp cho người sành trà.",
    onboardInfoTitle: "Cho em biết về a/chị",
    onboardInterestLabel: "Quan tâm đến",
    onboardWholesale: "Mua sỉ",
    onboardRetail: "Mua lẻ",
    onboardNamePh: "Tên của bạn",
    onboardContactPh: "Số điện thoại hoặc email",
    onboardCTA: "Bắt đầu",
    leadRequired: "Vui lòng nhập tên và liên hệ để tiếp tục.",
    frontDeskLeads: "Khách tiềm năng",
    noLeadsYet: "Chưa có khách tiềm năng nào.",
    interestedIn: "Quan tâm đến",
    trackOrder: "Theo dõi đơn hàng",
    trackOrderHint: "Nhập mã đơn hàng để kiểm tra trạng thái.",
    orderIdPh: "Mã đơn hàng",
    lookupBtn: "Kiểm tra",
    orderNotFound: "Không tìm thấy đơn hàng với mã này.",
    yourOrderId: "Mã đơn hàng của a/chị",
    orderIdSaveNote: "Lưu lại mã này để kiểm tra trạng thái đơn sau.",
    paymentTitle: "Thanh toán",
    paymentHint: "Hoàn tất thanh toán bằng chuyển khoản theo thông tin bên dưới.",
    paymentPending: "Thông tin chuyển khoản sẽ được đội ngũ xác nhận sớm.",
    paymentSettingsTitle: "Cài đặt thanh toán",
    selectBank: "Chọn ngân hàng",
    accountNumberLabel: "Số tài khoản",
    accountNameLabel: "Tên chủ tài khoản",
    saveSettings: "Lưu",
    savedNote: "Đã lưu",
    transferContent: "Nội dung chuyển khoản",
    frontDeskPayment: "Thanh toán",
    orderStatusLabel: "Trạng thái",
    exportCsv: "Xuất CSV",
    catalogTitle: "Sản phẩm",
    productNameEnPh: "Tên (tiếng Anh)",
    productNameViPh: "Tên (tiếng Việt)",
    lineLabel: "Dòng",
    everydayOption: "Pha Chế (kg, áp dụng giá sỉ)",
    reserveOption: "Thưởng (gói, chỉ bán lẻ)",
    addProduct: "Thêm loại trà",
    saveProduct: "Lưu",
    deleteProduct: "Xoá",
    reviewsTitle: "Đánh giá",
    reviewerNamePh: "Tên khách hàng",
    reviewQuotePh: "Khách nói gì…",
    addReview: "Thêm đánh giá",
    noReviewsYetAdmin: "Chưa có đánh giá nào.",
    testimonialsHeading: "Khách hàng nói gì về chúng tôi",
    reorderTitle: "Đã từng đặt hàng?",
    reorderHint: "Nhập số điện thoại/email để tải lại đơn gần nhất.",
    reorderContactPh: "Số điện thoại hoặc email",
    reorderBtn: "Tải đơn gần nhất",
    reorderNotFound: "Không tìm thấy đơn hàng trước đó với liên hệ này.",
    reorderApplied: "Đã tải đơn gần nhất — xem lại và gửi lại bên dưới.",
    printInvoice: "In hoá đơn",
    promoLabel: "Mã giảm giá",
    promoCodePh: "Nhập mã giảm giá",
    applyPromo: "Áp dụng",
    promoApplied: (code, pct) => `Đã áp dụng: ${code} (-${pct}%)`,
    promoInvalid: "Mã không hợp lệ hoặc đã hết hạn.",
    promosTitle: "Mã giảm giá",
    promoCodeFieldPh: "Mã (vd: TET10)",
    promoPercentPh: "% giảm",
    addPromo: "Thêm mã",
    activate: "Kích hoạt",
    deactivate: "Tắt",
    noPromosYet: "Chưa có mã giảm giá nào.",
    affiliateNamePh: "Tên nhân viên/affiliate (không bắt buộc)",
    usedCount: (n) => `Đã dùng ${n} lần`,
    tastingNotesEnPh: "Vị/hương vị, tiếng Anh (không bắt buộc)",
    tastingNotesViPh: "Vị/hương vị, tiếng Việt (không bắt buộc)",
    brewEnPh: "Gợi ý pha, tiếng Anh",
    brewViPh: "Gợi ý pha, tiếng Việt",
    packSizePh: "Quy cách đóng gói (vd: 100g, 250g) — không bắt buộc",
    photoUrlPh: "Link ảnh (không bắt buộc)",
    uploadPhotoLabel: "Hoặc upload ảnh trực tiếp",
    centerImageLabel: "Chỉnh tâm ảnh (vị trí crop)",
    pricePh: "Giá (VNĐ, không bắt buộc)",
    sampleOption: "Gói Dùng Thử",
    estimatedTotal: "Tạm tính (sản phẩm đã niêm yết giá)",
    priceNote: "Các sản phẩm khác sẽ được đội ngũ báo giá riêng.",
    stockHaGiangPh: "Tồn kho tại kho Tuyên Quang (Hà Giang)",
    stockSocSonPh: "Tồn kho tại kho Sóc Sơn",
    batchPh: "Mẻ/Batch (không bắt buộc, vd: Mẻ #2025-11)",
    warehouseHaGiang: "Tuyên Quang (Hà Giang)",
    warehouseSocSon: "Sóc Sơn",
    batchLabel: "Mẻ",
    stockLeft: (n) => `Còn ${n}`,
    lastFew: "Sắp hết hàng!",
    fromPrice: (v) => `Từ ${v}`,
    chooseWeight: "Chọn trọng lượng",
    limitedBadge: "Giới hạn",
    shareExperienceTitle: "Chia sẻ trải nghiệm của bạn",
    yourReviewNamePh: "Tên của bạn",
    yourReviewQuotePh: "Bạn thấy trà thế nào…",
    submitReview: "Gửi đánh giá",
    reviewSubmittedNote: "Cảm ơn a/chị! Đánh giá sẽ hiện sau khi đội ngũ xem qua.",
    pendingApproval: "Chờ duyệt",
    approve: "Duyệt",
    cartBarItems: (n) => `${n} món`,
    viewOrder: "Xem đơn hàng",
    cartTitle: "Đơn hàng của bạn",
    proceedToCheckout: "Tới thanh toán",
    yieldGuideTitle: "1kg Trà Pha Được Bao Nhiêu Lít?",
    replaySeal: "Xem lại",
    yieldGuideHint: "Ước tính chung — hiệu suất thực tế tuỳ độ đậm nhạt và công thức pha của quán.",
    yieldLight: "Nhạt (trà đá)",
    yieldStandard: "Chuẩn",
    yieldConcentrate: "Đậm (nền trà sữa/cold brew)",
    litersLabel: "lít",
    cupsApprox: (min, max) => `≈ ${min}–${max} cốc (200–350ml)`,
    costPerLiterFrom: (v) => `từ ${v} / lít`,
    paymentMethodLabel: "Phương thức thanh toán",
    payByQR: "Chuyển khoản (QR)",
    payByCash: "Tiền mặt",
    cashLockedNote: "Đơn đầu tiên cần thanh toán qua chuyển khoản. Tiền mặt sẽ mở khoá sau khi a/chị hoàn tất đơn đầu tiên.",
    cashConfirmedNote: "A/chị đã chọn thanh toán tiền mặt. Vui lòng chuẩn bị đúng số tiền, hoặc xác nhận lại với đội ngũ.",
    missingDetailsHint: "Chưa có vị/hương vị hoặc ảnh",
    addToOrder: "Thêm vào đơn",
    addedToOrder: "Đã thêm",
    viewDetails: "Bấm để xem chi tiết",
    quantityLabel: "Số lượng",
    wholesaleGateTitle: "Chỉ dành cho đối tác đã đăng ký",
    wholesaleGateHint: "Nhập mã đối tác đã đăng ký để xem giá sỉ và đặt hàng.",
    partnerIdPh: "Mã đối tác",
    verifyBtn: "Xác nhận",
    notRegisteredYet: "Chưa đăng ký?",
    requestAccess: "Yêu cầu đăng ký làm đối tác sỉ",
    invalidPartnerId: "Mã này chưa được đăng ký. Kiểm tra lại hoặc yêu cầu đăng ký bên dưới.",
    wholesaleAccountsTitle: "Đối tác sỉ",
    businessNamePh: "Tên doanh nghiệp/cửa hàng",
    partnerCodePh: "Mã đối tác (vd: WS-001)",
    addPartner: "Thêm đối tác",
    noPartnersYet: "Chưa có đối tác nào đăng ký.",
    trackingCodeLabel: "Mã vận đơn",
    trackingCodePh: "Nhập mã vận đơn",
    saveTracking: "Lưu",
    noTrackingYet: "Chưa có mã vận đơn",
    testPackName: { en: "New Batch Test Pack (Free)", vi: "Gói Thử Mẻ Mới (Miễn phí)" },
    testPackOfferTitle: "Gói Thử Mẻ Mới",
    testPackOfferHint: "Vì là đối tác đã từng đặt hàng, a/chị có thể thêm mẫu miễn phí từ mẻ trà mới nhất vào đơn này.",
    testPackCheckbox: "Thêm gói thử miễn phí vào đơn này",
    consentLabel: "Tôi đồng ý để Nhà Hoàng Long lưu thông tin này để xử lý yêu cầu.",
    consentRequired: "Vui lòng xác nhận đồng ý để tiếp tục.",
    statsWeekTitle: "Tuần này",
    statsOrders: "Đơn hàng",
    statsWholesaleVolume: "Sản lượng sỉ",
    statsLeads: "Lead mới",
    statsMessages: "Tin nhắn khách",
    outOfStock: "Hết hàng",
    markAvailable: "Đánh dấu còn hàng",
    markOutOfStock: "Đánh dấu hết hàng",
    loginTitle: "Đăng nhập Nội bộ",
    loginEmailPh: "Email",
    loginPasswordPh: "Mật khẩu",
    loginBtn: "Đăng nhập",
    loginError: "Sai email hoặc mật khẩu.",
    loginNotStaff: "Tài khoản này chưa được cấp quyền nội bộ. Liên hệ quản trị viên.",
    logout: "Đăng xuất",
    signedInAs: "Đăng nhập với",
    orderFailed: "Có gì đó vừa thay đổi (có thể do tồn kho) — vui lòng kiểm tra lại đơn và thử lại.",
  },
};
