export const STR = {
  en: {
    welcome: "Welcome to the House of Hoàng Long",
    search: "Search Our Story…",
    librarySearch: "Search the Library…",
    libraryChooseSection: "A general reference on tea — separate from our own story.",
    galleryTab: "Gallery",
    readingTab: "Reading",
    emptyGallery: "No photos yet — check back soon.",
    captionPh: "Caption (optional)",
    addPhoto: "Add photo",
    addArticle: "Add article",
    addToSection: "Add to this section",
    chooseSection: "Choose a section — ordered by what visitors usually want to know first.",
    stillHaveQuestions: "Still have questions? Call",
    teaOfDayLabel: "Tea of the day",
    // Home page movement markers
    remove: "Remove",
    // Dashboard — overview + customers
    overviewTab: "Overview",
    customersTab: "Customers",
    dashBack: "Dashboard",
    telegramTestTitle: "Telegram alerts",
    telegramTestHint: "Sends a test message to the House chat. If it doesn't arrive, the reply below says which part is wrong.",
    telegramTestSend: "Send a test message",
    telegramTestOk: "Sent. Check the chat — if it's there, new orders will arrive the same way.",
    telegramTestMissing: (names) => `Not set up in production yet: ${names}. Add them in Vercel › Settings › Environment Variables, then redeploy.`,
    telegramTestUnauthorised: "Sign in as staff first.",
    // Telegram's own wording, verbatim: "Unauthorized" means the token, "chat not found"
    // means the chat id, "bot was kicked" means the bot isn't in the group.
    telegramTestFailed: (why) => `Telegram refused it: ${why}`,
    telegramConfigured: "TELEGRAM_CHAT_ID is currently set to",
    telegramChatsTitle: "Chats this bot has heard from",
    telegramChatsEmpty: "None. Send the bot a message in Telegram, then press the button again — it can only find a chat that has spoken to it in the last 24 hours. In a group, send /start@yourbot; ordinary group messages are hidden from bots by default.",
    // Group headings name the moment you'd open the group, not the kind of data in it.
    dashGroup: (id) => ({
      today: "Today", people: "People", shop: "The shop", house: "House & records",
    }[id] || id),
    statVisitors: "Visitors",
    statViews: "Page views",
    statVisitorsToday: "Visitors today",
    statRevenue: "Revenue",
    statAvgOrder: "Average order",
    trafficTitle: (d) => `Traffic — last ${d} days`,
    topPagesTitle: "Most visited",
    noTrafficYet: "No visits recorded yet. Numbers start from the moment this went live.",
    salesTitle: (d) => `Sales — last ${d} days`,
    noCustomersYet: "No customers yet — profiles are built from orders as they come in.",
    custOrders: "Orders",
    custSpent: "Total spent",
    custAvg: "Average",
    custEvery: (n) => `Orders roughly every ${n} days`,
    custOnceOnly: "One order so far",
    custLastOrder: "Last order",
    custBought: "Bought",
    searchCustomers: "Search by name or contact",
    // Customer detail
    latestOrderTitle: "Latest order",
    orderPlacedAt: "Placed",
    custTotal: "Total",
    orderPromoLine: "Discount code",
    orderTierLine: "Wholesale tier",
    recipientName: "Recipient",
    phoneLabel: "Phone",
    addressLabel: "Address",
    orderNoteLine: "Order note",
    editInOrders: "Edit this order in Orders",
    internalNoteTitle: "Internal note",
    internalNoteHint: "Only staff see this. For what you want to remember about them — how they drink it, who to ask for, anything to watch.",
    internalNotePh: "e.g. prefers the honey batch, calls before 9am, delivers to the back door",
    saveNote: "Save note",
    noteSaved: "Saved",
    mostBoughtTitle: "Buys most often",
    orderHistoryTitle: "All orders",
    callCustomer: "Call",
    zaloCustomer: "Zalo",
    // Trade samples
    samplesTab: "Samples",
    samplesHint: "Requests from the trade sample link. Share it directly with café owners — it isn't in the site navigation:",
    noSamplesYet: "No sample requests yet.",
    free: "Free",
    qualShop: "Has a shop",
    qualRecipe: "Will build a recipe",
    qualFeedback: "Will report back",
    sampleNew: "New",
    sampleSent: "Sent",
    sampleConverted: "Became a partner",
    sampleDeclined: "Declined",
    sampleCreditNote: "What you pay comes off your first wholesale order.",
    sampleBarTitle: "Run a café or bar?",
    sampleBarSub: "Free sample pack to brew on your bar",
    // Referral
    referralTitle: "Invite a friend",
    referralExplain: "Share your code. Your friend gets 5% off their first order, and you get 5% off your next one once they've ordered.",
    referralYourCode: "Your code",
    referralCopied: "Copied",
    referralCopy: "Copy",
    referralCount: (n) => (n === 1 ? "1 friend has ordered" : `${n} friends have ordered`),
    referralRewardsReady: "Your rewards, ready to use at checkout:",
    referralNoRewards: "No rewards yet — they appear here once a friend orders with your code.",
    referralLookupTitle: "Your referral code",
    referralLookupHint: "Enter the phone or email you ordered with.",
    referralLookupBtn: "Show my code",
    referralNotACustomer: "We couldn't find an order for that phone or email. Referral codes are for customers who've ordered before.",
    promoSelfReferral: "That's your own referral code — share it with a friend instead.",
    promoUsedUp: "That code has already been used.",
    promoRewardNotYours: "That reward code belongs to another account.",
    movementToday: "Today at the house",
    movementRooms: "Where to go next",
    movementReach: "Reach us",
    privacyPolicy: "Privacy policy",
    deleteConfirm: "Delete for good?",
    deleteOrder: "Delete order",
    deleteOrderNote: "Removes the order and winds back its sold count. Stock is not restored — edit it in Catalog if needed.",
    deleteSessionNote: "Frees the day so it can be booked again.",
    deleteCustomer: "Delete this customer",
    deleteCustomerNote: (n) => `Deletes all ${n} of their orders and the internal note. Nothing else identifies them, so they disappear completely.`,
    binTab: "Trash",
    binHint: (d) => `Anything deleted in the Dashboard waits here for ${d} days, then goes for good. Restoring puts it back exactly as it was.`,
    binEmpty: "Nothing deleted recently.",
    binRestore: "Restore",
    binDaysLeft: (n) => (n <= 0 ? "Going now" : n === 1 ? "1 day left" : `${n} days left`),
    binTableName: (x) => ({ orders: "Order", leads: "Lead", sample_requests: "Sample request", tea_sessions: "Booking", customer_notes: "Customer note" }[x] || x),
    seeGallery: "See the whole gallery",
    quickAccess: "Jump to",
    allSections: "All sections",
    back: "Back",
    close: "Close",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    save: "Save article",
    titlePh: "Article title",
    bodyPh: "Content…",
    loading: "Loading…",
    noResults: "No results found.",
    noArticles: "No articles in this section yet.",
    results: (n, q) => `${n} results for "${q}"`,
    articleCount: (n) => `${n} sections`,
    comingSoon: "Coming soon",
    tradeIntro: "Volume pricing for our Everyday line, sold by the kilogram.",
    tradeQuoteNote: "This summary is a starting point, not a formal quotation — final pricing is confirmed by our team using our standard quotation template.",
    shopTitle: "Shop",
    shopBody: "A retail ordering flow is next on the roadmap — small-batch purchases for individual tea lovers.",
    orderTitle: "Build an Order",
    orderHint: "Enter quantities in kilograms for the products you need.",
    stepBrowse: "Browse & pick",
    stepYourOrder: "Your order",
    kg: "kg",
    totalKg: "Total volume",
    tierApplied: "Tier applied",
    summaryTitle: "Order Summary",
    emptyCart: "Add a quantity to at least one product to see your order summary.",
    copySummary: "Copy order summary",
    copied: "Copied",
    priceRef: "Reference pricing tiers",
    yourName: "Your name",
    yourContact: "Phone or email",
    yourAddress: "Delivery address",
    taxNumber: "Tax number (optional)",
    vatNote: "10% VAT applies to retail orders and will be added to the final invoice.",
    wholesaleDiscoveryPrompt: "Ordering in bulk? Wholesale pricing is available →",
    orderNote: "Got a question or something to add? Comments, changes, anything…",
    submitOrder: "Submit order",
    orderSent: "Order received — thank you! We'll confirm final pricing shortly.",
    emailFallback: "Email this order",
    nameRequired: "Please enter your name and contact so we can reach you.",
    frontDeskOrders: "Orders",
    frontDeskMessages: "Messages",
    noOrdersYet: "No orders yet.",
    noThreadsYet: "No conversations yet.",
    markRead: "Mark as read",
    newBadge: "New",
    contactLabel: "Contact",
    noteLabel: "Note",
    chatTitle: "Talk to the House",
    chatIntro: "Have a question? Message our team directly.",
    chatNamePh: "Your name",
    chatMsgPh: "Type a message…",
    chatSend: "Send",
    chatStart: "Start conversation",
    chatEmpty: "No messages yet — say hello.",
    replyPh: "Type a reply…",
    you: "You",
    admin: "House of Hoàng Long",
    pcs: "pack(s)",
    shopHint: "Enter the quantity of packs you'd like for each tea.",
    itemsTotal: "Items",
    onboardSkip: "Skip",
    onboardStepOf: (n, total) => `Step ${n} of ${total}`,
    onboardWelcomeTitle: "Welcome to the House",
    onboardWelcomeBody: "A family tea house since 1995, working ancient Hà Giang leaf through Japanese processing craft.",
    onboardOfferTitle: "What we offer",
    onboardOriginTitle: "Origin & Craft",
    onboardOriginBody: "Wild ancient tea trees from Hoàng Su Phì, steamed using Japanese technology.",
    onboardLibraryTitle: "The Tea Library",
    onboardLibraryBody: "Everyday café-grade teas and a small Reserve line for connoisseurs.",
    onboardInfoTitle: "Tell us about you",
    onboardInterestLabel: "I'm interested in",
    onboardWholesale: "Wholesale",
    onboardRetail: "Retail",
    onboardNamePh: "Your name",
    onboardContactPh: "Phone or email",
    onboardCTA: "Get Started",
    leadRequired: "Please enter your name and contact to continue.",
    frontDeskLeads: "Leads",
    noLeadsYet: "No leads yet.",
    interestedIn: "Interested in",
    leadFromAd: "Sample request (ad landing page)",
    trackOrder: "Track an order",
    trackOrderHint: "Enter your Order ID to check its status.",
    orderIdPh: "Order ID",
    lookupBtn: "Check status",
    orderNotFound: "No order found with that ID.",
    yourOrderId: "Your Order ID",
    orderIdSaveNote: "Save this ID to check your order status later.",
    paymentTitle: "Payment",
    paymentHint: "Complete payment by bank transfer using the details below.",
    paymentPending: "Bank transfer details will be confirmed by our team shortly.",
    paymentSettingsTitle: "Payment Settings",
    selectBank: "Select your bank",
    accountNumberLabel: "Account number",
    accountNameLabel: "Account holder name",
    saveSettings: "Save",
    savedNote: "Saved",
    transferContent: "Transfer content",
    frontDeskPayment: "Payment",
    orderStatusLabel: "Status",
    exportCsv: "Export CSV",
    catalogTitle: "Catalog",
    productNameEnPh: "Name (English)",
    productNameViPh: "Name (Vietnamese)",
    lineLabel: "Line",
    everydayOption: "Everyday (sold by kg — shown in both Wholesale and Shop)",
    reserveOption: "Reserve (sold by pack — Shop only)",
    productLineHint: "The photo and details are shared everywhere this product appears — this only controls which section(s) it's grouped into.",
    addProduct: "Add tea",
    saveProduct: "Save",
    deleteProduct: "Remove",
    reviewsTitle: "Reviews",
    reviewerNamePh: "Customer name",
    reviewQuotePh: "What they said…",
    addReview: "Add review",
    noReviewsYetAdmin: "No reviews added yet.",
    testimonialsHeading: "What our customers say",
    reorderTitle: "Ordered before?",
    reorderHint: "Enter your phone or email to load your last order.",
    reorderContactPh: "Phone or email",
    reorderBtn: "Load last order",
    reorderNotFound: "No previous order found for that contact.",
    reorderApplied: "Loaded your last order — review and submit again below.",
    printInvoice: "Print invoice",
    promoLabel: "Promo code",
    promoCodePh: "Enter promo code",
    applyPromo: "Apply",
    promoApplied: (code, pct) => `Applied: ${code} (-${pct}%)`,
    promoInvalid: "That code isn't valid or active.",
    promosTitle: "Promo codes",
    promoCodeFieldPh: "Code (e.g. TET10)",
    promoPercentPh: "Discount %",
    addPromo: "Add code",
    activate: "Activate",
    deactivate: "Deactivate",
    noPromosYet: "No promo codes yet.",
    affiliateNamePh: "Employee/affiliate name (optional)",
    usedCount: (n) => `Used ${n} time${n === 1 ? "" : "s"}`,
    tastingNotesEnPh: "Tasting notes, English (optional)",
    tastingNotesViPh: "Tasting notes, Vietnamese (optional)",
    flavorsEnPh: "Flavour tags EN, comma-separated",
    flavorsViPh: "Flavour tags VI, comma-separated",
    specPackSize: "Pack size",
    specBrew: "Brewing",
    frontDeskHouseTab: "The House",
    houseTabHint: "Shown at the top of Our Story. Leave blank to hide the whole block.",
    originStatsTitle: "Origin facts",
    originStatsPh: "One per line:\nvalue | English label | Vietnamese label\n1,200m | Altitude | Độ cao",
    producerTitle: "The person behind the tea",
    producerNamePh: "Name",
    producerRoleEnPh: "Role EN (e.g. Founder · 30 years)",
    producerRoleViPh: "Vai trò VI",
    producerQuoteEnPh: "Short quote, English (optional)",
    producerQuoteViPh: "Short quote, Vietnamese (optional)",
    producerPhotoLabel: "Upload portrait",
    saved: "Saved",
    brewEnPh: "Brew guide, English",
    brewViPh: "Brew guide, Vietnamese",
    packSizePh: "Pack size (e.g. 100g, 250g) — optional",
    photoUrlPh: "Photo URL (optional)",
    uploadPhotoLabel: "Or upload a photo",
    uploading: "Uploading…",
    uploadFailed: "Upload failed. Please check your connection and try again.",
    centerImageLabel: "Adjust image center (crop position)",
    pricePh: "Price in VND (optional)",
    sampleOption: "Sample Packs",
    estimatedTotal: "Estimated total (priced items)",
    priceNote: "Other items are priced separately by our team.",
    stockHaGiangPh: "Stock in Tuyên Quang (Hà Giang) warehouse",
    stockSocSonPh: "Stock in Sóc Sơn warehouse",
    batchPh: "Batch (optional, e.g. Batch #2025-11)",
    soldCountPh: "Sold count shown on the card (0 hides the badge)",
    warehouseHaGiang: "Tuyên Quang (Hà Giang)",
    warehouseSocSon: "Sóc Sơn",
    batchLabel: "Batch",
    stockLeft: (n) => `${n} left`,
    lastFew: "Only a few left!",
    fromPrice: (v) => `From ${v}`,
    chooseWeight: "Choose a size",
    limitedBadge: "Limited",
    shareExperienceTitle: "Share your experience",
    yourReviewNamePh: "Your name",
    yourReviewQuotePh: "Tell us what you thought…",
    submitReview: "Submit review",
    reviewSubmittedNote: "Thanks! Your review will appear after our team takes a quick look.",
    pendingApproval: "Pending approval",
    approve: "Approve",
    ratingSummary: (avg, n) => `${avg} ★ · ${n} review${n === 1 ? "" : "s"}`,
    soldBadge: (n) => `Sold ${n}+`,
    writeReview: "Write a review",
    yourRating: "Your rating",
    reviewContactPh: "Phone or email used on your order",
    reviewBodyPh: "What did you think of this tea?",
    noProductReviewsYet: "No reviews yet — be the first once you've tried it.",
    reviewsHeading: "Customer reviews",
    reviewErrorNotPurchased: "We couldn't find an order for this tea under that phone/email. Only customers who've bought it can review it.",
    reviewErrorAlready: "You've already reviewed this tea — thank you!",
    productReviewsTitle: "Product reviews",
    allProducts: "All products",
    noProductReviewsAdmin: "No product reviews yet.",
    cartBarItems: (n) => `${n} item${n === 1 ? "" : "s"}`,
    viewOrder: "View order",
    cartTitle: "Your Order",
    proceedToCheckout: "Proceed to checkout",
    yieldGuideTitle: "How Far Does 1kg Go?",
    replaySeal: "Replay",
    yieldGuideHint: "A general guide — actual yield depends on your steeping strength and recipe.",
    yieldLight: "Light (iced tea)",
    yieldStandard: "Standard",
    yieldConcentrate: "Concentrated (milk tea / cold brew base)",
    litersLabel: "liters",
    cupsApprox: (min, max) => `≈ ${min}–${max} cups (200–350ml)`,
    costPerLiterFrom: (v) => `from ${v} / liter`,
    paymentMethodLabel: "Payment method",
    payByQR: "Bank transfer (QR)",
    payByCash: "Cash",
    cashLockedNote: "First-time orders are paid by bank transfer. Cash becomes available after your first completed order.",
    cashConfirmedNote: "You've chosen to pay by cash. Please have the exact amount ready, or confirm payment details with our team.",
    missingDetailsHint: "No tasting notes or photo yet",
    addToOrder: "Add to order",
    addedToOrder: "Added",
    viewDetails: "Tap for details",
    quantityLabel: "Quantity",
    wholesaleGateTitle: "Registered Partners Only",
    wholesaleGateHint: "Sign in or create an account to view wholesale pricing and place an order.",
    authEmailPh: "Email",
    authPasswordPh: "Password",
    authPhonePh: "Phone (optional)",
    authSignupBtn: "Create account",
    authLoginBtn: "Sign in",
    authSwitchToLogin: "Already have an account? Sign in",
    authSwitchToSignup: "New here? Create an account",
    authCheckEmailTitle: "Check your email",
    authCheckEmailHint: "We sent a confirmation link to your email. Click it, then sign in here.",
    authError: "Something went wrong. Please try again.",
    wholesaleApplyTitle: "Apply for Wholesale Access",
    wholesaleApplyHint: "Tell us about your business — our team will review and approve your account.",
    wholesaleApplyBtn: "Submit application",
    wholesalePendingTitle: "Application Pending",
    wholesalePendingHint: "Thanks — our team is reviewing your application. You'll get wholesale pricing and ordering once approved.",
    partnerPendingBadge: "Pending",
    partnerVerifiedBadge: "Verified",
    approvePartnerBtn: "Approve",
    wholesaleAccountsTitle: "Wholesale Partners",
    businessNamePh: "Business / shop name",
    partnerCodePh: "Partner ID (e.g. WS-001)",
    addPartner: "Add partner",
    noPartnersYet: "No registered partners yet.",
    trackingCodeLabel: "Tracking code",
    parcelPhotoLabel: "Packed parcel photo",
    parcelPhotoUpload: "Add parcel photo",
    trackingCodePh: "Enter tracking code",
    saveTracking: "Save",
    noTrackingYet: "No tracking code yet",
    teaSessionCtaBtn: "Book a Private Tea Session",
    teaSessionModalTitle: "Private Tea Session",
    teaSessionPriceNote: "500,000đ per session · unlimited tea · one-on-one with Long at the tea room",
    teaSessionFreeNote: "Free for now · unlimited tea · one-on-one with Long at the tea room",
    teaSessionAddress: "36B Quốc lộ 2, Xã Sóc Sơn, Hà Nội",
    teaSessionDateLabel: "Choose a date",
    teaSessionTimeLabel: "Choose a time",
    teaSessionDateTaken: "Fully booked",
    teaSessionNotePh: "Anything you'd like Long to know before your visit? (optional)",
    teaSessionSubmitBtn: "Request this date",
    teaSessionSuccessTitle: "Request Sent",
    teaSessionPendingNote: "We'll confirm by phone/email once Long's schedule is set for that day — your session isn't final until then.",
    teaSessionErrorDateTaken: "Sorry, that date was just booked by someone else. Please pick another date.",
    teaSessionErrorGeneric: "Something went wrong. Please try again.",
    teaSessionBackBtn: "Book another date",
    frontDeskSessionsTab: "Tea Sessions",
    teaSessionNoneYet: "No tea session bookings yet.",
    teaSessionConfirmBtn: "Confirm",
    teaSessionCancelBtn: "Cancel booking",
    teaSessionStatusPending: "Pending",
    teaSessionStatusConfirmed: "Confirmed",
    teaSessionStatusCancelled: "Cancelled",
    testPackName: { en: "New Batch Test Pack (Free)", vi: "Gói Thử Mẻ Mới (Miễn phí)" },
    testPackOfferTitle: "New Batch Test Pack",
    testPackOfferHint: "As a returning partner, add a free sample of our newest batch to this order.",
    testPackCheckbox: "Add free test pack to this order",
    consentLabel: "I agree that House of Hoàng Long may store this information to process my request.",
    consentRequired: "Please confirm consent to continue.",
    statsWeekTitle: "This week",
    statsOrders: "Orders",
    statsWholesaleVolume: "Wholesale volume",
    statsLeads: "New leads",
    statsMessages: "Customer messages",
    outOfStock: "Out of stock",
    markAvailable: "Mark available",
    markOutOfStock: "Mark out of stock",
    loginTitle: "Internal Sign In",
    loginEmailPh: "Email",
    loginPasswordPh: "Password",
    loginBtn: "Sign in",
    loginError: "Incorrect email or password.",
    loginNotStaff: "This account doesn't have internal access yet. Contact an administrator.",
    logout: "Sign out",
    signedInAs: "Signed in as",
    orderFailed: "Something changed (likely stock) — please review your order and try again.",
  },
  vi: {
    welcome: "Chào mừng đến Nhà Hoàng Long",
    search: "Tìm trong Câu chuyện…",
    librarySearch: "Tìm trong Thư Viện…",
    libraryChooseSection: "Kiến thức trà nói chung — tách biệt với câu chuyện thương hiệu của nhà.",
    galleryTab: "Ảnh",
    readingTab: "Đọc thêm",
    emptyGallery: "Chưa có ảnh nào — quay lại sau nhé.",
    captionPh: "Chú thích (không bắt buộc)",
    addPhoto: "Thêm ảnh",
    addArticle: "Thêm bài",
    addToSection: "Thêm bài vào mục này",
    chooseSection: "Chọn một chuyên mục — sắp xếp theo thứ tự thường được khách quan tâm trước.",
    stillHaveQuestions: "Vẫn còn thắc mắc? Gọi",
    teaOfDayLabel: "Trà hôm nay",
    remove: "Xoá",
    overviewTab: "Tổng quan",
    customersTab: "Khách hàng",
    dashBack: "Bảng điều khiển",
    telegramTestTitle: "Thông báo Telegram",
    telegramTestHint: "Gửi một tin thử vào nhóm. Nếu không nhận được, dòng trả lời bên dưới sẽ cho biết đang sai ở đâu.",
    telegramTestSend: "Gửi tin thử",
    telegramTestOk: "Đã gửi. Kiểm tra nhóm — nếu thấy tin này thì đơn hàng mới cũng sẽ về theo đường đó.",
    telegramTestMissing: (names) => `Chưa khai báo trên bản chạy thật: ${names}. Thêm ở Vercel › Settings › Environment Variables rồi deploy lại.`,
    telegramTestUnauthorised: "Cần đăng nhập bằng tài khoản nội bộ.",
    telegramTestFailed: (why) => `Telegram từ chối: ${why}`,
    telegramConfigured: "TELEGRAM_CHAT_ID đang đặt là",
    telegramChatsTitle: "Các cuộc trò chuyện bot đã nhận tin",
    telegramChatsEmpty: "Chưa có. Hãy nhắn cho bot trong Telegram rồi bấm lại — bot chỉ thấy cuộc trò chuyện có tin nhắn trong 24 giờ qua. Trong nhóm thì gửi /start@tênbot; tin nhắn nhóm thông thường mặc định bị ẩn với bot.",
    dashGroup: (id) => ({
      today: "Hôm nay", people: "Khách hàng", shop: "Cửa hàng", house: "Nhà & sổ sách",
    }[id] || id),
    statVisitors: "Lượt khách",
    statViews: "Lượt xem trang",
    statVisitorsToday: "Khách hôm nay",
    statRevenue: "Doanh thu",
    statAvgOrder: "Giá trị đơn TB",
    trafficTitle: (d) => `Truy cập — ${d} ngày qua`,
    topPagesTitle: "Xem nhiều nhất",
    noTrafficYet: "Chưa ghi nhận lượt truy cập nào. Số liệu bắt đầu từ lúc tính năng này lên sóng.",
    salesTitle: (d) => `Doanh số — ${d} ngày qua`,
    noCustomersYet: "Chưa có khách hàng — hồ sơ được dựng từ đơn hàng khi đơn về.",
    custOrders: "Đơn hàng",
    custSpent: "Tổng chi",
    custAvg: "Trung bình",
    custEvery: (n) => `Khoảng ${n} ngày đặt một lần`,
    custOnceOnly: "Mới đặt một đơn",
    custLastOrder: "Đơn gần nhất",
    custBought: "Đã mua",
    searchCustomers: "Tìm theo tên hoặc số điện thoại",
    latestOrderTitle: "Đơn gần nhất",
    orderPlacedAt: "Thời gian đặt",
    custTotal: "Tổng tiền",
    orderPromoLine: "Mã giảm giá",
    orderTierLine: "Bậc giá sỉ",
    recipientName: "Người nhận",
    phoneLabel: "Số điện thoại",
    addressLabel: "Địa chỉ giao",
    orderNoteLine: "Ghi chú đơn",
    editInOrders: "Sửa đơn này ở tab Đơn hàng",
    internalNoteTitle: "Ghi chú nội bộ",
    internalNoteHint: "Chỉ nội bộ nhìn thấy. Ghi những gì cần nhớ về khách — gu uống, gọi ai, điều cần lưu ý.",
    internalNotePh: "vd: thích mẻ ướp mật, hay gọi trước 9h sáng, giao cửa sau",
    saveNote: "Lưu ghi chú",
    noteSaved: "Đã lưu",
    mostBoughtTitle: "Hay mua nhất",
    orderHistoryTitle: "Toàn bộ đơn hàng",
    callCustomer: "Gọi",
    zaloCustomer: "Zalo",
    samplesTab: "Trà mẫu",
    samplesHint: "Yêu cầu từ link trà mẫu. Gửi link trực tiếp cho chủ quán — link này không nằm trong menu:",
    noSamplesYet: "Chưa có yêu cầu trà mẫu nào.",
    free: "Miễn phí",
    qualShop: "Đang có quán",
    qualRecipe: "Sẽ dựng công thức",
    qualFeedback: "Sẽ phản hồi",
    sampleNew: "Mới",
    sampleSent: "Đã gửi",
    sampleConverted: "Đã thành đối tác",
    sampleDeclined: "Từ chối",
    sampleCreditNote: "Số tiền bạn trả sẽ được trừ vào đơn sỉ đầu tiên.",
    sampleBarTitle: "Bạn đang mở quán?",
    sampleBarSub: "Nhận gói trà mẫu miễn phí về pha thử",
    referralTitle: "Giới thiệu bạn bè",
    referralExplain: "Chia sẻ mã của bạn. Bạn của bạn được giảm 5% cho đơn đầu tiên, và bạn được giảm 5% cho đơn kế tiếp khi họ đặt hàng.",
    referralYourCode: "Mã của bạn",
    referralCopied: "Đã chép",
    referralCopy: "Chép",
    referralCount: (n) => `${n} người bạn đã đặt hàng`,
    referralRewardsReady: "Phần thưởng của bạn, dùng được khi thanh toán:",
    referralNoRewards: "Chưa có phần thưởng — sẽ xuất hiện ở đây khi bạn bè đặt hàng bằng mã của bạn.",
    referralLookupTitle: "Mã giới thiệu của bạn",
    referralLookupHint: "Nhập số điện thoại hoặc email bạn đã dùng để đặt hàng.",
    referralLookupBtn: "Xem mã của tôi",
    referralNotACustomer: "Không tìm thấy đơn hàng nào với số điện thoại/email đó. Mã giới thiệu dành cho khách đã từng đặt hàng.",
    promoSelfReferral: "Đây là mã giới thiệu của chính bạn — hãy chia sẻ cho bạn bè.",
    promoUsedUp: "Mã này đã được sử dụng.",
    promoRewardNotYours: "Mã thưởng này thuộc về tài khoản khác.",
    movementToday: "Hôm nay tại nhà trà",
    movementRooms: "Đi tiếp",
    privacyPolicy: "Chính sách quyền riêng tư",
    deleteConfirm: "Xoá hẳn?",
    deleteOrder: "Xoá đơn",
    deleteOrderNote: "Xoá đơn và trừ lại số đã bán. Không hoàn tồn kho — sửa trong tab Sản phẩm nếu cần.",
    deleteSessionNote: "Giải phóng ngày đó để khách khác đặt được.",
    deleteCustomer: "Xoá khách này",
    deleteCustomerNote: (n) => `Xoá toàn bộ ${n} đơn hàng và ghi chú nội bộ. Không còn gì nhận diện họ nữa.`,
    binTab: "Thùng rác",
    binHint: (d) => `Mọi thứ đã xoá trong Bảng điều khiển nằm ở đây ${d} ngày rồi mất hẳn. Khôi phục sẽ trả lại nguyên vẹn như cũ.`,
    binEmpty: "Chưa xoá gì gần đây.",
    binRestore: "Khôi phục",
    binDaysLeft: (n) => (n <= 0 ? "Sắp mất" : `Còn ${n} ngày`),
    binTableName: (x) => ({ orders: "Đơn hàng", leads: "Khách tiềm năng", sample_requests: "Yêu cầu mẫu", tea_sessions: "Lịch trà", customer_notes: "Ghi chú khách" }[x] || x),
    movementReach: "Liên hệ",
    seeGallery: "Xem toàn bộ thư viện ảnh",
    quickAccess: "Đi nhanh tới",
    allSections: "Tất cả chuyên mục",
    back: "Quay lại",
    close: "Đóng",
    cancel: "Huỷ",
    edit: "Sửa",
    delete: "Xoá",
    save: "Lưu bài viết",
    titlePh: "Tiêu đề bài viết",
    bodyPh: "Nội dung…",
    loading: "Đang tải…",
    noResults: "Không tìm thấy kết quả nào.",
    noArticles: "Chưa có bài viết trong mục này.",
    results: (n, q) => `${n} kết quả cho "${q}"`,
    articleCount: (n) => `${n} chuyên mục`,
    comingSoon: "Sắp ra mắt",
    tradeIntro: "Bậc giá theo sản lượng cho dòng Pha Chế, bán theo kg.",
    tradeQuoteNote: "Đây là bản tóm tắt sơ bộ, chưa phải báo giá chính thức — giá cuối cùng sẽ được đội ngũ xác nhận theo mẫu quotation chuẩn.",
    shopTitle: "Cửa hàng",
    shopBody: "Luồng đặt hàng lẻ đang trong kế hoạch tiếp theo — mua số lượng nhỏ cho khách yêu trà cá nhân.",
    orderTitle: "Tạo đơn hàng",
    orderHint: "Nhập số lượng (kg) cho các sản phẩm cần đặt.",
    stepBrowse: "Chọn sản phẩm",
    stepYourOrder: "Đơn hàng của bạn",
    kg: "kg",
    totalKg: "Tổng sản lượng",
    tierApplied: "Bậc giá áp dụng",
    summaryTitle: "Tóm tắt đơn hàng",
    emptyCart: "Nhập số lượng ít nhất một sản phẩm để xem tóm tắt đơn hàng.",
    copySummary: "Sao chép đơn hàng",
    copied: "Đã sao chép",
    priceRef: "Bảng giá tham khảo",
    yourName: "Tên của bạn",
    yourContact: "Số điện thoại hoặc email",
    yourAddress: "Địa chỉ giao hàng",
    taxNumber: "Mã số thuế (không bắt buộc)",
    vatNote: "Đơn lẻ áp dụng VAT 10%, sẽ được cộng vào hoá đơn cuối cùng.",
    wholesaleDiscoveryPrompt: "Đặt số lượng lớn? Xem giá sỉ →",
    orderNote: "Bạn có thắc mắc gì không? Bình luận, thay đổi, hay câu hỏi...?",
    submitOrder: "Gửi đơn hàng",
    orderSent: "Đã nhận đơn — cảm ơn a/chị! Bên em sẽ xác nhận giá cuối cùng sớm.",
    emailFallback: "Gửi đơn qua email",
    nameRequired: "Vui lòng nhập tên và số liên hệ để bên em liên lạc lại.",
    frontDeskOrders: "Đơn hàng",
    frontDeskMessages: "Tin nhắn",
    noOrdersYet: "Chưa có đơn hàng nào.",
    noThreadsYet: "Chưa có cuộc trò chuyện nào.",
    markRead: "Đánh dấu đã đọc",
    newBadge: "Mới",
    contactLabel: "Liên hệ",
    noteLabel: "Ghi chú",
    chatTitle: "Trò chuyện với Nhà Hoàng Long",
    chatIntro: "Có câu hỏi? Nhắn trực tiếp cho đội ngũ hỗ trợ.",
    chatNamePh: "Tên của bạn",
    chatMsgPh: "Nhập tin nhắn…",
    chatSend: "Gửi",
    chatStart: "Bắt đầu trò chuyện",
    chatEmpty: "Chưa có tin nhắn nào — chào một câu nhé.",
    replyPh: "Nhập phản hồi…",
    you: "Bạn",
    admin: "Nhà Hoàng Long",
    pcs: "gói",
    shopHint: "Nhập số lượng gói muốn mua cho mỗi loại trà.",
    itemsTotal: "Số món",
    onboardSkip: "Bỏ qua",
    onboardStepOf: (n, total) => `Bước ${n}/${total}`,
    onboardWelcomeTitle: "Chào mừng đến Nhà Hoàng Long",
    onboardWelcomeBody: "Thương hiệu trà gia đình từ 1995, làm trà cổ thụ Hà Giang bằng công nghệ Nhật Bản.",
    onboardOfferTitle: "Chúng tôi có gì",
    onboardOriginTitle: "Nguồn gốc & Công nghệ",
    onboardOriginBody: "Trà cổ thụ mọc tự nhiên tại Hoàng Su Phì, chế biến bằng công nghệ hấp Nhật Bản.",
    onboardLibraryTitle: "Trà & Sản phẩm",
    onboardLibraryBody: "Dòng Pha Chế dùng hàng ngày và dòng Thưởng cao cấp cho người sành trà.",
    onboardInfoTitle: "Cho em biết về a/chị",
    onboardInterestLabel: "Quan tâm đến",
    onboardWholesale: "Mua sỉ",
    onboardRetail: "Mua lẻ",
    onboardNamePh: "Tên của bạn",
    onboardContactPh: "Số điện thoại hoặc email",
    onboardCTA: "Bắt đầu",
    leadRequired: "Vui lòng nhập tên và liên hệ để tiếp tục.",
    frontDeskLeads: "Khách tiềm năng",
    noLeadsYet: "Chưa có khách tiềm năng nào.",
    interestedIn: "Quan tâm đến",
    leadFromAd: "Xin mẫu thử (trang quảng cáo)",
    trackOrder: "Theo dõi đơn hàng",
    trackOrderHint: "Nhập mã đơn hàng để kiểm tra trạng thái.",
    orderIdPh: "Mã đơn hàng",
    lookupBtn: "Kiểm tra",
    orderNotFound: "Không tìm thấy đơn hàng với mã này.",
    yourOrderId: "Mã đơn hàng của a/chị",
    orderIdSaveNote: "Lưu lại mã này để kiểm tra trạng thái đơn sau.",
    paymentTitle: "Thanh toán",
    paymentHint: "Hoàn tất thanh toán bằng chuyển khoản theo thông tin bên dưới.",
    paymentPending: "Thông tin chuyển khoản sẽ được đội ngũ xác nhận sớm.",
    paymentSettingsTitle: "Cài đặt thanh toán",
    selectBank: "Chọn ngân hàng",
    accountNumberLabel: "Số tài khoản",
    accountNameLabel: "Tên chủ tài khoản",
    saveSettings: "Lưu",
    savedNote: "Đã lưu",
    transferContent: "Nội dung chuyển khoản",
    frontDeskPayment: "Thanh toán",
    orderStatusLabel: "Trạng thái",
    exportCsv: "Xuất CSV",
    catalogTitle: "Sản phẩm",
    productNameEnPh: "Tên (tiếng Anh)",
    productNameViPh: "Tên (tiếng Việt)",
    lineLabel: "Dòng",
    everydayOption: "Pha Chế (bán theo kg — hiện ở cả Bán sỉ và Cửa hàng)",
    reserveOption: "Thưởng (bán theo gói — chỉ ở Cửa hàng)",
    productLineHint: "Ảnh và thông tin sản phẩm dùng chung ở mọi nơi sản phẩm này xuất hiện — mục này chỉ quyết định nó thuộc (những) mục nào.",
    addProduct: "Thêm loại trà",
    saveProduct: "Lưu",
    deleteProduct: "Xoá",
    reviewsTitle: "Đánh giá",
    reviewerNamePh: "Tên khách hàng",
    reviewQuotePh: "Khách nói gì…",
    addReview: "Thêm đánh giá",
    noReviewsYetAdmin: "Chưa có đánh giá nào.",
    testimonialsHeading: "Khách hàng nói gì về chúng tôi",
    reorderTitle: "Đã từng đặt hàng?",
    reorderHint: "Nhập số điện thoại/email để tải lại đơn gần nhất.",
    reorderContactPh: "Số điện thoại hoặc email",
    reorderBtn: "Tải đơn gần nhất",
    reorderNotFound: "Không tìm thấy đơn hàng trước đó với liên hệ này.",
    reorderApplied: "Đã tải đơn gần nhất — xem lại và gửi lại bên dưới.",
    printInvoice: "In hoá đơn",
    promoLabel: "Mã giảm giá",
    promoCodePh: "Nhập mã giảm giá",
    applyPromo: "Áp dụng",
    promoApplied: (code, pct) => `Đã áp dụng: ${code} (-${pct}%)`,
    promoInvalid: "Mã không hợp lệ hoặc đã hết hạn.",
    promosTitle: "Mã giảm giá",
    promoCodeFieldPh: "Mã (vd: TET10)",
    promoPercentPh: "% giảm",
    addPromo: "Thêm mã",
    activate: "Kích hoạt",
    deactivate: "Tắt",
    noPromosYet: "Chưa có mã giảm giá nào.",
    affiliateNamePh: "Tên nhân viên/affiliate (không bắt buộc)",
    usedCount: (n) => `Đã dùng ${n} lần`,
    tastingNotesEnPh: "Vị/hương vị, tiếng Anh (không bắt buộc)",
    tastingNotesViPh: "Vị/hương vị, tiếng Việt (không bắt buộc)",
    flavorsEnPh: "Tag hương vị EN, cách nhau bởi dấu phẩy",
    flavorsViPh: "Tag hương vị VI, cách nhau bởi dấu phẩy",
    specPackSize: "Quy cách",
    specBrew: "Cách pha",
    frontDeskHouseTab: "Trang nhà",
    houseTabHint: "Hiện ở đầu mục Câu chuyện. Để trống thì cả khối sẽ ẩn đi.",
    originStatsTitle: "Thông số vùng trồng",
    originStatsPh: "Mỗi dòng một mục:\ngiá trị | nhãn tiếng Anh | nhãn tiếng Việt\n1.200m | Altitude | Độ cao",
    producerTitle: "Người làm ra trà",
    producerNamePh: "Tên",
    producerRoleEnPh: "Vai trò EN (vd: Founder · 30 years)",
    producerRoleViPh: "Vai trò VI (vd: Người sáng lập · 30 năm)",
    producerQuoteEnPh: "Câu trích ngắn, tiếng Anh (không bắt buộc)",
    producerQuoteViPh: "Câu trích ngắn, tiếng Việt (không bắt buộc)",
    producerPhotoLabel: "Tải ảnh chân dung",
    saved: "Đã lưu",
    brewEnPh: "Gợi ý pha, tiếng Anh",
    brewViPh: "Gợi ý pha, tiếng Việt",
    packSizePh: "Quy cách đóng gói (vd: 100g, 250g) — không bắt buộc",
    photoUrlPh: "Link ảnh (không bắt buộc)",
    uploadPhotoLabel: "Hoặc upload ảnh trực tiếp",
    uploading: "Đang tải lên…",
    uploadFailed: "Tải ảnh lên thất bại. Kiểm tra kết nối mạng và thử lại.",
    centerImageLabel: "Chỉnh tâm ảnh (vị trí crop)",
    pricePh: "Giá (VNĐ, không bắt buộc)",
    sampleOption: "Gói Dùng Thử",
    estimatedTotal: "Tạm tính (sản phẩm đã niêm yết giá)",
    priceNote: "Các sản phẩm khác sẽ được đội ngũ báo giá riêng.",
    stockHaGiangPh: "Tồn kho tại kho Tuyên Quang (Hà Giang)",
    stockSocSonPh: "Tồn kho tại kho Sóc Sơn",
    batchPh: "Mẻ/Batch (không bắt buộc, vd: Mẻ #2025-11)",
    soldCountPh: "Lượt bán hiện trên thẻ (0 = ẩn)",
    warehouseHaGiang: "Tuyên Quang (Hà Giang)",
    warehouseSocSon: "Sóc Sơn",
    batchLabel: "Mẻ",
    stockLeft: (n) => `Còn ${n}`,
    lastFew: "Sắp hết hàng!",
    fromPrice: (v) => `Từ ${v}`,
    chooseWeight: "Chọn trọng lượng",
    limitedBadge: "Giới hạn",
    shareExperienceTitle: "Chia sẻ trải nghiệm của bạn",
    yourReviewNamePh: "Tên của bạn",
    yourReviewQuotePh: "Bạn thấy trà thế nào…",
    submitReview: "Gửi đánh giá",
    reviewSubmittedNote: "Cảm ơn a/chị! Đánh giá sẽ hiện sau khi đội ngũ xem qua.",
    pendingApproval: "Chờ duyệt",
    approve: "Duyệt",
    ratingSummary: (avg, n) => `${avg} ★ · ${n} đánh giá`,
    soldBadge: (n) => `Đã bán ${n}+`,
    writeReview: "Viết đánh giá",
    yourRating: "Đánh giá của bạn",
    reviewContactPh: "SĐT hoặc email đã dùng khi đặt hàng",
    reviewBodyPh: "A/chị thấy loại trà này thế nào?",
    noProductReviewsYet: "Chưa có đánh giá — hãy là người đầu tiên sau khi dùng thử.",
    reviewsHeading: "Đánh giá của khách",
    reviewErrorNotPurchased: "Không tìm thấy đơn hàng nào cho loại trà này với SĐT/email đó. Chỉ khách đã mua mới đánh giá được.",
    reviewErrorAlready: "A/chị đã đánh giá loại trà này rồi — cảm ơn a/chị!",
    productReviewsTitle: "Đánh giá theo sản phẩm",
    allProducts: "Tất cả sản phẩm",
    noProductReviewsAdmin: "Chưa có đánh giá sản phẩm nào.",
    cartBarItems: (n) => `${n} món`,
    viewOrder: "Xem đơn hàng",
    cartTitle: "Đơn hàng của bạn",
    proceedToCheckout: "Tới thanh toán",
    yieldGuideTitle: "1kg Trà Pha Được Bao Nhiêu Lít?",
    replaySeal: "Xem lại",
    yieldGuideHint: "Ước tính chung — hiệu suất thực tế tuỳ độ đậm nhạt và công thức pha của quán.",
    yieldLight: "Nhạt (trà đá)",
    yieldStandard: "Chuẩn",
    yieldConcentrate: "Đậm (nền trà sữa/cold brew)",
    litersLabel: "lít",
    cupsApprox: (min, max) => `≈ ${min}–${max} cốc (200–350ml)`,
    costPerLiterFrom: (v) => `từ ${v} / lít`,
    paymentMethodLabel: "Phương thức thanh toán",
    payByQR: "Chuyển khoản (QR)",
    payByCash: "Tiền mặt",
    cashLockedNote: "Đơn đầu tiên cần thanh toán qua chuyển khoản. Tiền mặt sẽ mở khoá sau khi a/chị hoàn tất đơn đầu tiên.",
    cashConfirmedNote: "A/chị đã chọn thanh toán tiền mặt. Vui lòng chuẩn bị đúng số tiền, hoặc xác nhận lại với đội ngũ.",
    missingDetailsHint: "Chưa có vị/hương vị hoặc ảnh",
    addToOrder: "Thêm vào đơn",
    addedToOrder: "Đã thêm",
    viewDetails: "Bấm để xem chi tiết",
    quantityLabel: "Số lượng",
    wholesaleGateTitle: "Chỉ dành cho đối tác đã đăng ký",
    wholesaleGateHint: "Đăng nhập hoặc tạo tài khoản để xem giá sỉ và đặt hàng.",
    authEmailPh: "Email",
    authPasswordPh: "Mật khẩu",
    authPhonePh: "Số điện thoại (không bắt buộc)",
    authSignupBtn: "Tạo tài khoản",
    authLoginBtn: "Đăng nhập",
    authSwitchToLogin: "Đã có tài khoản? Đăng nhập",
    authSwitchToSignup: "Chưa có tài khoản? Đăng ký",
    authCheckEmailTitle: "Kiểm tra email của bạn",
    authCheckEmailHint: "Chúng tôi đã gửi link xác nhận đến email của bạn. Bấm vào link đó rồi quay lại đăng nhập.",
    authError: "Có lỗi xảy ra. Vui lòng thử lại.",
    wholesaleApplyTitle: "Đăng Ký Làm Đối Tác Sỉ",
    wholesaleApplyHint: "Cho chúng tôi biết về doanh nghiệp của bạn — đội ngũ sẽ xem xét và duyệt tài khoản.",
    wholesaleApplyBtn: "Gửi đăng ký",
    wholesalePendingTitle: "Đang Chờ Duyệt",
    wholesalePendingHint: "Cảm ơn bạn — chúng tôi đang xem xét đăng ký này. Bạn sẽ thấy giá sỉ và đặt được hàng sau khi được duyệt.",
    partnerPendingBadge: "Chờ duyệt",
    partnerVerifiedBadge: "Đã duyệt",
    approvePartnerBtn: "Duyệt",
    wholesaleAccountsTitle: "Đối tác sỉ",
    businessNamePh: "Tên doanh nghiệp/cửa hàng",
    partnerCodePh: "Mã đối tác (vd: WS-001)",
    addPartner: "Thêm đối tác",
    noPartnersYet: "Chưa có đối tác nào đăng ký.",
    trackingCodeLabel: "Mã vận đơn",
    parcelPhotoLabel: "Ảnh kiện hàng đã đóng",
    parcelPhotoUpload: "Thêm ảnh kiện hàng",
    trackingCodePh: "Nhập mã vận đơn",
    saveTracking: "Lưu",
    noTrackingYet: "Chưa có mã vận đơn",
    teaSessionCtaBtn: "Đặt Lịch Buổi Trà Riêng",
    teaSessionModalTitle: "Buổi Trà Riêng",
    teaSessionPriceNote: "500.000đ/buổi · uống trà không giới hạn · 1-1 trực tiếp với Long tại phòng trà",
    teaSessionFreeNote: "Miễn phí (tạm thời) · uống trà không giới hạn · 1-1 trực tiếp với Long tại phòng trà",
    teaSessionAddress: "36B Quốc lộ 2, Xã Sóc Sơn, Hà Nội",
    teaSessionDateLabel: "Chọn ngày",
    teaSessionTimeLabel: "Chọn giờ",
    teaSessionDateTaken: "Đã kín lịch",
    teaSessionNotePh: "Có điều gì muốn Long biết trước khi ghé thăm không? (không bắt buộc)",
    teaSessionSubmitBtn: "Đặt lịch ngày này",
    teaSessionSuccessTitle: "Đã Gửi Yêu Cầu",
    teaSessionPendingNote: "Chúng tôi sẽ xác nhận qua điện thoại/email khi lịch của Long cho ngày đó đã chốt — buổi trà chỉ chính thức sau khi được xác nhận.",
    teaSessionErrorDateTaken: "Rất tiếc, ngày này vừa có người đặt trước. Vui lòng chọn ngày khác.",
    teaSessionErrorGeneric: "Có lỗi xảy ra. Vui lòng thử lại.",
    teaSessionBackBtn: "Đặt ngày khác",
    frontDeskSessionsTab: "Buổi trà riêng",
    teaSessionNoneYet: "Chưa có lịch đặt buổi trà riêng nào.",
    teaSessionConfirmBtn: "Xác nhận",
    teaSessionCancelBtn: "Huỷ lịch",
    teaSessionStatusPending: "Chờ xác nhận",
    teaSessionStatusConfirmed: "Đã xác nhận",
    teaSessionStatusCancelled: "Đã huỷ",
    testPackName: { en: "New Batch Test Pack (Free)", vi: "Gói Thử Mẻ Mới (Miễn phí)" },
    testPackOfferTitle: "Gói Thử Mẻ Mới",
    testPackOfferHint: "Vì là đối tác đã từng đặt hàng, a/chị có thể thêm mẫu miễn phí từ mẻ trà mới nhất vào đơn này.",
    testPackCheckbox: "Thêm gói thử miễn phí vào đơn này",
    consentLabel: "Tôi đồng ý để Nhà Hoàng Long lưu thông tin này để xử lý yêu cầu.",
    consentRequired: "Vui lòng xác nhận đồng ý để tiếp tục.",
    statsWeekTitle: "Tuần này",
    statsOrders: "Đơn hàng",
    statsWholesaleVolume: "Sản lượng sỉ",
    statsLeads: "Lead mới",
    statsMessages: "Tin nhắn khách",
    outOfStock: "Hết hàng",
    markAvailable: "Đánh dấu còn hàng",
    markOutOfStock: "Đánh dấu hết hàng",
    loginTitle: "Đăng nhập Nội bộ",
    loginEmailPh: "Email",
    loginPasswordPh: "Mật khẩu",
    loginBtn: "Đăng nhập",
    loginError: "Sai email hoặc mật khẩu.",
    loginNotStaff: "Tài khoản này chưa được cấp quyền nội bộ. Liên hệ quản trị viên.",
    logout: "Đăng xuất",
    signedInAs: "Đăng nhập với",
    orderFailed: "Có gì đó vừa thay đổi (có thể do tồn kho) — vui lòng kiểm tra lại đơn và thử lại.",
  },
};
